/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the communicationPreferences service. Represents a row in the &quot;collaborated_communicationPreferences&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.communicationPreferencesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.communicationPreferencesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see communicationPreferences
 * @see com.collaborated.entity.model.impl.communicationPreferencesImpl
 * @see com.collaborated.entity.model.impl.communicationPreferencesModelImpl
 * @generated
 */
@ProviderType
public interface communicationPreferencesModel extends BaseModel<communicationPreferences> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a communication preferences model instance should use the {@link communicationPreferences} interface instead.
	 */

	/**
	 * Returns the primary key of this communication preferences.
	 *
	 * @return the primary key of this communication preferences
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this communication preferences.
	 *
	 * @param primaryKey the primary key of this communication preferences
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_communication preferences of this communication preferences.
	 *
	 * @return the p k_communication preferences of this communication preferences
	 */
	public long getPK_communicationPreferences();

	/**
	 * Sets the p k_communication preferences of this communication preferences.
	 *
	 * @param PK_communicationPreferences the p k_communication preferences of this communication preferences
	 */
	public void setPK_communicationPreferences(long PK_communicationPreferences);

	/**
	 * Returns the group ID of this communication preferences.
	 *
	 * @return the group ID of this communication preferences
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this communication preferences.
	 *
	 * @param groupId the group ID of this communication preferences
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this communication preferences.
	 *
	 * @return the user ID of this communication preferences
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this communication preferences.
	 *
	 * @param userId the user ID of this communication preferences
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this communication preferences.
	 *
	 * @return the user uuid of this communication preferences
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this communication preferences.
	 *
	 * @param userUuid the user uuid of this communication preferences
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this communication preferences.
	 *
	 * @return the create date of this communication preferences
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this communication preferences.
	 *
	 * @param createDate the create date of this communication preferences
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this communication preferences.
	 *
	 * @return the modified date of this communication preferences
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this communication preferences.
	 *
	 * @param modifiedDate the modified date of this communication preferences
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the primary language ID of this communication preferences.
	 *
	 * @return the primary language ID of this communication preferences
	 */
	public long getPrimaryLanguageId();

	/**
	 * Sets the primary language ID of this communication preferences.
	 *
	 * @param primaryLanguageId the primary language ID of this communication preferences
	 */
	public void setPrimaryLanguageId(long primaryLanguageId);

	/**
	 * Returns the primary language name of this communication preferences.
	 *
	 * @return the primary language name of this communication preferences
	 */
	@AutoEscape
	public String getPrimaryLanguageName();

	/**
	 * Sets the primary language name of this communication preferences.
	 *
	 * @param primaryLanguageName the primary language name of this communication preferences
	 */
	public void setPrimaryLanguageName(String primaryLanguageName);

	/**
	 * Returns the secondary language ID of this communication preferences.
	 *
	 * @return the secondary language ID of this communication preferences
	 */
	public long getSecondaryLanguageId();

	/**
	 * Sets the secondary language ID of this communication preferences.
	 *
	 * @param secondaryLanguageId the secondary language ID of this communication preferences
	 */
	public void setSecondaryLanguageId(long secondaryLanguageId);

	/**
	 * Returns the secondary language name of this communication preferences.
	 *
	 * @return the secondary language name of this communication preferences
	 */
	@AutoEscape
	public String getSecondaryLanguageName();

	/**
	 * Sets the secondary language name of this communication preferences.
	 *
	 * @param secondaryLanguageName the secondary language name of this communication preferences
	 */
	public void setSecondaryLanguageName(String secondaryLanguageName);

	/**
	 * Returns the tertiary language ID of this communication preferences.
	 *
	 * @return the tertiary language ID of this communication preferences
	 */
	public long getTertiaryLanguageId();

	/**
	 * Sets the tertiary language ID of this communication preferences.
	 *
	 * @param tertiaryLanguageId the tertiary language ID of this communication preferences
	 */
	public void setTertiaryLanguageId(long tertiaryLanguageId);

	/**
	 * Returns the tertiary language name of this communication preferences.
	 *
	 * @return the tertiary language name of this communication preferences
	 */
	@AutoEscape
	public String getTertiaryLanguageName();

	/**
	 * Sets the tertiary language name of this communication preferences.
	 *
	 * @param tertiaryLanguageName the tertiary language name of this communication preferences
	 */
	public void setTertiaryLanguageName(String tertiaryLanguageName);

	/**
	 * Returns the email address of this communication preferences.
	 *
	 * @return the email address of this communication preferences
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this communication preferences.
	 *
	 * @param emailAddress the email address of this communication preferences
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the phone number of this communication preferences.
	 *
	 * @return the phone number of this communication preferences
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this communication preferences.
	 *
	 * @param phoneNumber the phone number of this communication preferences
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the mobile number of this communication preferences.
	 *
	 * @return the mobile number of this communication preferences
	 */
	@AutoEscape
	public String getMobileNumber();

	/**
	 * Sets the mobile number of this communication preferences.
	 *
	 * @param mobileNumber the mobile number of this communication preferences
	 */
	public void setMobileNumber(String mobileNumber);

	/**
	 * Returns the website of this communication preferences.
	 *
	 * @return the website of this communication preferences
	 */
	@AutoEscape
	public String getWebsite();

	/**
	 * Sets the website of this communication preferences.
	 *
	 * @param website the website of this communication preferences
	 */
	public void setWebsite(String website);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.communicationPreferences communicationPreferences);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.communicationPreferences> toCacheModel();

	@Override
	public com.collaborated.entity.model.communicationPreferences toEscapedModel();

	@Override
	public com.collaborated.entity.model.communicationPreferences toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}