/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the commonWebsserviceAPI service. Represents a row in the &quot;collaborated_commonWebsserviceAPI&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.commonWebsserviceAPIModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.commonWebsserviceAPIImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see commonWebsserviceAPI
 * @see com.collaborated.entity.model.impl.commonWebsserviceAPIImpl
 * @see com.collaborated.entity.model.impl.commonWebsserviceAPIModelImpl
 * @generated
 */
@ProviderType
public interface commonWebsserviceAPIModel extends BaseModel<commonWebsserviceAPI> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a common websservice a p i model instance should use the {@link commonWebsserviceAPI} interface instead.
	 */

	/**
	 * Returns the primary key of this common websservice a p i.
	 *
	 * @return the primary key of this common websservice a p i
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this common websservice a p i.
	 *
	 * @param primaryKey the primary key of this common websservice a p i
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the common a p i ID of this common websservice a p i.
	 *
	 * @return the common a p i ID of this common websservice a p i
	 */
	public long getCommonAPIId();

	/**
	 * Sets the common a p i ID of this common websservice a p i.
	 *
	 * @param commonAPIId the common a p i ID of this common websservice a p i
	 */
	public void setCommonAPIId(long commonAPIId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.commonWebsserviceAPI commonWebsserviceAPI);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.commonWebsserviceAPI> toCacheModel();

	@Override
	public com.collaborated.entity.model.commonWebsserviceAPI toEscapedModel();

	@Override
	public com.collaborated.entity.model.commonWebsserviceAPI toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}