/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Custom_CalendarInvitees service. Represents a row in the &quot;collaborated_Custom_CalendarInvitees&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.Custom_CalendarInviteesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.Custom_CalendarInviteesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Custom_CalendarInvitees
 * @see com.collaborated.entity.model.impl.Custom_CalendarInviteesImpl
 * @see com.collaborated.entity.model.impl.Custom_CalendarInviteesModelImpl
 * @generated
 */
@ProviderType
public interface Custom_CalendarInviteesModel extends BaseModel<Custom_CalendarInvitees> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom_ calendar invitees model instance should use the {@link Custom_CalendarInvitees} interface instead.
	 */

	/**
	 * Returns the primary key of this custom_ calendar invitees.
	 *
	 * @return the primary key of this custom_ calendar invitees
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this custom_ calendar invitees.
	 *
	 * @param primaryKey the primary key of this custom_ calendar invitees
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_calendar event sub ID of this custom_ calendar invitees.
	 *
	 * @return the p k_calendar event sub ID of this custom_ calendar invitees
	 */
	public long getPK_calendarEventSubId();

	/**
	 * Sets the p k_calendar event sub ID of this custom_ calendar invitees.
	 *
	 * @param PK_calendarEventSubId the p k_calendar event sub ID of this custom_ calendar invitees
	 */
	public void setPK_calendarEventSubId(long PK_calendarEventSubId);

	/**
	 * Returns the group ID of this custom_ calendar invitees.
	 *
	 * @return the group ID of this custom_ calendar invitees
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this custom_ calendar invitees.
	 *
	 * @param groupId the group ID of this custom_ calendar invitees
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this custom_ calendar invitees.
	 *
	 * @return the user ID of this custom_ calendar invitees
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this custom_ calendar invitees.
	 *
	 * @param userId the user ID of this custom_ calendar invitees
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this custom_ calendar invitees.
	 *
	 * @return the user uuid of this custom_ calendar invitees
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this custom_ calendar invitees.
	 *
	 * @param userUuid the user uuid of this custom_ calendar invitees
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this custom_ calendar invitees.
	 *
	 * @return the create date of this custom_ calendar invitees
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this custom_ calendar invitees.
	 *
	 * @param createDate the create date of this custom_ calendar invitees
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this custom_ calendar invitees.
	 *
	 * @return the modified date of this custom_ calendar invitees
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this custom_ calendar invitees.
	 *
	 * @param modifiedDate the modified date of this custom_ calendar invitees
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the p k_calendar event ID of this custom_ calendar invitees.
	 *
	 * @return the p k_calendar event ID of this custom_ calendar invitees
	 */
	public long getPK_calendarEventId();

	/**
	 * Sets the p k_calendar event ID of this custom_ calendar invitees.
	 *
	 * @param PK_calendarEventId the p k_calendar event ID of this custom_ calendar invitees
	 */
	public void setPK_calendarEventId(long PK_calendarEventId);

	/**
	 * Returns the invitee email address of this custom_ calendar invitees.
	 *
	 * @return the invitee email address of this custom_ calendar invitees
	 */
	@AutoEscape
	public String getInviteeEmailAddress();

	/**
	 * Sets the invitee email address of this custom_ calendar invitees.
	 *
	 * @param inviteeEmailAddress the invitee email address of this custom_ calendar invitees
	 */
	public void setInviteeEmailAddress(String inviteeEmailAddress);

	/**
	 * Returns the invitee of this custom_ calendar invitees.
	 *
	 * @return the invitee of this custom_ calendar invitees
	 */
	public long getInvitee();

	/**
	 * Sets the invitee of this custom_ calendar invitees.
	 *
	 * @param invitee the invitee of this custom_ calendar invitees
	 */
	public void setInvitee(long invitee);

	/**
	 * Returns the status of this custom_ calendar invitees.
	 *
	 * @return the status of this custom_ calendar invitees
	 */
	public int getStatus();

	/**
	 * Sets the status of this custom_ calendar invitees.
	 *
	 * @param status the status of this custom_ calendar invitees
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Custom_CalendarInvitees custom_CalendarInvitees);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Custom_CalendarInvitees> toCacheModel();

	@Override
	public Custom_CalendarInvitees toEscapedModel();

	@Override
	public Custom_CalendarInvitees toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}