/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Custom_Workflow_Completed service. Represents a row in the &quot;collaborated_Custom_Workflow_Completed&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.Custom_Workflow_CompletedModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.Custom_Workflow_CompletedImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Custom_Workflow_Completed
 * @see com.collaborated.entity.model.impl.Custom_Workflow_CompletedImpl
 * @see com.collaborated.entity.model.impl.Custom_Workflow_CompletedModelImpl
 * @generated
 */
@ProviderType
public interface Custom_Workflow_CompletedModel extends BaseModel<Custom_Workflow_Completed> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom_ workflow_ completed model instance should use the {@link Custom_Workflow_Completed} interface instead.
	 */

	/**
	 * Returns the primary key of this custom_ workflow_ completed.
	 *
	 * @return the primary key of this custom_ workflow_ completed
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this custom_ workflow_ completed.
	 *
	 * @param primaryKey the primary key of this custom_ workflow_ completed
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the c ID of this custom_ workflow_ completed.
	 *
	 * @return the c ID of this custom_ workflow_ completed
	 */
	public long getCId();

	/**
	 * Sets the c ID of this custom_ workflow_ completed.
	 *
	 * @param cId the c ID of this custom_ workflow_ completed
	 */
	public void setCId(long cId);

	/**
	 * Returns the tracking ID of this custom_ workflow_ completed.
	 *
	 * @return the tracking ID of this custom_ workflow_ completed
	 */
	public long getTrackingId();

	/**
	 * Sets the tracking ID of this custom_ workflow_ completed.
	 *
	 * @param trackingId the tracking ID of this custom_ workflow_ completed
	 */
	public void setTrackingId(long trackingId);

	/**
	 * Returns the workflow ID of this custom_ workflow_ completed.
	 *
	 * @return the workflow ID of this custom_ workflow_ completed
	 */
	public long getWorkflowId();

	/**
	 * Sets the workflow ID of this custom_ workflow_ completed.
	 *
	 * @param workflowId the workflow ID of this custom_ workflow_ completed
	 */
	public void setWorkflowId(long workflowId);

	/**
	 * Returns the workflow task ID of this custom_ workflow_ completed.
	 *
	 * @return the workflow task ID of this custom_ workflow_ completed
	 */
	@AutoEscape
	public String getWorkflowTaskId();

	/**
	 * Sets the workflow task ID of this custom_ workflow_ completed.
	 *
	 * @param workflowTaskId the workflow task ID of this custom_ workflow_ completed
	 */
	public void setWorkflowTaskId(String workflowTaskId);

	/**
	 * Returns the trasition ID of this custom_ workflow_ completed.
	 *
	 * @return the trasition ID of this custom_ workflow_ completed
	 */
	public long getTrasitionId();

	/**
	 * Sets the trasition ID of this custom_ workflow_ completed.
	 *
	 * @param trasitionId the trasition ID of this custom_ workflow_ completed
	 */
	public void setTrasitionId(long trasitionId);

	/**
	 * Returns the log description of this custom_ workflow_ completed.
	 *
	 * @return the log description of this custom_ workflow_ completed
	 */
	@AutoEscape
	public String getLogDescription();

	/**
	 * Sets the log description of this custom_ workflow_ completed.
	 *
	 * @param logDescription the log description of this custom_ workflow_ completed
	 */
	public void setLogDescription(String logDescription);

	/**
	 * Returns the comments of this custom_ workflow_ completed.
	 *
	 * @return the comments of this custom_ workflow_ completed
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this custom_ workflow_ completed.
	 *
	 * @param comments the comments of this custom_ workflow_ completed
	 */
	public void setComments(String comments);

	/**
	 * Returns the completed date of this custom_ workflow_ completed.
	 *
	 * @return the completed date of this custom_ workflow_ completed
	 */
	public Date getCompletedDate();

	/**
	 * Sets the completed date of this custom_ workflow_ completed.
	 *
	 * @param completedDate the completed date of this custom_ workflow_ completed
	 */
	public void setCompletedDate(Date completedDate);

	/**
	 * Returns the user ID of this custom_ workflow_ completed.
	 *
	 * @return the user ID of this custom_ workflow_ completed
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this custom_ workflow_ completed.
	 *
	 * @param userId the user ID of this custom_ workflow_ completed
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this custom_ workflow_ completed.
	 *
	 * @return the user uuid of this custom_ workflow_ completed
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this custom_ workflow_ completed.
	 *
	 * @param userUuid the user uuid of this custom_ workflow_ completed
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this custom_ workflow_ completed.
	 *
	 * @return the created date of this custom_ workflow_ completed
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this custom_ workflow_ completed.
	 *
	 * @param createdDate the created date of this custom_ workflow_ completed
	 */
	public void setCreatedDate(Date createdDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Custom_Workflow_Completed custom_Workflow_Completed);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Custom_Workflow_Completed> toCacheModel();

	@Override
	public Custom_Workflow_Completed toEscapedModel();

	@Override
	public Custom_Workflow_Completed toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}