/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Custom_WorkflowLog service. Represents a row in the &quot;collaborated_Custom_WorkflowLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.Custom_WorkflowLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.Custom_WorkflowLogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Custom_WorkflowLog
 * @see com.collaborated.entity.model.impl.Custom_WorkflowLogImpl
 * @see com.collaborated.entity.model.impl.Custom_WorkflowLogModelImpl
 * @generated
 */
@ProviderType
public interface Custom_WorkflowLogModel extends BaseModel<Custom_WorkflowLog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom_ workflow log model instance should use the {@link Custom_WorkflowLog} interface instead.
	 */

	/**
	 * Returns the primary key of this custom_ workflow log.
	 *
	 * @return the primary key of this custom_ workflow log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this custom_ workflow log.
	 *
	 * @param primaryKey the primary key of this custom_ workflow log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the log ID of this custom_ workflow log.
	 *
	 * @return the log ID of this custom_ workflow log
	 */
	public long getLogId();

	/**
	 * Sets the log ID of this custom_ workflow log.
	 *
	 * @param logId the log ID of this custom_ workflow log
	 */
	public void setLogId(long logId);

	/**
	 * Returns the tracking ID of this custom_ workflow log.
	 *
	 * @return the tracking ID of this custom_ workflow log
	 */
	public long getTrackingId();

	/**
	 * Sets the tracking ID of this custom_ workflow log.
	 *
	 * @param trackingId the tracking ID of this custom_ workflow log
	 */
	public void setTrackingId(long trackingId);

	/**
	 * Returns the workflow ID of this custom_ workflow log.
	 *
	 * @return the workflow ID of this custom_ workflow log
	 */
	public long getWorkflowId();

	/**
	 * Sets the workflow ID of this custom_ workflow log.
	 *
	 * @param workflowId the workflow ID of this custom_ workflow log
	 */
	public void setWorkflowId(long workflowId);

	/**
	 * Returns the workflow task ID of this custom_ workflow log.
	 *
	 * @return the workflow task ID of this custom_ workflow log
	 */
	@AutoEscape
	public String getWorkflowTaskId();

	/**
	 * Sets the workflow task ID of this custom_ workflow log.
	 *
	 * @param workflowTaskId the workflow task ID of this custom_ workflow log
	 */
	public void setWorkflowTaskId(String workflowTaskId);

	/**
	 * Returns the trasition ID of this custom_ workflow log.
	 *
	 * @return the trasition ID of this custom_ workflow log
	 */
	public long getTrasitionId();

	/**
	 * Sets the trasition ID of this custom_ workflow log.
	 *
	 * @param trasitionId the trasition ID of this custom_ workflow log
	 */
	public void setTrasitionId(long trasitionId);

	/**
	 * Returns the log description of this custom_ workflow log.
	 *
	 * @return the log description of this custom_ workflow log
	 */
	@AutoEscape
	public String getLogDescription();

	/**
	 * Sets the log description of this custom_ workflow log.
	 *
	 * @param logDescription the log description of this custom_ workflow log
	 */
	public void setLogDescription(String logDescription);

	/**
	 * Returns the comments of this custom_ workflow log.
	 *
	 * @return the comments of this custom_ workflow log
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this custom_ workflow log.
	 *
	 * @param comments the comments of this custom_ workflow log
	 */
	public void setComments(String comments);

	/**
	 * Returns the assignee class p k of this custom_ workflow log.
	 *
	 * @return the assignee class p k of this custom_ workflow log
	 */
	public long getAssigneeClassPK();

	/**
	 * Sets the assignee class p k of this custom_ workflow log.
	 *
	 * @param assigneeClassPK the assignee class p k of this custom_ workflow log
	 */
	public void setAssigneeClassPK(long assigneeClassPK);

	/**
	 * Returns the class name of this custom_ workflow log.
	 *
	 * @return the class name of this custom_ workflow log
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this custom_ workflow log.
	 *
	 * @param className the class name of this custom_ workflow log
	 */
	public void setClassName(String className);

	/**
	 * Returns the assigned date of this custom_ workflow log.
	 *
	 * @return the assigned date of this custom_ workflow log
	 */
	public Date getAssignedDate();

	/**
	 * Sets the assigned date of this custom_ workflow log.
	 *
	 * @param assignedDate the assigned date of this custom_ workflow log
	 */
	public void setAssignedDate(Date assignedDate);

	/**
	 * Returns the completed date of this custom_ workflow log.
	 *
	 * @return the completed date of this custom_ workflow log
	 */
	public Date getCompletedDate();

	/**
	 * Sets the completed date of this custom_ workflow log.
	 *
	 * @param completedDate the completed date of this custom_ workflow log
	 */
	public void setCompletedDate(Date completedDate);

	/**
	 * Returns the created by of this custom_ workflow log.
	 *
	 * @return the created by of this custom_ workflow log
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this custom_ workflow log.
	 *
	 * @param createdBy the created by of this custom_ workflow log
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the created date of this custom_ workflow log.
	 *
	 * @return the created date of this custom_ workflow log
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this custom_ workflow log.
	 *
	 * @param createdDate the created date of this custom_ workflow log
	 */
	public void setCreatedDate(Date createdDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Custom_WorkflowLog custom_WorkflowLog);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Custom_WorkflowLog> toCacheModel();

	@Override
	public Custom_WorkflowLog toEscapedModel();

	@Override
	public Custom_WorkflowLog toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}