/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Custom_Calendar service. Represents a row in the &quot;collaborated_Custom_Calendar&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.Custom_CalendarModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.Custom_CalendarImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Custom_Calendar
 * @see com.collaborated.entity.model.impl.Custom_CalendarImpl
 * @see com.collaborated.entity.model.impl.Custom_CalendarModelImpl
 * @generated
 */
@ProviderType
public interface Custom_CalendarModel extends BaseModel<Custom_Calendar> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom_ calendar model instance should use the {@link Custom_Calendar} interface instead.
	 */

	/**
	 * Returns the primary key of this custom_ calendar.
	 *
	 * @return the primary key of this custom_ calendar
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this custom_ calendar.
	 *
	 * @param primaryKey the primary key of this custom_ calendar
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_calendar event ID of this custom_ calendar.
	 *
	 * @return the p k_calendar event ID of this custom_ calendar
	 */
	public long getPK_calendarEventId();

	/**
	 * Sets the p k_calendar event ID of this custom_ calendar.
	 *
	 * @param PK_calendarEventId the p k_calendar event ID of this custom_ calendar
	 */
	public void setPK_calendarEventId(long PK_calendarEventId);

	/**
	 * Returns the group ID of this custom_ calendar.
	 *
	 * @return the group ID of this custom_ calendar
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this custom_ calendar.
	 *
	 * @param groupId the group ID of this custom_ calendar
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this custom_ calendar.
	 *
	 * @return the user ID of this custom_ calendar
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this custom_ calendar.
	 *
	 * @param userId the user ID of this custom_ calendar
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this custom_ calendar.
	 *
	 * @return the user uuid of this custom_ calendar
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this custom_ calendar.
	 *
	 * @param userUuid the user uuid of this custom_ calendar
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this custom_ calendar.
	 *
	 * @return the create date of this custom_ calendar
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this custom_ calendar.
	 *
	 * @param createDate the create date of this custom_ calendar
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this custom_ calendar.
	 *
	 * @return the modified date of this custom_ calendar
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this custom_ calendar.
	 *
	 * @param modifiedDate the modified date of this custom_ calendar
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the calendar resource ID of this custom_ calendar.
	 *
	 * @return the calendar resource ID of this custom_ calendar
	 */
	public long getCalendarResourceId();

	/**
	 * Sets the calendar resource ID of this custom_ calendar.
	 *
	 * @param calendarResourceId the calendar resource ID of this custom_ calendar
	 */
	public void setCalendarResourceId(long calendarResourceId);

	/**
	 * Returns the time zone ID of this custom_ calendar.
	 *
	 * @return the time zone ID of this custom_ calendar
	 */
	@AutoEscape
	public String getTimeZoneId();

	/**
	 * Sets the time zone ID of this custom_ calendar.
	 *
	 * @param timeZoneId the time zone ID of this custom_ calendar
	 */
	public void setTimeZoneId(String timeZoneId);

	/**
	 * Returns the start date of this custom_ calendar.
	 *
	 * @return the start date of this custom_ calendar
	 */
	@AutoEscape
	public String getStartDate();

	/**
	 * Sets the start date of this custom_ calendar.
	 *
	 * @param startDate the start date of this custom_ calendar
	 */
	public void setStartDate(String startDate);

	/**
	 * Returns the end date of this custom_ calendar.
	 *
	 * @return the end date of this custom_ calendar
	 */
	@AutoEscape
	public String getEndDate();

	/**
	 * Sets the end date of this custom_ calendar.
	 *
	 * @param endDate the end date of this custom_ calendar
	 */
	public void setEndDate(String endDate);

	/**
	 * Returns the start time of this custom_ calendar.
	 *
	 * @return the start time of this custom_ calendar
	 */
	@AutoEscape
	public String getStartTime();

	/**
	 * Sets the start time of this custom_ calendar.
	 *
	 * @param startTime the start time of this custom_ calendar
	 */
	public void setStartTime(String startTime);

	/**
	 * Returns the end time of this custom_ calendar.
	 *
	 * @return the end time of this custom_ calendar
	 */
	@AutoEscape
	public String getEndTime();

	/**
	 * Sets the end time of this custom_ calendar.
	 *
	 * @param endTime the end time of this custom_ calendar
	 */
	public void setEndTime(String endTime);

	/**
	 * Returns the event title of this custom_ calendar.
	 *
	 * @return the event title of this custom_ calendar
	 */
	@AutoEscape
	public String getEventTitle();

	/**
	 * Sets the event title of this custom_ calendar.
	 *
	 * @param eventTitle the event title of this custom_ calendar
	 */
	public void setEventTitle(String eventTitle);

	/**
	 * Returns the event location of this custom_ calendar.
	 *
	 * @return the event location of this custom_ calendar
	 */
	@AutoEscape
	public String getEventLocation();

	/**
	 * Sets the event location of this custom_ calendar.
	 *
	 * @param eventLocation the event location of this custom_ calendar
	 */
	public void setEventLocation(String eventLocation);

	/**
	 * Returns the all day of this custom_ calendar.
	 *
	 * @return the all day of this custom_ calendar
	 */
	public int getAllDay();

	/**
	 * Sets the all day of this custom_ calendar.
	 *
	 * @param allDay the all day of this custom_ calendar
	 */
	public void setAllDay(int allDay);

	/**
	 * Returns the repeat of this custom_ calendar.
	 *
	 * @return the repeat of this custom_ calendar
	 */
	@AutoEscape
	public String getRepeat();

	/**
	 * Sets the repeat of this custom_ calendar.
	 *
	 * @param repeat the repeat of this custom_ calendar
	 */
	public void setRepeat(String repeat);

	/**
	 * Returns the end repeat of this custom_ calendar.
	 *
	 * @return the end repeat of this custom_ calendar
	 */
	@AutoEscape
	public String getEndRepeat();

	/**
	 * Sets the end repeat of this custom_ calendar.
	 *
	 * @param endRepeat the end repeat of this custom_ calendar
	 */
	public void setEndRepeat(String endRepeat);

	/**
	 * Returns the end repeat date of this custom_ calendar.
	 *
	 * @return the end repeat date of this custom_ calendar
	 */
	@AutoEscape
	public String getEndRepeatDate();

	/**
	 * Sets the end repeat date of this custom_ calendar.
	 *
	 * @param endRepeatDate the end repeat date of this custom_ calendar
	 */
	public void setEndRepeatDate(String endRepeatDate);

	/**
	 * Returns the alert of this custom_ calendar.
	 *
	 * @return the alert of this custom_ calendar
	 */
	@AutoEscape
	public String getAlert();

	/**
	 * Sets the alert of this custom_ calendar.
	 *
	 * @param alert the alert of this custom_ calendar
	 */
	public void setAlert(String alert);

	/**
	 * Returns the url of this custom_ calendar.
	 *
	 * @return the url of this custom_ calendar
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this custom_ calendar.
	 *
	 * @param url the url of this custom_ calendar
	 */
	public void setUrl(String url);

	/**
	 * Returns the notes of this custom_ calendar.
	 *
	 * @return the notes of this custom_ calendar
	 */
	@AutoEscape
	public String getNotes();

	/**
	 * Sets the notes of this custom_ calendar.
	 *
	 * @param notes the notes of this custom_ calendar
	 */
	public void setNotes(String notes);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Custom_Calendar custom_Calendar);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Custom_Calendar> toCacheModel();

	@Override
	public Custom_Calendar toEscapedModel();

	@Override
	public Custom_Calendar toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}