/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the labDetailedCourseResources service. Represents a row in the &quot;collaborated_labDetailedCourseResources&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.labDetailedCourseResourcesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.labDetailedCourseResourcesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see labDetailedCourseResources
 * @see com.collaborated.entity.model.impl.labDetailedCourseResourcesImpl
 * @see com.collaborated.entity.model.impl.labDetailedCourseResourcesModelImpl
 * @generated
 */
@ProviderType
public interface labDetailedCourseResourcesModel extends BaseModel<labDetailedCourseResources> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lab detailed course resources model instance should use the {@link labDetailedCourseResources} interface instead.
	 */

	/**
	 * Returns the primary key of this lab detailed course resources.
	 *
	 * @return the primary key of this lab detailed course resources
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lab detailed course resources.
	 *
	 * @param primaryKey the primary key of this lab detailed course resources
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_course resource ID of this lab detailed course resources.
	 *
	 * @return the p k_course resource ID of this lab detailed course resources
	 */
	public long getPK_courseResourceId();

	/**
	 * Sets the p k_course resource ID of this lab detailed course resources.
	 *
	 * @param PK_courseResourceId the p k_course resource ID of this lab detailed course resources
	 */
	public void setPK_courseResourceId(long PK_courseResourceId);

	/**
	 * Returns the group ID of this lab detailed course resources.
	 *
	 * @return the group ID of this lab detailed course resources
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this lab detailed course resources.
	 *
	 * @param groupId the group ID of this lab detailed course resources
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this lab detailed course resources.
	 *
	 * @return the user ID of this lab detailed course resources
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this lab detailed course resources.
	 *
	 * @param userId the user ID of this lab detailed course resources
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lab detailed course resources.
	 *
	 * @return the user uuid of this lab detailed course resources
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lab detailed course resources.
	 *
	 * @param userUuid the user uuid of this lab detailed course resources
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this lab detailed course resources.
	 *
	 * @return the create date of this lab detailed course resources
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this lab detailed course resources.
	 *
	 * @param createDate the create date of this lab detailed course resources
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lab detailed course resources.
	 *
	 * @return the modified date of this lab detailed course resources
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lab detailed course resources.
	 *
	 * @param modifiedDate the modified date of this lab detailed course resources
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the p k_project ID of this lab detailed course resources.
	 *
	 * @return the p k_project ID of this lab detailed course resources
	 */
	public long getPK_projectId();

	/**
	 * Sets the p k_project ID of this lab detailed course resources.
	 *
	 * @param PK_projectId the p k_project ID of this lab detailed course resources
	 */
	public void setPK_projectId(long PK_projectId);

	/**
	 * Returns the p k_course ID of this lab detailed course resources.
	 *
	 * @return the p k_course ID of this lab detailed course resources
	 */
	public long getPK_courseId();

	/**
	 * Sets the p k_course ID of this lab detailed course resources.
	 *
	 * @param PK_courseId the p k_course ID of this lab detailed course resources
	 */
	public void setPK_courseId(long PK_courseId);

	/**
	 * Returns the textbok title of this lab detailed course resources.
	 *
	 * @return the textbok title of this lab detailed course resources
	 */
	@AutoEscape
	public String getTextbokTitle();

	/**
	 * Sets the textbok title of this lab detailed course resources.
	 *
	 * @param textbokTitle the textbok title of this lab detailed course resources
	 */
	public void setTextbokTitle(String textbokTitle);

	/**
	 * Returns the publisher name of this lab detailed course resources.
	 *
	 * @return the publisher name of this lab detailed course resources
	 */
	@AutoEscape
	public String getPublisherName();

	/**
	 * Sets the publisher name of this lab detailed course resources.
	 *
	 * @param publisherName the publisher name of this lab detailed course resources
	 */
	public void setPublisherName(String publisherName);

	/**
	 * Returns the author of this lab detailed course resources.
	 *
	 * @return the author of this lab detailed course resources
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this lab detailed course resources.
	 *
	 * @param author the author of this lab detailed course resources
	 */
	public void setAuthor(String author);

	/**
	 * Returns the isbn of this lab detailed course resources.
	 *
	 * @return the isbn of this lab detailed course resources
	 */
	@AutoEscape
	public String getIsbn();

	/**
	 * Sets the isbn of this lab detailed course resources.
	 *
	 * @param isbn the isbn of this lab detailed course resources
	 */
	public void setIsbn(String isbn);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.labDetailedCourseResources labDetailedCourseResources);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.labDetailedCourseResources> toCacheModel();

	@Override
	public com.collaborated.entity.model.labDetailedCourseResources toEscapedModel();

	@Override
	public com.collaborated.entity.model.labDetailedCourseResources toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}