/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the labDetailedCourseHours service. Represents a row in the &quot;collaborated_labDetailedCourseHours&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.labDetailedCourseHoursModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.labDetailedCourseHoursImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see labDetailedCourseHours
 * @see com.collaborated.entity.model.impl.labDetailedCourseHoursImpl
 * @see com.collaborated.entity.model.impl.labDetailedCourseHoursModelImpl
 * @generated
 */
@ProviderType
public interface labDetailedCourseHoursModel extends BaseModel<labDetailedCourseHours> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lab detailed course hours model instance should use the {@link labDetailedCourseHours} interface instead.
	 */

	/**
	 * Returns the primary key of this lab detailed course hours.
	 *
	 * @return the primary key of this lab detailed course hours
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lab detailed course hours.
	 *
	 * @param primaryKey the primary key of this lab detailed course hours
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_course hours ID of this lab detailed course hours.
	 *
	 * @return the p k_course hours ID of this lab detailed course hours
	 */
	public long getPK_courseHoursId();

	/**
	 * Sets the p k_course hours ID of this lab detailed course hours.
	 *
	 * @param PK_courseHoursId the p k_course hours ID of this lab detailed course hours
	 */
	public void setPK_courseHoursId(long PK_courseHoursId);

	/**
	 * Returns the group ID of this lab detailed course hours.
	 *
	 * @return the group ID of this lab detailed course hours
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this lab detailed course hours.
	 *
	 * @param groupId the group ID of this lab detailed course hours
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this lab detailed course hours.
	 *
	 * @return the user ID of this lab detailed course hours
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this lab detailed course hours.
	 *
	 * @param userId the user ID of this lab detailed course hours
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lab detailed course hours.
	 *
	 * @return the user uuid of this lab detailed course hours
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lab detailed course hours.
	 *
	 * @param userUuid the user uuid of this lab detailed course hours
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this lab detailed course hours.
	 *
	 * @return the create date of this lab detailed course hours
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this lab detailed course hours.
	 *
	 * @param createDate the create date of this lab detailed course hours
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lab detailed course hours.
	 *
	 * @return the modified date of this lab detailed course hours
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lab detailed course hours.
	 *
	 * @param modifiedDate the modified date of this lab detailed course hours
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the p k_project ID of this lab detailed course hours.
	 *
	 * @return the p k_project ID of this lab detailed course hours
	 */
	public long getPK_projectId();

	/**
	 * Sets the p k_project ID of this lab detailed course hours.
	 *
	 * @param PK_projectId the p k_project ID of this lab detailed course hours
	 */
	public void setPK_projectId(long PK_projectId);

	/**
	 * Returns the p k_course ID of this lab detailed course hours.
	 *
	 * @return the p k_course ID of this lab detailed course hours
	 */
	public long getPK_courseId();

	/**
	 * Sets the p k_course ID of this lab detailed course hours.
	 *
	 * @param PK_courseId the p k_course ID of this lab detailed course hours
	 */
	public void setPK_courseId(long PK_courseId);

	/**
	 * Returns the number of credits of this lab detailed course hours.
	 *
	 * @return the number of credits of this lab detailed course hours
	 */
	public long getNumberOfCredits();

	/**
	 * Sets the number of credits of this lab detailed course hours.
	 *
	 * @param numberOfCredits the number of credits of this lab detailed course hours
	 */
	public void setNumberOfCredits(long numberOfCredits);

	/**
	 * Returns the number of course weeks of this lab detailed course hours.
	 *
	 * @return the number of course weeks of this lab detailed course hours
	 */
	public long getNumberOfCourseWeeks();

	/**
	 * Sets the number of course weeks of this lab detailed course hours.
	 *
	 * @param numberOfCourseWeeks the number of course weeks of this lab detailed course hours
	 */
	public void setNumberOfCourseWeeks(long numberOfCourseWeeks);

	/**
	 * Returns the course hours per week of this lab detailed course hours.
	 *
	 * @return the course hours per week of this lab detailed course hours
	 */
	public long getCourseHoursPerWeek();

	/**
	 * Sets the course hours per week of this lab detailed course hours.
	 *
	 * @param courseHoursPerWeek the course hours per week of this lab detailed course hours
	 */
	public void setCourseHoursPerWeek(long courseHoursPerWeek);

	/**
	 * Returns the lecture hours per week of this lab detailed course hours.
	 *
	 * @return the lecture hours per week of this lab detailed course hours
	 */
	public long getLectureHoursPerWeek();

	/**
	 * Sets the lecture hours per week of this lab detailed course hours.
	 *
	 * @param lectureHoursPerWeek the lecture hours per week of this lab detailed course hours
	 */
	public void setLectureHoursPerWeek(long lectureHoursPerWeek);

	/**
	 * Returns the lab hours per week of this lab detailed course hours.
	 *
	 * @return the lab hours per week of this lab detailed course hours
	 */
	public long getLabHoursPerWeek();

	/**
	 * Sets the lab hours per week of this lab detailed course hours.
	 *
	 * @param labHoursPerWeek the lab hours per week of this lab detailed course hours
	 */
	public void setLabHoursPerWeek(long labHoursPerWeek);

	/**
	 * Returns the independent study hours per week of this lab detailed course hours.
	 *
	 * @return the independent study hours per week of this lab detailed course hours
	 */
	public long getIndependentStudyHoursPerWeek();

	/**
	 * Sets the independent study hours per week of this lab detailed course hours.
	 *
	 * @param independentStudyHoursPerWeek the independent study hours per week of this lab detailed course hours
	 */
	public void setIndependentStudyHoursPerWeek(
		long independentStudyHoursPerWeek);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.labDetailedCourseHours labDetailedCourseHours);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.labDetailedCourseHours> toCacheModel();

	@Override
	public com.collaborated.entity.model.labDetailedCourseHours toEscapedModel();

	@Override
	public com.collaborated.entity.model.labDetailedCourseHours toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}