/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the labDetailedCourseIdentification service. Represents a row in the &quot;collaborated_labDetailedCourseIdentification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.labDetailedCourseIdentificationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.labDetailedCourseIdentificationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see labDetailedCourseIdentification
 * @see com.collaborated.entity.model.impl.labDetailedCourseIdentificationImpl
 * @see com.collaborated.entity.model.impl.labDetailedCourseIdentificationModelImpl
 * @generated
 */
@ProviderType
public interface labDetailedCourseIdentificationModel extends BaseModel<labDetailedCourseIdentification> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lab detailed course identification model instance should use the {@link labDetailedCourseIdentification} interface instead.
	 */

	/**
	 * Returns the primary key of this lab detailed course identification.
	 *
	 * @return the primary key of this lab detailed course identification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lab detailed course identification.
	 *
	 * @param primaryKey the primary key of this lab detailed course identification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_course ID of this lab detailed course identification.
	 *
	 * @return the p k_course ID of this lab detailed course identification
	 */
	public long getPK_courseId();

	/**
	 * Sets the p k_course ID of this lab detailed course identification.
	 *
	 * @param PK_courseId the p k_course ID of this lab detailed course identification
	 */
	public void setPK_courseId(long PK_courseId);

	/**
	 * Returns the group ID of this lab detailed course identification.
	 *
	 * @return the group ID of this lab detailed course identification
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this lab detailed course identification.
	 *
	 * @param groupId the group ID of this lab detailed course identification
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this lab detailed course identification.
	 *
	 * @return the user ID of this lab detailed course identification
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this lab detailed course identification.
	 *
	 * @param userId the user ID of this lab detailed course identification
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lab detailed course identification.
	 *
	 * @return the user uuid of this lab detailed course identification
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lab detailed course identification.
	 *
	 * @param userUuid the user uuid of this lab detailed course identification
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this lab detailed course identification.
	 *
	 * @return the create date of this lab detailed course identification
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this lab detailed course identification.
	 *
	 * @param createDate the create date of this lab detailed course identification
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lab detailed course identification.
	 *
	 * @return the modified date of this lab detailed course identification
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lab detailed course identification.
	 *
	 * @param modifiedDate the modified date of this lab detailed course identification
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the p k_project ID of this lab detailed course identification.
	 *
	 * @return the p k_project ID of this lab detailed course identification
	 */
	public long getPK_projectId();

	/**
	 * Sets the p k_project ID of this lab detailed course identification.
	 *
	 * @param PK_projectId the p k_project ID of this lab detailed course identification
	 */
	public void setPK_projectId(long PK_projectId);

	/**
	 * Returns the course title of this lab detailed course identification.
	 *
	 * @return the course title of this lab detailed course identification
	 */
	@AutoEscape
	public String getCourseTitle();

	/**
	 * Sets the course title of this lab detailed course identification.
	 *
	 * @param courseTitle the course title of this lab detailed course identification
	 */
	public void setCourseTitle(String courseTitle);

	/**
	 * Returns the course number of this lab detailed course identification.
	 *
	 * @return the course number of this lab detailed course identification
	 */
	@AutoEscape
	public String getCourseNumber();

	/**
	 * Sets the course number of this lab detailed course identification.
	 *
	 * @param courseNumber the course number of this lab detailed course identification
	 */
	public void setCourseNumber(String courseNumber);

	/**
	 * Returns the prerequisites of this lab detailed course identification.
	 *
	 * @return the prerequisites of this lab detailed course identification
	 */
	@AutoEscape
	public String getPrerequisites();

	/**
	 * Sets the prerequisites of this lab detailed course identification.
	 *
	 * @param prerequisites the prerequisites of this lab detailed course identification
	 */
	public void setPrerequisites(String prerequisites);

	/**
	 * Returns the course description of this lab detailed course identification.
	 *
	 * @return the course description of this lab detailed course identification
	 */
	@AutoEscape
	public String getCourseDescription();

	/**
	 * Sets the course description of this lab detailed course identification.
	 *
	 * @param courseDescription the course description of this lab detailed course identification
	 */
	public void setCourseDescription(String courseDescription);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.labDetailedCourseIdentification labDetailedCourseIdentification);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.labDetailedCourseIdentification> toCacheModel();

	@Override
	public com.collaborated.entity.model.labDetailedCourseIdentification toEscapedModel();

	@Override
	public com.collaborated.entity.model.labDetailedCourseIdentification toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}