/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the labDetailedCourseTopics service. Represents a row in the &quot;collaborated_labDetailedCourseTopics&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.labDetailedCourseTopicsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.labDetailedCourseTopicsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see labDetailedCourseTopics
 * @see com.collaborated.entity.model.impl.labDetailedCourseTopicsImpl
 * @see com.collaborated.entity.model.impl.labDetailedCourseTopicsModelImpl
 * @generated
 */
@ProviderType
public interface labDetailedCourseTopicsModel extends BaseModel<labDetailedCourseTopics> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lab detailed course topics model instance should use the {@link labDetailedCourseTopics} interface instead.
	 */

	/**
	 * Returns the primary key of this lab detailed course topics.
	 *
	 * @return the primary key of this lab detailed course topics
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lab detailed course topics.
	 *
	 * @param primaryKey the primary key of this lab detailed course topics
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_course topics ID of this lab detailed course topics.
	 *
	 * @return the p k_course topics ID of this lab detailed course topics
	 */
	public long getPK_courseTopicsId();

	/**
	 * Sets the p k_course topics ID of this lab detailed course topics.
	 *
	 * @param PK_courseTopicsId the p k_course topics ID of this lab detailed course topics
	 */
	public void setPK_courseTopicsId(long PK_courseTopicsId);

	/**
	 * Returns the group ID of this lab detailed course topics.
	 *
	 * @return the group ID of this lab detailed course topics
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this lab detailed course topics.
	 *
	 * @param groupId the group ID of this lab detailed course topics
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this lab detailed course topics.
	 *
	 * @return the user ID of this lab detailed course topics
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this lab detailed course topics.
	 *
	 * @param userId the user ID of this lab detailed course topics
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lab detailed course topics.
	 *
	 * @return the user uuid of this lab detailed course topics
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lab detailed course topics.
	 *
	 * @param userUuid the user uuid of this lab detailed course topics
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this lab detailed course topics.
	 *
	 * @return the create date of this lab detailed course topics
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this lab detailed course topics.
	 *
	 * @param createDate the create date of this lab detailed course topics
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lab detailed course topics.
	 *
	 * @return the modified date of this lab detailed course topics
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lab detailed course topics.
	 *
	 * @param modifiedDate the modified date of this lab detailed course topics
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the p k_project ID of this lab detailed course topics.
	 *
	 * @return the p k_project ID of this lab detailed course topics
	 */
	public long getPK_projectId();

	/**
	 * Sets the p k_project ID of this lab detailed course topics.
	 *
	 * @param PK_projectId the p k_project ID of this lab detailed course topics
	 */
	public void setPK_projectId(long PK_projectId);

	/**
	 * Returns the p k_course ID of this lab detailed course topics.
	 *
	 * @return the p k_course ID of this lab detailed course topics
	 */
	public long getPK_courseId();

	/**
	 * Sets the p k_course ID of this lab detailed course topics.
	 *
	 * @param PK_courseId the p k_course ID of this lab detailed course topics
	 */
	public void setPK_courseId(long PK_courseId);

	/**
	 * Returns the course topic of this lab detailed course topics.
	 *
	 * @return the course topic of this lab detailed course topics
	 */
	@AutoEscape
	public String getCourseTopic();

	/**
	 * Sets the course topic of this lab detailed course topics.
	 *
	 * @param courseTopic the course topic of this lab detailed course topics
	 */
	public void setCourseTopic(String courseTopic);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.labDetailedCourseTopics labDetailedCourseTopics);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.labDetailedCourseTopics> toCacheModel();

	@Override
	public com.collaborated.entity.model.labDetailedCourseTopics toEscapedModel();

	@Override
	public com.collaborated.entity.model.labDetailedCourseTopics toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}