/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the labScreenProjectPartners service. Represents a row in the &quot;collaborated_labScreenProjectPartners&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.labScreenProjectPartnersModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.labScreenProjectPartnersImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see labScreenProjectPartners
 * @see com.collaborated.entity.model.impl.labScreenProjectPartnersImpl
 * @see com.collaborated.entity.model.impl.labScreenProjectPartnersModelImpl
 * @generated
 */
@ProviderType
public interface labScreenProjectPartnersModel extends BaseModel<labScreenProjectPartners> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lab screen project partners model instance should use the {@link labScreenProjectPartners} interface instead.
	 */

	/**
	 * Returns the primary key of this lab screen project partners.
	 *
	 * @return the primary key of this lab screen project partners
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lab screen project partners.
	 *
	 * @param primaryKey the primary key of this lab screen project partners
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_project partner ID of this lab screen project partners.
	 *
	 * @return the p k_project partner ID of this lab screen project partners
	 */
	public long getPK_projectPartnerId();

	/**
	 * Sets the p k_project partner ID of this lab screen project partners.
	 *
	 * @param PK_projectPartnerId the p k_project partner ID of this lab screen project partners
	 */
	public void setPK_projectPartnerId(long PK_projectPartnerId);

	/**
	 * Returns the group ID of this lab screen project partners.
	 *
	 * @return the group ID of this lab screen project partners
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this lab screen project partners.
	 *
	 * @param groupId the group ID of this lab screen project partners
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this lab screen project partners.
	 *
	 * @return the user ID of this lab screen project partners
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this lab screen project partners.
	 *
	 * @param userId the user ID of this lab screen project partners
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lab screen project partners.
	 *
	 * @return the user uuid of this lab screen project partners
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lab screen project partners.
	 *
	 * @param userUuid the user uuid of this lab screen project partners
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this lab screen project partners.
	 *
	 * @return the create date of this lab screen project partners
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this lab screen project partners.
	 *
	 * @param createDate the create date of this lab screen project partners
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lab screen project partners.
	 *
	 * @return the modified date of this lab screen project partners
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lab screen project partners.
	 *
	 * @param modifiedDate the modified date of this lab screen project partners
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the p k_project ID of this lab screen project partners.
	 *
	 * @return the p k_project ID of this lab screen project partners
	 */
	public long getPK_projectId();

	/**
	 * Sets the p k_project ID of this lab screen project partners.
	 *
	 * @param PK_projectId the p k_project ID of this lab screen project partners
	 */
	public void setPK_projectId(long PK_projectId);

	/**
	 * Returns the project partner ID of this lab screen project partners.
	 *
	 * @return the project partner ID of this lab screen project partners
	 */
	public long getProjectPartnerId();

	/**
	 * Sets the project partner ID of this lab screen project partners.
	 *
	 * @param projectPartnerId the project partner ID of this lab screen project partners
	 */
	public void setProjectPartnerId(long projectPartnerId);

	/**
	 * Returns the is active of this lab screen project partners.
	 *
	 * @return the is active of this lab screen project partners
	 */
	public long getIsActive();

	/**
	 * Sets the is active of this lab screen project partners.
	 *
	 * @param isActive the is active of this lab screen project partners
	 */
	public void setIsActive(long isActive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.labScreenProjectPartners labScreenProjectPartners);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.labScreenProjectPartners> toCacheModel();

	@Override
	public com.collaborated.entity.model.labScreenProjectPartners toEscapedModel();

	@Override
	public com.collaborated.entity.model.labScreenProjectPartners toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}