/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the labScreenProjectOverview service. Represents a row in the &quot;collaborated_labScreenProjectOverview&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.labScreenProjectOverviewModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.labScreenProjectOverviewImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see labScreenProjectOverview
 * @see com.collaborated.entity.model.impl.labScreenProjectOverviewImpl
 * @see com.collaborated.entity.model.impl.labScreenProjectOverviewModelImpl
 * @generated
 */
@ProviderType
public interface labScreenProjectOverviewModel extends BaseModel<labScreenProjectOverview> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lab screen project overview model instance should use the {@link labScreenProjectOverview} interface instead.
	 */

	/**
	 * Returns the primary key of this lab screen project overview.
	 *
	 * @return the primary key of this lab screen project overview
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lab screen project overview.
	 *
	 * @param primaryKey the primary key of this lab screen project overview
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_project ID of this lab screen project overview.
	 *
	 * @return the p k_project ID of this lab screen project overview
	 */
	public long getPK_projectId();

	/**
	 * Sets the p k_project ID of this lab screen project overview.
	 *
	 * @param PK_projectId the p k_project ID of this lab screen project overview
	 */
	public void setPK_projectId(long PK_projectId);

	/**
	 * Returns the group ID of this lab screen project overview.
	 *
	 * @return the group ID of this lab screen project overview
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this lab screen project overview.
	 *
	 * @param groupId the group ID of this lab screen project overview
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this lab screen project overview.
	 *
	 * @return the user ID of this lab screen project overview
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this lab screen project overview.
	 *
	 * @param userId the user ID of this lab screen project overview
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lab screen project overview.
	 *
	 * @return the user uuid of this lab screen project overview
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lab screen project overview.
	 *
	 * @param userUuid the user uuid of this lab screen project overview
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this lab screen project overview.
	 *
	 * @return the create date of this lab screen project overview
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this lab screen project overview.
	 *
	 * @param createDate the create date of this lab screen project overview
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lab screen project overview.
	 *
	 * @return the modified date of this lab screen project overview
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lab screen project overview.
	 *
	 * @param modifiedDate the modified date of this lab screen project overview
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the project owner ID of this lab screen project overview.
	 *
	 * @return the project owner ID of this lab screen project overview
	 */
	public long getProjectOwnerId();

	/**
	 * Sets the project owner ID of this lab screen project overview.
	 *
	 * @param projectOwnerId the project owner ID of this lab screen project overview
	 */
	public void setProjectOwnerId(long projectOwnerId);

	/**
	 * Returns the project name of this lab screen project overview.
	 *
	 * @return the project name of this lab screen project overview
	 */
	@AutoEscape
	public String getProjectName();

	/**
	 * Sets the project name of this lab screen project overview.
	 *
	 * @param projectName the project name of this lab screen project overview
	 */
	public void setProjectName(String projectName);

	/**
	 * Returns the project type of this lab screen project overview.
	 *
	 * @return the project type of this lab screen project overview
	 */
	@AutoEscape
	public String getProjectType();

	/**
	 * Sets the project type of this lab screen project overview.
	 *
	 * @param projectType the project type of this lab screen project overview
	 */
	public void setProjectType(String projectType);

	/**
	 * Returns the project description of this lab screen project overview.
	 *
	 * @return the project description of this lab screen project overview
	 */
	@AutoEscape
	public String getProjectDescription();

	/**
	 * Sets the project description of this lab screen project overview.
	 *
	 * @param projectDescription the project description of this lab screen project overview
	 */
	public void setProjectDescription(String projectDescription);

	/**
	 * Returns the project discipline1 of this lab screen project overview.
	 *
	 * @return the project discipline1 of this lab screen project overview
	 */
	@AutoEscape
	public String getProjectDiscipline1();

	/**
	 * Sets the project discipline1 of this lab screen project overview.
	 *
	 * @param projectDiscipline1 the project discipline1 of this lab screen project overview
	 */
	public void setProjectDiscipline1(String projectDiscipline1);

	/**
	 * Returns the project discipline2 of this lab screen project overview.
	 *
	 * @return the project discipline2 of this lab screen project overview
	 */
	@AutoEscape
	public String getProjectDiscipline2();

	/**
	 * Sets the project discipline2 of this lab screen project overview.
	 *
	 * @param projectDiscipline2 the project discipline2 of this lab screen project overview
	 */
	public void setProjectDiscipline2(String projectDiscipline2);

	/**
	 * Returns the project discipline3 of this lab screen project overview.
	 *
	 * @return the project discipline3 of this lab screen project overview
	 */
	@AutoEscape
	public String getProjectDiscipline3();

	/**
	 * Sets the project discipline3 of this lab screen project overview.
	 *
	 * @param projectDiscipline3 the project discipline3 of this lab screen project overview
	 */
	public void setProjectDiscipline3(String projectDiscipline3);

	/**
	 * Returns the role of this lab screen project overview.
	 *
	 * @return the role of this lab screen project overview
	 */
	@AutoEscape
	public String getRole();

	/**
	 * Sets the role of this lab screen project overview.
	 *
	 * @param role the role of this lab screen project overview
	 */
	public void setRole(String role);

	/**
	 * Returns the project start date of this lab screen project overview.
	 *
	 * @return the project start date of this lab screen project overview
	 */
	@AutoEscape
	public String getProjectStartDate();

	/**
	 * Sets the project start date of this lab screen project overview.
	 *
	 * @param projectStartDate the project start date of this lab screen project overview
	 */
	public void setProjectStartDate(String projectStartDate);

	/**
	 * Returns the project end date of this lab screen project overview.
	 *
	 * @return the project end date of this lab screen project overview
	 */
	@AutoEscape
	public String getProjectEndDate();

	/**
	 * Sets the project end date of this lab screen project overview.
	 *
	 * @param projectEndDate the project end date of this lab screen project overview
	 */
	public void setProjectEndDate(String projectEndDate);

	/**
	 * Returns the project document ID of this lab screen project overview.
	 *
	 * @return the project document ID of this lab screen project overview
	 */
	public long getProjectDocumentId();

	/**
	 * Sets the project document ID of this lab screen project overview.
	 *
	 * @param projectDocumentId the project document ID of this lab screen project overview
	 */
	public void setProjectDocumentId(long projectDocumentId);

	/**
	 * Returns the percentage of this lab screen project overview.
	 *
	 * @return the percentage of this lab screen project overview
	 */
	public long getPercentage();

	/**
	 * Sets the percentage of this lab screen project overview.
	 *
	 * @param percentage the percentage of this lab screen project overview
	 */
	public void setPercentage(long percentage);

	/**
	 * Returns the interest ID of this lab screen project overview.
	 *
	 * @return the interest ID of this lab screen project overview
	 */
	public long getInterestId();

	/**
	 * Sets the interest ID of this lab screen project overview.
	 *
	 * @param interestId the interest ID of this lab screen project overview
	 */
	public void setInterestId(long interestId);

	/**
	 * Returns the project status of this lab screen project overview.
	 *
	 * @return the project status of this lab screen project overview
	 */
	@AutoEscape
	public String getProjectStatus();

	/**
	 * Sets the project status of this lab screen project overview.
	 *
	 * @param projectStatus the project status of this lab screen project overview
	 */
	public void setProjectStatus(String projectStatus);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.labScreenProjectOverview labScreenProjectOverview);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.labScreenProjectOverview> toCacheModel();

	@Override
	public com.collaborated.entity.model.labScreenProjectOverview toEscapedModel();

	@Override
	public com.collaborated.entity.model.labScreenProjectOverview toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}