/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the labScreenTask service. Represents a row in the &quot;collaborated_labScreenTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.labScreenTaskModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.labScreenTaskImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see labScreenTask
 * @see com.collaborated.entity.model.impl.labScreenTaskImpl
 * @see com.collaborated.entity.model.impl.labScreenTaskModelImpl
 * @generated
 */
@ProviderType
public interface labScreenTaskModel extends BaseModel<labScreenTask> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lab screen task model instance should use the {@link labScreenTask} interface instead.
	 */

	/**
	 * Returns the primary key of this lab screen task.
	 *
	 * @return the primary key of this lab screen task
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lab screen task.
	 *
	 * @param primaryKey the primary key of this lab screen task
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_task ID of this lab screen task.
	 *
	 * @return the p k_task ID of this lab screen task
	 */
	public long getPK_taskId();

	/**
	 * Sets the p k_task ID of this lab screen task.
	 *
	 * @param PK_taskId the p k_task ID of this lab screen task
	 */
	public void setPK_taskId(long PK_taskId);

	/**
	 * Returns the group ID of this lab screen task.
	 *
	 * @return the group ID of this lab screen task
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this lab screen task.
	 *
	 * @param groupId the group ID of this lab screen task
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this lab screen task.
	 *
	 * @return the user ID of this lab screen task
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this lab screen task.
	 *
	 * @param userId the user ID of this lab screen task
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lab screen task.
	 *
	 * @return the user uuid of this lab screen task
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lab screen task.
	 *
	 * @param userUuid the user uuid of this lab screen task
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this lab screen task.
	 *
	 * @return the create date of this lab screen task
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this lab screen task.
	 *
	 * @param createDate the create date of this lab screen task
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lab screen task.
	 *
	 * @return the modified date of this lab screen task
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lab screen task.
	 *
	 * @param modifiedDate the modified date of this lab screen task
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the p k_project ID of this lab screen task.
	 *
	 * @return the p k_project ID of this lab screen task
	 */
	public long getPK_projectId();

	/**
	 * Sets the p k_project ID of this lab screen task.
	 *
	 * @param PK_projectId the p k_project ID of this lab screen task
	 */
	public void setPK_projectId(long PK_projectId);

	/**
	 * Returns the milestone name of this lab screen task.
	 *
	 * @return the milestone name of this lab screen task
	 */
	@AutoEscape
	public String getMilestoneName();

	/**
	 * Sets the milestone name of this lab screen task.
	 *
	 * @param milestoneName the milestone name of this lab screen task
	 */
	public void setMilestoneName(String milestoneName);

	/**
	 * Returns the task name of this lab screen task.
	 *
	 * @return the task name of this lab screen task
	 */
	@AutoEscape
	public String getTaskName();

	/**
	 * Sets the task name of this lab screen task.
	 *
	 * @param taskName the task name of this lab screen task
	 */
	public void setTaskName(String taskName);

	/**
	 * Returns the project assigned to of this lab screen task.
	 *
	 * @return the project assigned to of this lab screen task
	 */
	public long getProjectAssignedTo();

	/**
	 * Sets the project assigned to of this lab screen task.
	 *
	 * @param projectAssignedTo the project assigned to of this lab screen task
	 */
	public void setProjectAssignedTo(long projectAssignedTo);

	/**
	 * Returns the task description of this lab screen task.
	 *
	 * @return the task description of this lab screen task
	 */
	@AutoEscape
	public String getTaskDescription();

	/**
	 * Sets the task description of this lab screen task.
	 *
	 * @param taskDescription the task description of this lab screen task
	 */
	public void setTaskDescription(String taskDescription);

	/**
	 * Returns the task status of this lab screen task.
	 *
	 * @return the task status of this lab screen task
	 */
	@AutoEscape
	public String getTaskStatus();

	/**
	 * Sets the task status of this lab screen task.
	 *
	 * @param taskStatus the task status of this lab screen task
	 */
	public void setTaskStatus(String taskStatus);

	/**
	 * Returns the due date of this lab screen task.
	 *
	 * @return the due date of this lab screen task
	 */
	@AutoEscape
	public String getDueDate();

	/**
	 * Sets the due date of this lab screen task.
	 *
	 * @param dueDate the due date of this lab screen task
	 */
	public void setDueDate(String dueDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.labScreenTask labScreenTask);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.labScreenTask> toCacheModel();

	@Override
	public com.collaborated.entity.model.labScreenTask toEscapedModel();

	@Override
	public com.collaborated.entity.model.labScreenTask toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}