/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the languagePreferences service. Represents a row in the &quot;collaborated_languagePreferences&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.languagePreferencesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.languagePreferencesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see languagePreferences
 * @see com.collaborated.entity.model.impl.languagePreferencesImpl
 * @see com.collaborated.entity.model.impl.languagePreferencesModelImpl
 * @generated
 */
@ProviderType
public interface languagePreferencesModel extends BaseModel<languagePreferences> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a language preferences model instance should use the {@link languagePreferences} interface instead.
	 */

	/**
	 * Returns the primary key of this language preferences.
	 *
	 * @return the primary key of this language preferences
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this language preferences.
	 *
	 * @param primaryKey the primary key of this language preferences
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_language preferences of this language preferences.
	 *
	 * @return the p k_language preferences of this language preferences
	 */
	public long getPK_languagePreferences();

	/**
	 * Sets the p k_language preferences of this language preferences.
	 *
	 * @param PK_languagePreferences the p k_language preferences of this language preferences
	 */
	public void setPK_languagePreferences(long PK_languagePreferences);

	/**
	 * Returns the user ID of this language preferences.
	 *
	 * @return the user ID of this language preferences
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this language preferences.
	 *
	 * @param userId the user ID of this language preferences
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this language preferences.
	 *
	 * @return the user uuid of this language preferences
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this language preferences.
	 *
	 * @param userUuid the user uuid of this language preferences
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this language preferences.
	 *
	 * @return the create date of this language preferences
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this language preferences.
	 *
	 * @param createDate the create date of this language preferences
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this language preferences.
	 *
	 * @return the modified date of this language preferences
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this language preferences.
	 *
	 * @param modifiedDate the modified date of this language preferences
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the language name of this language preferences.
	 *
	 * @return the language name of this language preferences
	 */
	@AutoEscape
	public String getLanguageName();

	/**
	 * Sets the language name of this language preferences.
	 *
	 * @param languageName the language name of this language preferences
	 */
	public void setLanguageName(String languageName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.languagePreferences languagePreferences);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.languagePreferences> toCacheModel();

	@Override
	public com.collaborated.entity.model.languagePreferences toEscapedModel();

	@Override
	public com.collaborated.entity.model.languagePreferences toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}