/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the profileAreaofinterest service. Represents a row in the &quot;collaborated_profileAreaofinterest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.profileAreaofinterestModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.profileAreaofinterestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see profileAreaofinterest
 * @see com.collaborated.entity.model.impl.profileAreaofinterestImpl
 * @see com.collaborated.entity.model.impl.profileAreaofinterestModelImpl
 * @generated
 */
@ProviderType
public interface profileAreaofinterestModel extends BaseModel<profileAreaofinterest> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a profile areaofinterest model instance should use the {@link profileAreaofinterest} interface instead.
	 */

	/**
	 * Returns the primary key of this profile areaofinterest.
	 *
	 * @return the primary key of this profile areaofinterest
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this profile areaofinterest.
	 *
	 * @param primaryKey the primary key of this profile areaofinterest
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_areaofinterest of this profile areaofinterest.
	 *
	 * @return the p k_areaofinterest of this profile areaofinterest
	 */
	public long getPK_areaofinterest();

	/**
	 * Sets the p k_areaofinterest of this profile areaofinterest.
	 *
	 * @param PK_areaofinterest the p k_areaofinterest of this profile areaofinterest
	 */
	public void setPK_areaofinterest(long PK_areaofinterest);

	/**
	 * Returns the group ID of this profile areaofinterest.
	 *
	 * @return the group ID of this profile areaofinterest
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this profile areaofinterest.
	 *
	 * @param groupId the group ID of this profile areaofinterest
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this profile areaofinterest.
	 *
	 * @return the user ID of this profile areaofinterest
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this profile areaofinterest.
	 *
	 * @param userId the user ID of this profile areaofinterest
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this profile areaofinterest.
	 *
	 * @return the user uuid of this profile areaofinterest
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this profile areaofinterest.
	 *
	 * @param userUuid the user uuid of this profile areaofinterest
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this profile areaofinterest.
	 *
	 * @return the create date of this profile areaofinterest
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this profile areaofinterest.
	 *
	 * @param createDate the create date of this profile areaofinterest
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this profile areaofinterest.
	 *
	 * @return the modified date of this profile areaofinterest
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this profile areaofinterest.
	 *
	 * @param modifiedDate the modified date of this profile areaofinterest
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the project type of this profile areaofinterest.
	 *
	 * @return the project type of this profile areaofinterest
	 */
	@AutoEscape
	public String getProjectType();

	/**
	 * Sets the project type of this profile areaofinterest.
	 *
	 * @param projectType the project type of this profile areaofinterest
	 */
	public void setProjectType(String projectType);

	/**
	 * Returns the description of this profile areaofinterest.
	 *
	 * @return the description of this profile areaofinterest
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this profile areaofinterest.
	 *
	 * @param description the description of this profile areaofinterest
	 */
	public void setDescription(String description);

	/**
	 * Returns the language of this profile areaofinterest.
	 *
	 * @return the language of this profile areaofinterest
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this profile areaofinterest.
	 *
	 * @param language the language of this profile areaofinterest
	 */
	public void setLanguage(String language);

	/**
	 * Returns the campus of this profile areaofinterest.
	 *
	 * @return the campus of this profile areaofinterest
	 */
	@AutoEscape
	public String getCampus();

	/**
	 * Sets the campus of this profile areaofinterest.
	 *
	 * @param campus the campus of this profile areaofinterest
	 */
	public void setCampus(String campus);

	/**
	 * Returns the program level of this profile areaofinterest.
	 *
	 * @return the program level of this profile areaofinterest
	 */
	@AutoEscape
	public String getProgramLevel();

	/**
	 * Sets the program level of this profile areaofinterest.
	 *
	 * @param programLevel the program level of this profile areaofinterest
	 */
	public void setProgramLevel(String programLevel);

	/**
	 * Returns the program length of this profile areaofinterest.
	 *
	 * @return the program length of this profile areaofinterest
	 */
	@AutoEscape
	public String getProgramLength();

	/**
	 * Sets the program length of this profile areaofinterest.
	 *
	 * @param programLength the program length of this profile areaofinterest
	 */
	public void setProgramLength(String programLength);

	/**
	 * Returns the delivery method of this profile areaofinterest.
	 *
	 * @return the delivery method of this profile areaofinterest
	 */
	@AutoEscape
	public String getDeliveryMethod();

	/**
	 * Sets the delivery method of this profile areaofinterest.
	 *
	 * @param deliveryMethod the delivery method of this profile areaofinterest
	 */
	public void setDeliveryMethod(String deliveryMethod);

	/**
	 * Returns the credits of this profile areaofinterest.
	 *
	 * @return the credits of this profile areaofinterest
	 */
	@AutoEscape
	public String getCredits();

	/**
	 * Sets the credits of this profile areaofinterest.
	 *
	 * @param credits the credits of this profile areaofinterest
	 */
	public void setCredits(String credits);

	/**
	 * Returns the collaboration type of this profile areaofinterest.
	 *
	 * @return the collaboration type of this profile areaofinterest
	 */
	@AutoEscape
	public String getCollaborationType();

	/**
	 * Sets the collaboration type of this profile areaofinterest.
	 *
	 * @param collaborationType the collaboration type of this profile areaofinterest
	 */
	public void setCollaborationType(String collaborationType);

	/**
	 * Returns the discipline1 of this profile areaofinterest.
	 *
	 * @return the discipline1 of this profile areaofinterest
	 */
	@AutoEscape
	public String getDiscipline1();

	/**
	 * Sets the discipline1 of this profile areaofinterest.
	 *
	 * @param discipline1 the discipline1 of this profile areaofinterest
	 */
	public void setDiscipline1(String discipline1);

	/**
	 * Returns the discipline2 of this profile areaofinterest.
	 *
	 * @return the discipline2 of this profile areaofinterest
	 */
	@AutoEscape
	public String getDiscipline2();

	/**
	 * Sets the discipline2 of this profile areaofinterest.
	 *
	 * @param discipline2 the discipline2 of this profile areaofinterest
	 */
	public void setDiscipline2(String discipline2);

	/**
	 * Returns the discipline3 of this profile areaofinterest.
	 *
	 * @return the discipline3 of this profile areaofinterest
	 */
	@AutoEscape
	public String getDiscipline3();

	/**
	 * Sets the discipline3 of this profile areaofinterest.
	 *
	 * @param discipline3 the discipline3 of this profile areaofinterest
	 */
	public void setDiscipline3(String discipline3);

	/**
	 * Returns the location1 of this profile areaofinterest.
	 *
	 * @return the location1 of this profile areaofinterest
	 */
	@AutoEscape
	public String getLocation1();

	/**
	 * Sets the location1 of this profile areaofinterest.
	 *
	 * @param location1 the location1 of this profile areaofinterest
	 */
	public void setLocation1(String location1);

	/**
	 * Returns the location2 of this profile areaofinterest.
	 *
	 * @return the location2 of this profile areaofinterest
	 */
	@AutoEscape
	public String getLocation2();

	/**
	 * Sets the location2 of this profile areaofinterest.
	 *
	 * @param location2 the location2 of this profile areaofinterest
	 */
	public void setLocation2(String location2);

	/**
	 * Returns the location3 of this profile areaofinterest.
	 *
	 * @return the location3 of this profile areaofinterest
	 */
	@AutoEscape
	public String getLocation3();

	/**
	 * Sets the location3 of this profile areaofinterest.
	 *
	 * @param location3 the location3 of this profile areaofinterest
	 */
	public void setLocation3(String location3);

	/**
	 * Returns the location4 of this profile areaofinterest.
	 *
	 * @return the location4 of this profile areaofinterest
	 */
	@AutoEscape
	public String getLocation4();

	/**
	 * Sets the location4 of this profile areaofinterest.
	 *
	 * @param location4 the location4 of this profile areaofinterest
	 */
	public void setLocation4(String location4);

	/**
	 * Returns the ranger year start of this profile areaofinterest.
	 *
	 * @return the ranger year start of this profile areaofinterest
	 */
	public int getRangerYearStart();

	/**
	 * Sets the ranger year start of this profile areaofinterest.
	 *
	 * @param rangerYearStart the ranger year start of this profile areaofinterest
	 */
	public void setRangerYearStart(int rangerYearStart);

	/**
	 * Returns the ranger year end of this profile areaofinterest.
	 *
	 * @return the ranger year end of this profile areaofinterest
	 */
	public int getRangerYearEnd();

	/**
	 * Sets the ranger year end of this profile areaofinterest.
	 *
	 * @param rangerYearEnd the ranger year end of this profile areaofinterest
	 */
	public void setRangerYearEnd(int rangerYearEnd);

	/**
	 * Returns the ranger month start of this profile areaofinterest.
	 *
	 * @return the ranger month start of this profile areaofinterest
	 */
	@AutoEscape
	public String getRangerMonthStart();

	/**
	 * Sets the ranger month start of this profile areaofinterest.
	 *
	 * @param rangerMonthStart the ranger month start of this profile areaofinterest
	 */
	public void setRangerMonthStart(String rangerMonthStart);

	/**
	 * Returns the ranger month end of this profile areaofinterest.
	 *
	 * @return the ranger month end of this profile areaofinterest
	 */
	@AutoEscape
	public String getRangerMonthEnd();

	/**
	 * Sets the ranger month end of this profile areaofinterest.
	 *
	 * @param rangerMonthEnd the ranger month end of this profile areaofinterest
	 */
	public void setRangerMonthEnd(String rangerMonthEnd);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.profileAreaofinterest profileAreaofinterest);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.profileAreaofinterest> toCacheModel();

	@Override
	public com.collaborated.entity.model.profileAreaofinterest toEscapedModel();

	@Override
	public com.collaborated.entity.model.profileAreaofinterest toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}