/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the projectFolderUpload service. Represents a row in the &quot;collaborated_projectFolderUpload&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.projectFolderUploadModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.projectFolderUploadImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see projectFolderUpload
 * @see com.collaborated.entity.model.impl.projectFolderUploadImpl
 * @see com.collaborated.entity.model.impl.projectFolderUploadModelImpl
 * @generated
 */
@ProviderType
public interface projectFolderUploadModel extends BaseModel<projectFolderUpload> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project folder upload model instance should use the {@link projectFolderUpload} interface instead.
	 */

	/**
	 * Returns the primary key of this project folder upload.
	 *
	 * @return the primary key of this project folder upload
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project folder upload.
	 *
	 * @param primaryKey the primary key of this project folder upload
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_project folder ID of this project folder upload.
	 *
	 * @return the p k_project folder ID of this project folder upload
	 */
	public long getPK_projectFolderId();

	/**
	 * Sets the p k_project folder ID of this project folder upload.
	 *
	 * @param PK_projectFolderId the p k_project folder ID of this project folder upload
	 */
	public void setPK_projectFolderId(long PK_projectFolderId);

	/**
	 * Returns the group ID of this project folder upload.
	 *
	 * @return the group ID of this project folder upload
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this project folder upload.
	 *
	 * @param groupId the group ID of this project folder upload
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the created on of this project folder upload.
	 *
	 * @return the created on of this project folder upload
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this project folder upload.
	 *
	 * @param createdOn the created on of this project folder upload
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the deleted on of this project folder upload.
	 *
	 * @return the deleted on of this project folder upload
	 */
	public Date getDeletedOn();

	/**
	 * Sets the deleted on of this project folder upload.
	 *
	 * @param deletedOn the deleted on of this project folder upload
	 */
	public void setDeletedOn(Date deletedOn);

	/**
	 * Returns the interest ID of this project folder upload.
	 *
	 * @return the interest ID of this project folder upload
	 */
	public long getInterestId();

	/**
	 * Sets the interest ID of this project folder upload.
	 *
	 * @param interestId the interest ID of this project folder upload
	 */
	public void setInterestId(long interestId);

	/**
	 * Returns the project ID of this project folder upload.
	 *
	 * @return the project ID of this project folder upload
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this project folder upload.
	 *
	 * @param projectId the project ID of this project folder upload
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the user ID of this project folder upload.
	 *
	 * @return the user ID of this project folder upload
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this project folder upload.
	 *
	 * @param userId the user ID of this project folder upload
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this project folder upload.
	 *
	 * @return the user uuid of this project folder upload
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this project folder upload.
	 *
	 * @param userUuid the user uuid of this project folder upload
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the deleted by of this project folder upload.
	 *
	 * @return the deleted by of this project folder upload
	 */
	public long getDeletedBy();

	/**
	 * Sets the deleted by of this project folder upload.
	 *
	 * @param deletedBy the deleted by of this project folder upload
	 */
	public void setDeletedBy(long deletedBy);

	/**
	 * Returns the parent folder ID of this project folder upload.
	 *
	 * @return the parent folder ID of this project folder upload
	 */
	public long getParentFolderId();

	/**
	 * Sets the parent folder ID of this project folder upload.
	 *
	 * @param parentFolderId the parent folder ID of this project folder upload
	 */
	public void setParentFolderId(long parentFolderId);

	/**
	 * Returns the folder ID of this project folder upload.
	 *
	 * @return the folder ID of this project folder upload
	 */
	public long getFolderId();

	/**
	 * Sets the folder ID of this project folder upload.
	 *
	 * @param folderId the folder ID of this project folder upload
	 */
	public void setFolderId(long folderId);

	/**
	 * Returns the folder name of this project folder upload.
	 *
	 * @return the folder name of this project folder upload
	 */
	@AutoEscape
	public String getFolderName();

	/**
	 * Sets the folder name of this project folder upload.
	 *
	 * @param folderName the folder name of this project folder upload
	 */
	public void setFolderName(String folderName);

	/**
	 * Returns the description of this project folder upload.
	 *
	 * @return the description of this project folder upload
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this project folder upload.
	 *
	 * @param description the description of this project folder upload
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.projectFolderUpload projectFolderUpload);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.projectFolderUpload> toCacheModel();

	@Override
	public com.collaborated.entity.model.projectFolderUpload toEscapedModel();

	@Override
	public com.collaborated.entity.model.projectFolderUpload toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}