/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the projectInviteTracking service. Represents a row in the &quot;collaborated_projectInviteTracking&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.projectInviteTrackingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.projectInviteTrackingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see projectInviteTracking
 * @see com.collaborated.entity.model.impl.projectInviteTrackingImpl
 * @see com.collaborated.entity.model.impl.projectInviteTrackingModelImpl
 * @generated
 */
@ProviderType
public interface projectInviteTrackingModel extends BaseModel<projectInviteTracking> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project invite tracking model instance should use the {@link projectInviteTracking} interface instead.
	 */

	/**
	 * Returns the primary key of this project invite tracking.
	 *
	 * @return the primary key of this project invite tracking
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project invite tracking.
	 *
	 * @param primaryKey the primary key of this project invite tracking
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_project invitation ID of this project invite tracking.
	 *
	 * @return the p k_project invitation ID of this project invite tracking
	 */
	public long getPK_projectInvitationId();

	/**
	 * Sets the p k_project invitation ID of this project invite tracking.
	 *
	 * @param PK_projectInvitationId the p k_project invitation ID of this project invite tracking
	 */
	public void setPK_projectInvitationId(long PK_projectInvitationId);

	/**
	 * Returns the group ID of this project invite tracking.
	 *
	 * @return the group ID of this project invite tracking
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this project invite tracking.
	 *
	 * @param groupId the group ID of this project invite tracking
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this project invite tracking.
	 *
	 * @return the create date of this project invite tracking
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this project invite tracking.
	 *
	 * @param createDate the create date of this project invite tracking
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this project invite tracking.
	 *
	 * @return the modified date of this project invite tracking
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this project invite tracking.
	 *
	 * @param modifiedDate the modified date of this project invite tracking
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the project ID of this project invite tracking.
	 *
	 * @return the project ID of this project invite tracking
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this project invite tracking.
	 *
	 * @param projectId the project ID of this project invite tracking
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the invite from of this project invite tracking.
	 *
	 * @return the invite from of this project invite tracking
	 */
	public long getInviteFrom();

	/**
	 * Sets the invite from of this project invite tracking.
	 *
	 * @param inviteFrom the invite from of this project invite tracking
	 */
	public void setInviteFrom(long inviteFrom);

	/**
	 * Returns the invite to of this project invite tracking.
	 *
	 * @return the invite to of this project invite tracking
	 */
	public long getInviteTo();

	/**
	 * Sets the invite to of this project invite tracking.
	 *
	 * @param inviteTo the invite to of this project invite tracking
	 */
	public void setInviteTo(long inviteTo);

	/**
	 * Returns the invitation status of this project invite tracking.
	 *
	 * @return the invitation status of this project invite tracking
	 */
	@AutoEscape
	public String getInvitationStatus();

	/**
	 * Sets the invitation status of this project invite tracking.
	 *
	 * @param invitationStatus the invitation status of this project invite tracking
	 */
	public void setInvitationStatus(String invitationStatus);

	/**
	 * Returns the is read of this project invite tracking.
	 *
	 * @return the is read of this project invite tracking
	 */
	public long getIsRead();

	/**
	 * Sets the is read of this project invite tracking.
	 *
	 * @param isRead the is read of this project invite tracking
	 */
	public void setIsRead(long isRead);

	/**
	 * Returns the is removed of this project invite tracking.
	 *
	 * @return the is removed of this project invite tracking
	 */
	public long getIsRemoved();

	/**
	 * Sets the is removed of this project invite tracking.
	 *
	 * @param isRemoved the is removed of this project invite tracking
	 */
	public void setIsRemoved(long isRemoved);

	/**
	 * Returns the message title of this project invite tracking.
	 *
	 * @return the message title of this project invite tracking
	 */
	@AutoEscape
	public String getMessageTitle();

	/**
	 * Sets the message title of this project invite tracking.
	 *
	 * @param messageTitle the message title of this project invite tracking
	 */
	public void setMessageTitle(String messageTitle);

	/**
	 * Returns the message content of this project invite tracking.
	 *
	 * @return the message content of this project invite tracking
	 */
	@AutoEscape
	public String getMessageContent();

	/**
	 * Sets the message content of this project invite tracking.
	 *
	 * @param messageContent the message content of this project invite tracking
	 */
	public void setMessageContent(String messageContent);

	/**
	 * Returns the email content of this project invite tracking.
	 *
	 * @return the email content of this project invite tracking
	 */
	@AutoEscape
	public String getEmailContent();

	/**
	 * Sets the email content of this project invite tracking.
	 *
	 * @param emailContent the email content of this project invite tracking
	 */
	public void setEmailContent(String emailContent);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.projectInviteTracking projectInviteTracking);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.projectInviteTracking> toCacheModel();

	@Override
	public com.collaborated.entity.model.projectInviteTracking toEscapedModel();

	@Override
	public com.collaborated.entity.model.projectInviteTracking toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}