/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the userCredential service. Represents a row in the &quot;collaborated_userCredential&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.userCredentialModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.userCredentialImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see userCredential
 * @see com.collaborated.entity.model.impl.userCredentialImpl
 * @see com.collaborated.entity.model.impl.userCredentialModelImpl
 * @generated
 */
@ProviderType
public interface userCredentialModel extends BaseModel<userCredential> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user credential model instance should use the {@link userCredential} interface instead.
	 */

	/**
	 * Returns the primary key of this user credential.
	 *
	 * @return the primary key of this user credential
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user credential.
	 *
	 * @param primaryKey the primary key of this user credential
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_user credential of this user credential.
	 *
	 * @return the p k_user credential of this user credential
	 */
	public long getPK_userCredential();

	/**
	 * Sets the p k_user credential of this user credential.
	 *
	 * @param PK_userCredential the p k_user credential of this user credential
	 */
	public void setPK_userCredential(long PK_userCredential);

	/**
	 * Returns the group ID of this user credential.
	 *
	 * @return the group ID of this user credential
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this user credential.
	 *
	 * @param groupId the group ID of this user credential
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this user credential.
	 *
	 * @return the user ID of this user credential
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user credential.
	 *
	 * @param userId the user ID of this user credential
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user credential.
	 *
	 * @return the user uuid of this user credential
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user credential.
	 *
	 * @param userUuid the user uuid of this user credential
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this user credential.
	 *
	 * @return the create date of this user credential
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user credential.
	 *
	 * @param createDate the create date of this user credential
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user credential.
	 *
	 * @return the modified date of this user credential
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user credential.
	 *
	 * @param modifiedDate the modified date of this user credential
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the membership1 of this user credential.
	 *
	 * @return the membership1 of this user credential
	 */
	@AutoEscape
	public String getMembership1();

	/**
	 * Sets the membership1 of this user credential.
	 *
	 * @param membership1 the membership1 of this user credential
	 */
	public void setMembership1(String membership1);

	/**
	 * Returns the membership2 of this user credential.
	 *
	 * @return the membership2 of this user credential
	 */
	@AutoEscape
	public String getMembership2();

	/**
	 * Sets the membership2 of this user credential.
	 *
	 * @param membership2 the membership2 of this user credential
	 */
	public void setMembership2(String membership2);

	/**
	 * Returns the membership3 of this user credential.
	 *
	 * @return the membership3 of this user credential
	 */
	@AutoEscape
	public String getMembership3();

	/**
	 * Sets the membership3 of this user credential.
	 *
	 * @param membership3 the membership3 of this user credential
	 */
	public void setMembership3(String membership3);

	/**
	 * Returns the membership4 of this user credential.
	 *
	 * @return the membership4 of this user credential
	 */
	@AutoEscape
	public String getMembership4();

	/**
	 * Sets the membership4 of this user credential.
	 *
	 * @param membership4 the membership4 of this user credential
	 */
	public void setMembership4(String membership4);

	/**
	 * Returns the certificate1 of this user credential.
	 *
	 * @return the certificate1 of this user credential
	 */
	@AutoEscape
	public String getCertificate1();

	/**
	 * Sets the certificate1 of this user credential.
	 *
	 * @param certificate1 the certificate1 of this user credential
	 */
	public void setCertificate1(String certificate1);

	/**
	 * Returns the certificate2 of this user credential.
	 *
	 * @return the certificate2 of this user credential
	 */
	@AutoEscape
	public String getCertificate2();

	/**
	 * Sets the certificate2 of this user credential.
	 *
	 * @param certificate2 the certificate2 of this user credential
	 */
	public void setCertificate2(String certificate2);

	/**
	 * Returns the certificate3 of this user credential.
	 *
	 * @return the certificate3 of this user credential
	 */
	@AutoEscape
	public String getCertificate3();

	/**
	 * Sets the certificate3 of this user credential.
	 *
	 * @param certificate3 the certificate3 of this user credential
	 */
	public void setCertificate3(String certificate3);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.userCredential userCredential);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.userCredential> toCacheModel();

	@Override
	public com.collaborated.entity.model.userCredential toEscapedModel();

	@Override
	public com.collaborated.entity.model.userCredential toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}