/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the userProfessionalBio service. Represents a row in the &quot;collaborated_userProfessionalBio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.userProfessionalBioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.userProfessionalBioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see userProfessionalBio
 * @see com.collaborated.entity.model.impl.userProfessionalBioImpl
 * @see com.collaborated.entity.model.impl.userProfessionalBioModelImpl
 * @generated
 */
@ProviderType
public interface userProfessionalBioModel extends BaseModel<userProfessionalBio> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user professional bio model instance should use the {@link userProfessionalBio} interface instead.
	 */

	/**
	 * Returns the primary key of this user professional bio.
	 *
	 * @return the primary key of this user professional bio
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user professional bio.
	 *
	 * @param primaryKey the primary key of this user professional bio
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_user professional bio of this user professional bio.
	 *
	 * @return the p k_user professional bio of this user professional bio
	 */
	public long getPK_userProfessionalBio();

	/**
	 * Sets the p k_user professional bio of this user professional bio.
	 *
	 * @param PK_userProfessionalBio the p k_user professional bio of this user professional bio
	 */
	public void setPK_userProfessionalBio(long PK_userProfessionalBio);

	/**
	 * Returns the group ID of this user professional bio.
	 *
	 * @return the group ID of this user professional bio
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this user professional bio.
	 *
	 * @param groupId the group ID of this user professional bio
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this user professional bio.
	 *
	 * @return the user ID of this user professional bio
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user professional bio.
	 *
	 * @param userId the user ID of this user professional bio
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user professional bio.
	 *
	 * @return the user uuid of this user professional bio
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user professional bio.
	 *
	 * @param userUuid the user uuid of this user professional bio
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this user professional bio.
	 *
	 * @return the create date of this user professional bio
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user professional bio.
	 *
	 * @param createDate the create date of this user professional bio
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user professional bio.
	 *
	 * @return the modified date of this user professional bio
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user professional bio.
	 *
	 * @param modifiedDate the modified date of this user professional bio
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the areaofexpertise1 of this user professional bio.
	 *
	 * @return the areaofexpertise1 of this user professional bio
	 */
	@AutoEscape
	public String getAreaofexpertise1();

	/**
	 * Sets the areaofexpertise1 of this user professional bio.
	 *
	 * @param areaofexpertise1 the areaofexpertise1 of this user professional bio
	 */
	public void setAreaofexpertise1(String areaofexpertise1);

	/**
	 * Returns the areaofexpertise2 of this user professional bio.
	 *
	 * @return the areaofexpertise2 of this user professional bio
	 */
	@AutoEscape
	public String getAreaofexpertise2();

	/**
	 * Sets the areaofexpertise2 of this user professional bio.
	 *
	 * @param areaofexpertise2 the areaofexpertise2 of this user professional bio
	 */
	public void setAreaofexpertise2(String areaofexpertise2);

	/**
	 * Returns the areaofexpertise3 of this user professional bio.
	 *
	 * @return the areaofexpertise3 of this user professional bio
	 */
	@AutoEscape
	public String getAreaofexpertise3();

	/**
	 * Sets the areaofexpertise3 of this user professional bio.
	 *
	 * @param areaofexpertise3 the areaofexpertise3 of this user professional bio
	 */
	public void setAreaofexpertise3(String areaofexpertise3);

	/**
	 * Returns the experienceyears of this user professional bio.
	 *
	 * @return the experienceyears of this user professional bio
	 */
	@AutoEscape
	public String getExperienceyears();

	/**
	 * Sets the experienceyears of this user professional bio.
	 *
	 * @param experienceyears the experienceyears of this user professional bio
	 */
	public void setExperienceyears(String experienceyears);

	/**
	 * Returns the cvlink of this user professional bio.
	 *
	 * @return the cvlink of this user professional bio
	 */
	@AutoEscape
	public String getCvlink();

	/**
	 * Sets the cvlink of this user professional bio.
	 *
	 * @param cvlink the cvlink of this user professional bio
	 */
	public void setCvlink(String cvlink);

	/**
	 * Returns the biodescription of this user professional bio.
	 *
	 * @return the biodescription of this user professional bio
	 */
	@AutoEscape
	public String getBiodescription();

	/**
	 * Sets the biodescription of this user professional bio.
	 *
	 * @param biodescription the biodescription of this user professional bio
	 */
	public void setBiodescription(String biodescription);

	/**
	 * Returns the bio discipline of this user professional bio.
	 *
	 * @return the bio discipline of this user professional bio
	 */
	@AutoEscape
	public String getBioDiscipline();

	/**
	 * Sets the bio discipline of this user professional bio.
	 *
	 * @param bioDiscipline the bio discipline of this user professional bio
	 */
	public void setBioDiscipline(String bioDiscipline);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.userProfessionalBio userProfessionalBio);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.userProfessionalBio> toCacheModel();

	@Override
	public com.collaborated.entity.model.userProfessionalBio toEscapedModel();

	@Override
	public com.collaborated.entity.model.userProfessionalBio toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}