/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the userInstitutionProfileSubDetails service. Represents a row in the &quot;collaborated_userInstitutionProfileSubDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.collaborated.entity.model.impl.userInstitutionProfileSubDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.collaborated.entity.model.impl.userInstitutionProfileSubDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see userInstitutionProfileSubDetails
 * @see com.collaborated.entity.model.impl.userInstitutionProfileSubDetailsImpl
 * @see com.collaborated.entity.model.impl.userInstitutionProfileSubDetailsModelImpl
 * @generated
 */
@ProviderType
public interface userInstitutionProfileSubDetailsModel extends BaseModel<userInstitutionProfileSubDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user institution profile sub details model instance should use the {@link userInstitutionProfileSubDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this user institution profile sub details.
	 *
	 * @return the primary key of this user institution profile sub details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user institution profile sub details.
	 *
	 * @param primaryKey the primary key of this user institution profile sub details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the p k_user instition sub of this user institution profile sub details.
	 *
	 * @return the p k_user instition sub of this user institution profile sub details
	 */
	public long getPK_userInstitionSub();

	/**
	 * Sets the p k_user instition sub of this user institution profile sub details.
	 *
	 * @param PK_userInstitionSub the p k_user instition sub of this user institution profile sub details
	 */
	public void setPK_userInstitionSub(long PK_userInstitionSub);

	/**
	 * Returns the group ID of this user institution profile sub details.
	 *
	 * @return the group ID of this user institution profile sub details
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this user institution profile sub details.
	 *
	 * @param groupId the group ID of this user institution profile sub details
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this user institution profile sub details.
	 *
	 * @return the user ID of this user institution profile sub details
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user institution profile sub details.
	 *
	 * @param userId the user ID of this user institution profile sub details
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user institution profile sub details.
	 *
	 * @return the user uuid of this user institution profile sub details
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user institution profile sub details.
	 *
	 * @param userUuid the user uuid of this user institution profile sub details
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this user institution profile sub details.
	 *
	 * @return the create date of this user institution profile sub details
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user institution profile sub details.
	 *
	 * @param createDate the create date of this user institution profile sub details
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user institution profile sub details.
	 *
	 * @return the modified date of this user institution profile sub details
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user institution profile sub details.
	 *
	 * @param modifiedDate the modified date of this user institution profile sub details
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the file ID of this user institution profile sub details.
	 *
	 * @return the file ID of this user institution profile sub details
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this user institution profile sub details.
	 *
	 * @param fileId the file ID of this user institution profile sub details
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the p k_user instition of this user institution profile sub details.
	 *
	 * @return the p k_user instition of this user institution profile sub details
	 */
	public long getPK_userInstition();

	/**
	 * Sets the p k_user instition of this user institution profile sub details.
	 *
	 * @param PK_userInstition the p k_user instition of this user institution profile sub details
	 */
	public void setPK_userInstition(long PK_userInstition);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.collaborated.entity.model.userInstitutionProfileSubDetails userInstitutionProfileSubDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.collaborated.entity.model.userInstitutionProfileSubDetails> toCacheModel();

	@Override
	public com.collaborated.entity.model.userInstitutionProfileSubDetails toEscapedModel();

	@Override
	public com.collaborated.entity.model.userInstitutionProfileSubDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}