/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.service.base;

import com.collaborated.entity.model.projectFilesUpload;
import com.collaborated.entity.service.persistence.Custom_CalendarPersistence;
import com.collaborated.entity.service.persistence.Custom_WorkflowLogPersistence;
import com.collaborated.entity.service.persistence.Custom_WorkflowPersistence;
import com.collaborated.entity.service.persistence.Custom_Workflow_CompletedPersistence;
import com.collaborated.entity.service.persistence.Custom_Workflow_TaskPersistence;
import com.collaborated.entity.service.persistence.Custom_Workflow_TransitionPersistence;
import com.collaborated.entity.service.persistence.commonWebsserviceAPIPersistence;
import com.collaborated.entity.service.persistence.communicationPreferencesPersistence;
import com.collaborated.entity.service.persistence.labDetailedActivityTablePersistence;
import com.collaborated.entity.service.persistence.labDetailedCourseHoursPersistence;
import com.collaborated.entity.service.persistence.labDetailedCourseIdentificationPersistence;
import com.collaborated.entity.service.persistence.labDetailedCourseObjectivesPersistence;
import com.collaborated.entity.service.persistence.labDetailedCourseResourcesPersistence;
import com.collaborated.entity.service.persistence.labDetailedCourseTopicsPersistence;
import com.collaborated.entity.service.persistence.labDetailedInstructorQualificationPersistence;
import com.collaborated.entity.service.persistence.labDetailedLearningEnvironmentsPersistence;
import com.collaborated.entity.service.persistence.labScreenProjectOverviewPersistence;
import com.collaborated.entity.service.persistence.labScreenProjectPartnersPersistence;
import com.collaborated.entity.service.persistence.labScreenTaskPersistence;
import com.collaborated.entity.service.persistence.languagePreferencesPersistence;
import com.collaborated.entity.service.persistence.profileAreaofinterestPersistence;
import com.collaborated.entity.service.persistence.projectDiscussionPersistence;
import com.collaborated.entity.service.persistence.projectFilesUploadPersistence;
import com.collaborated.entity.service.persistence.projectFolderUploadPersistence;
import com.collaborated.entity.service.persistence.projectInviteTrackingPersistence;
import com.collaborated.entity.service.persistence.userCredentialPersistence;
import com.collaborated.entity.service.persistence.userInstitutionProfileDetailsPersistence;
import com.collaborated.entity.service.persistence.userInstitutionProfileSubDetailsPersistence;
import com.collaborated.entity.service.persistence.userProfessionalBioPersistence;
import com.collaborated.entity.service.persistence.userProfileImagePersistence;
import com.collaborated.entity.service.projectFilesUploadService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the project files upload remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.collaborated.entity.service.impl.projectFilesUploadServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.collaborated.entity.service.impl.projectFilesUploadServiceImpl
 * @see com.collaborated.entity.service.projectFilesUploadServiceUtil
 * @generated
 */
public abstract class projectFilesUploadServiceBaseImpl extends BaseServiceImpl
	implements projectFilesUploadService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.collaborated.entity.service.projectFilesUploadServiceUtil} to access the project files upload remote service.
	 */

	/**
	 * Returns the common websservice a p i local service.
	 *
	 * @return the common websservice a p i local service
	 */
	public com.collaborated.entity.service.commonWebsserviceAPILocalService getcommonWebsserviceAPILocalService() {
		return commonWebsserviceAPILocalService;
	}

	/**
	 * Sets the common websservice a p i local service.
	 *
	 * @param commonWebsserviceAPILocalService the common websservice a p i local service
	 */
	public void setcommonWebsserviceAPILocalService(
		com.collaborated.entity.service.commonWebsserviceAPILocalService commonWebsserviceAPILocalService) {
		this.commonWebsserviceAPILocalService = commonWebsserviceAPILocalService;
	}

	/**
	 * Returns the common websservice a p i remote service.
	 *
	 * @return the common websservice a p i remote service
	 */
	public com.collaborated.entity.service.commonWebsserviceAPIService getcommonWebsserviceAPIService() {
		return commonWebsserviceAPIService;
	}

	/**
	 * Sets the common websservice a p i remote service.
	 *
	 * @param commonWebsserviceAPIService the common websservice a p i remote service
	 */
	public void setcommonWebsserviceAPIService(
		com.collaborated.entity.service.commonWebsserviceAPIService commonWebsserviceAPIService) {
		this.commonWebsserviceAPIService = commonWebsserviceAPIService;
	}

	/**
	 * Returns the common websservice a p i persistence.
	 *
	 * @return the common websservice a p i persistence
	 */
	public commonWebsserviceAPIPersistence getcommonWebsserviceAPIPersistence() {
		return commonWebsserviceAPIPersistence;
	}

	/**
	 * Sets the common websservice a p i persistence.
	 *
	 * @param commonWebsserviceAPIPersistence the common websservice a p i persistence
	 */
	public void setcommonWebsserviceAPIPersistence(
		commonWebsserviceAPIPersistence commonWebsserviceAPIPersistence) {
		this.commonWebsserviceAPIPersistence = commonWebsserviceAPIPersistence;
	}

	/**
	 * Returns the communication preferences local service.
	 *
	 * @return the communication preferences local service
	 */
	public com.collaborated.entity.service.communicationPreferencesLocalService getcommunicationPreferencesLocalService() {
		return communicationPreferencesLocalService;
	}

	/**
	 * Sets the communication preferences local service.
	 *
	 * @param communicationPreferencesLocalService the communication preferences local service
	 */
	public void setcommunicationPreferencesLocalService(
		com.collaborated.entity.service.communicationPreferencesLocalService communicationPreferencesLocalService) {
		this.communicationPreferencesLocalService = communicationPreferencesLocalService;
	}

	/**
	 * Returns the communication preferences remote service.
	 *
	 * @return the communication preferences remote service
	 */
	public com.collaborated.entity.service.communicationPreferencesService getcommunicationPreferencesService() {
		return communicationPreferencesService;
	}

	/**
	 * Sets the communication preferences remote service.
	 *
	 * @param communicationPreferencesService the communication preferences remote service
	 */
	public void setcommunicationPreferencesService(
		com.collaborated.entity.service.communicationPreferencesService communicationPreferencesService) {
		this.communicationPreferencesService = communicationPreferencesService;
	}

	/**
	 * Returns the communication preferences persistence.
	 *
	 * @return the communication preferences persistence
	 */
	public communicationPreferencesPersistence getcommunicationPreferencesPersistence() {
		return communicationPreferencesPersistence;
	}

	/**
	 * Sets the communication preferences persistence.
	 *
	 * @param communicationPreferencesPersistence the communication preferences persistence
	 */
	public void setcommunicationPreferencesPersistence(
		communicationPreferencesPersistence communicationPreferencesPersistence) {
		this.communicationPreferencesPersistence = communicationPreferencesPersistence;
	}

	/**
	 * Returns the custom_ calendar local service.
	 *
	 * @return the custom_ calendar local service
	 */
	public com.collaborated.entity.service.Custom_CalendarLocalService getCustom_CalendarLocalService() {
		return custom_CalendarLocalService;
	}

	/**
	 * Sets the custom_ calendar local service.
	 *
	 * @param custom_CalendarLocalService the custom_ calendar local service
	 */
	public void setCustom_CalendarLocalService(
		com.collaborated.entity.service.Custom_CalendarLocalService custom_CalendarLocalService) {
		this.custom_CalendarLocalService = custom_CalendarLocalService;
	}

	/**
	 * Returns the custom_ calendar remote service.
	 *
	 * @return the custom_ calendar remote service
	 */
	public com.collaborated.entity.service.Custom_CalendarService getCustom_CalendarService() {
		return custom_CalendarService;
	}

	/**
	 * Sets the custom_ calendar remote service.
	 *
	 * @param custom_CalendarService the custom_ calendar remote service
	 */
	public void setCustom_CalendarService(
		com.collaborated.entity.service.Custom_CalendarService custom_CalendarService) {
		this.custom_CalendarService = custom_CalendarService;
	}

	/**
	 * Returns the custom_ calendar persistence.
	 *
	 * @return the custom_ calendar persistence
	 */
	public Custom_CalendarPersistence getCustom_CalendarPersistence() {
		return custom_CalendarPersistence;
	}

	/**
	 * Sets the custom_ calendar persistence.
	 *
	 * @param custom_CalendarPersistence the custom_ calendar persistence
	 */
	public void setCustom_CalendarPersistence(
		Custom_CalendarPersistence custom_CalendarPersistence) {
		this.custom_CalendarPersistence = custom_CalendarPersistence;
	}

	/**
	 * Returns the custom_ workflow local service.
	 *
	 * @return the custom_ workflow local service
	 */
	public com.collaborated.entity.service.Custom_WorkflowLocalService getCustom_WorkflowLocalService() {
		return custom_WorkflowLocalService;
	}

	/**
	 * Sets the custom_ workflow local service.
	 *
	 * @param custom_WorkflowLocalService the custom_ workflow local service
	 */
	public void setCustom_WorkflowLocalService(
		com.collaborated.entity.service.Custom_WorkflowLocalService custom_WorkflowLocalService) {
		this.custom_WorkflowLocalService = custom_WorkflowLocalService;
	}

	/**
	 * Returns the custom_ workflow remote service.
	 *
	 * @return the custom_ workflow remote service
	 */
	public com.collaborated.entity.service.Custom_WorkflowService getCustom_WorkflowService() {
		return custom_WorkflowService;
	}

	/**
	 * Sets the custom_ workflow remote service.
	 *
	 * @param custom_WorkflowService the custom_ workflow remote service
	 */
	public void setCustom_WorkflowService(
		com.collaborated.entity.service.Custom_WorkflowService custom_WorkflowService) {
		this.custom_WorkflowService = custom_WorkflowService;
	}

	/**
	 * Returns the custom_ workflow persistence.
	 *
	 * @return the custom_ workflow persistence
	 */
	public Custom_WorkflowPersistence getCustom_WorkflowPersistence() {
		return custom_WorkflowPersistence;
	}

	/**
	 * Sets the custom_ workflow persistence.
	 *
	 * @param custom_WorkflowPersistence the custom_ workflow persistence
	 */
	public void setCustom_WorkflowPersistence(
		Custom_WorkflowPersistence custom_WorkflowPersistence) {
		this.custom_WorkflowPersistence = custom_WorkflowPersistence;
	}

	/**
	 * Returns the custom_ workflow_ completed local service.
	 *
	 * @return the custom_ workflow_ completed local service
	 */
	public com.collaborated.entity.service.Custom_Workflow_CompletedLocalService getCustom_Workflow_CompletedLocalService() {
		return custom_Workflow_CompletedLocalService;
	}

	/**
	 * Sets the custom_ workflow_ completed local service.
	 *
	 * @param custom_Workflow_CompletedLocalService the custom_ workflow_ completed local service
	 */
	public void setCustom_Workflow_CompletedLocalService(
		com.collaborated.entity.service.Custom_Workflow_CompletedLocalService custom_Workflow_CompletedLocalService) {
		this.custom_Workflow_CompletedLocalService = custom_Workflow_CompletedLocalService;
	}

	/**
	 * Returns the custom_ workflow_ completed remote service.
	 *
	 * @return the custom_ workflow_ completed remote service
	 */
	public com.collaborated.entity.service.Custom_Workflow_CompletedService getCustom_Workflow_CompletedService() {
		return custom_Workflow_CompletedService;
	}

	/**
	 * Sets the custom_ workflow_ completed remote service.
	 *
	 * @param custom_Workflow_CompletedService the custom_ workflow_ completed remote service
	 */
	public void setCustom_Workflow_CompletedService(
		com.collaborated.entity.service.Custom_Workflow_CompletedService custom_Workflow_CompletedService) {
		this.custom_Workflow_CompletedService = custom_Workflow_CompletedService;
	}

	/**
	 * Returns the custom_ workflow_ completed persistence.
	 *
	 * @return the custom_ workflow_ completed persistence
	 */
	public Custom_Workflow_CompletedPersistence getCustom_Workflow_CompletedPersistence() {
		return custom_Workflow_CompletedPersistence;
	}

	/**
	 * Sets the custom_ workflow_ completed persistence.
	 *
	 * @param custom_Workflow_CompletedPersistence the custom_ workflow_ completed persistence
	 */
	public void setCustom_Workflow_CompletedPersistence(
		Custom_Workflow_CompletedPersistence custom_Workflow_CompletedPersistence) {
		this.custom_Workflow_CompletedPersistence = custom_Workflow_CompletedPersistence;
	}

	/**
	 * Returns the custom_ workflow_ task local service.
	 *
	 * @return the custom_ workflow_ task local service
	 */
	public com.collaborated.entity.service.Custom_Workflow_TaskLocalService getCustom_Workflow_TaskLocalService() {
		return custom_Workflow_TaskLocalService;
	}

	/**
	 * Sets the custom_ workflow_ task local service.
	 *
	 * @param custom_Workflow_TaskLocalService the custom_ workflow_ task local service
	 */
	public void setCustom_Workflow_TaskLocalService(
		com.collaborated.entity.service.Custom_Workflow_TaskLocalService custom_Workflow_TaskLocalService) {
		this.custom_Workflow_TaskLocalService = custom_Workflow_TaskLocalService;
	}

	/**
	 * Returns the custom_ workflow_ task remote service.
	 *
	 * @return the custom_ workflow_ task remote service
	 */
	public com.collaborated.entity.service.Custom_Workflow_TaskService getCustom_Workflow_TaskService() {
		return custom_Workflow_TaskService;
	}

	/**
	 * Sets the custom_ workflow_ task remote service.
	 *
	 * @param custom_Workflow_TaskService the custom_ workflow_ task remote service
	 */
	public void setCustom_Workflow_TaskService(
		com.collaborated.entity.service.Custom_Workflow_TaskService custom_Workflow_TaskService) {
		this.custom_Workflow_TaskService = custom_Workflow_TaskService;
	}

	/**
	 * Returns the custom_ workflow_ task persistence.
	 *
	 * @return the custom_ workflow_ task persistence
	 */
	public Custom_Workflow_TaskPersistence getCustom_Workflow_TaskPersistence() {
		return custom_Workflow_TaskPersistence;
	}

	/**
	 * Sets the custom_ workflow_ task persistence.
	 *
	 * @param custom_Workflow_TaskPersistence the custom_ workflow_ task persistence
	 */
	public void setCustom_Workflow_TaskPersistence(
		Custom_Workflow_TaskPersistence custom_Workflow_TaskPersistence) {
		this.custom_Workflow_TaskPersistence = custom_Workflow_TaskPersistence;
	}

	/**
	 * Returns the custom_ workflow_ transition local service.
	 *
	 * @return the custom_ workflow_ transition local service
	 */
	public com.collaborated.entity.service.Custom_Workflow_TransitionLocalService getCustom_Workflow_TransitionLocalService() {
		return custom_Workflow_TransitionLocalService;
	}

	/**
	 * Sets the custom_ workflow_ transition local service.
	 *
	 * @param custom_Workflow_TransitionLocalService the custom_ workflow_ transition local service
	 */
	public void setCustom_Workflow_TransitionLocalService(
		com.collaborated.entity.service.Custom_Workflow_TransitionLocalService custom_Workflow_TransitionLocalService) {
		this.custom_Workflow_TransitionLocalService = custom_Workflow_TransitionLocalService;
	}

	/**
	 * Returns the custom_ workflow_ transition remote service.
	 *
	 * @return the custom_ workflow_ transition remote service
	 */
	public com.collaborated.entity.service.Custom_Workflow_TransitionService getCustom_Workflow_TransitionService() {
		return custom_Workflow_TransitionService;
	}

	/**
	 * Sets the custom_ workflow_ transition remote service.
	 *
	 * @param custom_Workflow_TransitionService the custom_ workflow_ transition remote service
	 */
	public void setCustom_Workflow_TransitionService(
		com.collaborated.entity.service.Custom_Workflow_TransitionService custom_Workflow_TransitionService) {
		this.custom_Workflow_TransitionService = custom_Workflow_TransitionService;
	}

	/**
	 * Returns the custom_ workflow_ transition persistence.
	 *
	 * @return the custom_ workflow_ transition persistence
	 */
	public Custom_Workflow_TransitionPersistence getCustom_Workflow_TransitionPersistence() {
		return custom_Workflow_TransitionPersistence;
	}

	/**
	 * Sets the custom_ workflow_ transition persistence.
	 *
	 * @param custom_Workflow_TransitionPersistence the custom_ workflow_ transition persistence
	 */
	public void setCustom_Workflow_TransitionPersistence(
		Custom_Workflow_TransitionPersistence custom_Workflow_TransitionPersistence) {
		this.custom_Workflow_TransitionPersistence = custom_Workflow_TransitionPersistence;
	}

	/**
	 * Returns the custom_ workflow log local service.
	 *
	 * @return the custom_ workflow log local service
	 */
	public com.collaborated.entity.service.Custom_WorkflowLogLocalService getCustom_WorkflowLogLocalService() {
		return custom_WorkflowLogLocalService;
	}

	/**
	 * Sets the custom_ workflow log local service.
	 *
	 * @param custom_WorkflowLogLocalService the custom_ workflow log local service
	 */
	public void setCustom_WorkflowLogLocalService(
		com.collaborated.entity.service.Custom_WorkflowLogLocalService custom_WorkflowLogLocalService) {
		this.custom_WorkflowLogLocalService = custom_WorkflowLogLocalService;
	}

	/**
	 * Returns the custom_ workflow log remote service.
	 *
	 * @return the custom_ workflow log remote service
	 */
	public com.collaborated.entity.service.Custom_WorkflowLogService getCustom_WorkflowLogService() {
		return custom_WorkflowLogService;
	}

	/**
	 * Sets the custom_ workflow log remote service.
	 *
	 * @param custom_WorkflowLogService the custom_ workflow log remote service
	 */
	public void setCustom_WorkflowLogService(
		com.collaborated.entity.service.Custom_WorkflowLogService custom_WorkflowLogService) {
		this.custom_WorkflowLogService = custom_WorkflowLogService;
	}

	/**
	 * Returns the custom_ workflow log persistence.
	 *
	 * @return the custom_ workflow log persistence
	 */
	public Custom_WorkflowLogPersistence getCustom_WorkflowLogPersistence() {
		return custom_WorkflowLogPersistence;
	}

	/**
	 * Sets the custom_ workflow log persistence.
	 *
	 * @param custom_WorkflowLogPersistence the custom_ workflow log persistence
	 */
	public void setCustom_WorkflowLogPersistence(
		Custom_WorkflowLogPersistence custom_WorkflowLogPersistence) {
		this.custom_WorkflowLogPersistence = custom_WorkflowLogPersistence;
	}

	/**
	 * Returns the lab detailed activity table local service.
	 *
	 * @return the lab detailed activity table local service
	 */
	public com.collaborated.entity.service.labDetailedActivityTableLocalService getlabDetailedActivityTableLocalService() {
		return labDetailedActivityTableLocalService;
	}

	/**
	 * Sets the lab detailed activity table local service.
	 *
	 * @param labDetailedActivityTableLocalService the lab detailed activity table local service
	 */
	public void setlabDetailedActivityTableLocalService(
		com.collaborated.entity.service.labDetailedActivityTableLocalService labDetailedActivityTableLocalService) {
		this.labDetailedActivityTableLocalService = labDetailedActivityTableLocalService;
	}

	/**
	 * Returns the lab detailed activity table remote service.
	 *
	 * @return the lab detailed activity table remote service
	 */
	public com.collaborated.entity.service.labDetailedActivityTableService getlabDetailedActivityTableService() {
		return labDetailedActivityTableService;
	}

	/**
	 * Sets the lab detailed activity table remote service.
	 *
	 * @param labDetailedActivityTableService the lab detailed activity table remote service
	 */
	public void setlabDetailedActivityTableService(
		com.collaborated.entity.service.labDetailedActivityTableService labDetailedActivityTableService) {
		this.labDetailedActivityTableService = labDetailedActivityTableService;
	}

	/**
	 * Returns the lab detailed activity table persistence.
	 *
	 * @return the lab detailed activity table persistence
	 */
	public labDetailedActivityTablePersistence getlabDetailedActivityTablePersistence() {
		return labDetailedActivityTablePersistence;
	}

	/**
	 * Sets the lab detailed activity table persistence.
	 *
	 * @param labDetailedActivityTablePersistence the lab detailed activity table persistence
	 */
	public void setlabDetailedActivityTablePersistence(
		labDetailedActivityTablePersistence labDetailedActivityTablePersistence) {
		this.labDetailedActivityTablePersistence = labDetailedActivityTablePersistence;
	}

	/**
	 * Returns the lab detailed course hours local service.
	 *
	 * @return the lab detailed course hours local service
	 */
	public com.collaborated.entity.service.labDetailedCourseHoursLocalService getlabDetailedCourseHoursLocalService() {
		return labDetailedCourseHoursLocalService;
	}

	/**
	 * Sets the lab detailed course hours local service.
	 *
	 * @param labDetailedCourseHoursLocalService the lab detailed course hours local service
	 */
	public void setlabDetailedCourseHoursLocalService(
		com.collaborated.entity.service.labDetailedCourseHoursLocalService labDetailedCourseHoursLocalService) {
		this.labDetailedCourseHoursLocalService = labDetailedCourseHoursLocalService;
	}

	/**
	 * Returns the lab detailed course hours remote service.
	 *
	 * @return the lab detailed course hours remote service
	 */
	public com.collaborated.entity.service.labDetailedCourseHoursService getlabDetailedCourseHoursService() {
		return labDetailedCourseHoursService;
	}

	/**
	 * Sets the lab detailed course hours remote service.
	 *
	 * @param labDetailedCourseHoursService the lab detailed course hours remote service
	 */
	public void setlabDetailedCourseHoursService(
		com.collaborated.entity.service.labDetailedCourseHoursService labDetailedCourseHoursService) {
		this.labDetailedCourseHoursService = labDetailedCourseHoursService;
	}

	/**
	 * Returns the lab detailed course hours persistence.
	 *
	 * @return the lab detailed course hours persistence
	 */
	public labDetailedCourseHoursPersistence getlabDetailedCourseHoursPersistence() {
		return labDetailedCourseHoursPersistence;
	}

	/**
	 * Sets the lab detailed course hours persistence.
	 *
	 * @param labDetailedCourseHoursPersistence the lab detailed course hours persistence
	 */
	public void setlabDetailedCourseHoursPersistence(
		labDetailedCourseHoursPersistence labDetailedCourseHoursPersistence) {
		this.labDetailedCourseHoursPersistence = labDetailedCourseHoursPersistence;
	}

	/**
	 * Returns the lab detailed course identification local service.
	 *
	 * @return the lab detailed course identification local service
	 */
	public com.collaborated.entity.service.labDetailedCourseIdentificationLocalService getlabDetailedCourseIdentificationLocalService() {
		return labDetailedCourseIdentificationLocalService;
	}

	/**
	 * Sets the lab detailed course identification local service.
	 *
	 * @param labDetailedCourseIdentificationLocalService the lab detailed course identification local service
	 */
	public void setlabDetailedCourseIdentificationLocalService(
		com.collaborated.entity.service.labDetailedCourseIdentificationLocalService labDetailedCourseIdentificationLocalService) {
		this.labDetailedCourseIdentificationLocalService = labDetailedCourseIdentificationLocalService;
	}

	/**
	 * Returns the lab detailed course identification remote service.
	 *
	 * @return the lab detailed course identification remote service
	 */
	public com.collaborated.entity.service.labDetailedCourseIdentificationService getlabDetailedCourseIdentificationService() {
		return labDetailedCourseIdentificationService;
	}

	/**
	 * Sets the lab detailed course identification remote service.
	 *
	 * @param labDetailedCourseIdentificationService the lab detailed course identification remote service
	 */
	public void setlabDetailedCourseIdentificationService(
		com.collaborated.entity.service.labDetailedCourseIdentificationService labDetailedCourseIdentificationService) {
		this.labDetailedCourseIdentificationService = labDetailedCourseIdentificationService;
	}

	/**
	 * Returns the lab detailed course identification persistence.
	 *
	 * @return the lab detailed course identification persistence
	 */
	public labDetailedCourseIdentificationPersistence getlabDetailedCourseIdentificationPersistence() {
		return labDetailedCourseIdentificationPersistence;
	}

	/**
	 * Sets the lab detailed course identification persistence.
	 *
	 * @param labDetailedCourseIdentificationPersistence the lab detailed course identification persistence
	 */
	public void setlabDetailedCourseIdentificationPersistence(
		labDetailedCourseIdentificationPersistence labDetailedCourseIdentificationPersistence) {
		this.labDetailedCourseIdentificationPersistence = labDetailedCourseIdentificationPersistence;
	}

	/**
	 * Returns the lab detailed course objectives local service.
	 *
	 * @return the lab detailed course objectives local service
	 */
	public com.collaborated.entity.service.labDetailedCourseObjectivesLocalService getlabDetailedCourseObjectivesLocalService() {
		return labDetailedCourseObjectivesLocalService;
	}

	/**
	 * Sets the lab detailed course objectives local service.
	 *
	 * @param labDetailedCourseObjectivesLocalService the lab detailed course objectives local service
	 */
	public void setlabDetailedCourseObjectivesLocalService(
		com.collaborated.entity.service.labDetailedCourseObjectivesLocalService labDetailedCourseObjectivesLocalService) {
		this.labDetailedCourseObjectivesLocalService = labDetailedCourseObjectivesLocalService;
	}

	/**
	 * Returns the lab detailed course objectives remote service.
	 *
	 * @return the lab detailed course objectives remote service
	 */
	public com.collaborated.entity.service.labDetailedCourseObjectivesService getlabDetailedCourseObjectivesService() {
		return labDetailedCourseObjectivesService;
	}

	/**
	 * Sets the lab detailed course objectives remote service.
	 *
	 * @param labDetailedCourseObjectivesService the lab detailed course objectives remote service
	 */
	public void setlabDetailedCourseObjectivesService(
		com.collaborated.entity.service.labDetailedCourseObjectivesService labDetailedCourseObjectivesService) {
		this.labDetailedCourseObjectivesService = labDetailedCourseObjectivesService;
	}

	/**
	 * Returns the lab detailed course objectives persistence.
	 *
	 * @return the lab detailed course objectives persistence
	 */
	public labDetailedCourseObjectivesPersistence getlabDetailedCourseObjectivesPersistence() {
		return labDetailedCourseObjectivesPersistence;
	}

	/**
	 * Sets the lab detailed course objectives persistence.
	 *
	 * @param labDetailedCourseObjectivesPersistence the lab detailed course objectives persistence
	 */
	public void setlabDetailedCourseObjectivesPersistence(
		labDetailedCourseObjectivesPersistence labDetailedCourseObjectivesPersistence) {
		this.labDetailedCourseObjectivesPersistence = labDetailedCourseObjectivesPersistence;
	}

	/**
	 * Returns the lab detailed course resources local service.
	 *
	 * @return the lab detailed course resources local service
	 */
	public com.collaborated.entity.service.labDetailedCourseResourcesLocalService getlabDetailedCourseResourcesLocalService() {
		return labDetailedCourseResourcesLocalService;
	}

	/**
	 * Sets the lab detailed course resources local service.
	 *
	 * @param labDetailedCourseResourcesLocalService the lab detailed course resources local service
	 */
	public void setlabDetailedCourseResourcesLocalService(
		com.collaborated.entity.service.labDetailedCourseResourcesLocalService labDetailedCourseResourcesLocalService) {
		this.labDetailedCourseResourcesLocalService = labDetailedCourseResourcesLocalService;
	}

	/**
	 * Returns the lab detailed course resources remote service.
	 *
	 * @return the lab detailed course resources remote service
	 */
	public com.collaborated.entity.service.labDetailedCourseResourcesService getlabDetailedCourseResourcesService() {
		return labDetailedCourseResourcesService;
	}

	/**
	 * Sets the lab detailed course resources remote service.
	 *
	 * @param labDetailedCourseResourcesService the lab detailed course resources remote service
	 */
	public void setlabDetailedCourseResourcesService(
		com.collaborated.entity.service.labDetailedCourseResourcesService labDetailedCourseResourcesService) {
		this.labDetailedCourseResourcesService = labDetailedCourseResourcesService;
	}

	/**
	 * Returns the lab detailed course resources persistence.
	 *
	 * @return the lab detailed course resources persistence
	 */
	public labDetailedCourseResourcesPersistence getlabDetailedCourseResourcesPersistence() {
		return labDetailedCourseResourcesPersistence;
	}

	/**
	 * Sets the lab detailed course resources persistence.
	 *
	 * @param labDetailedCourseResourcesPersistence the lab detailed course resources persistence
	 */
	public void setlabDetailedCourseResourcesPersistence(
		labDetailedCourseResourcesPersistence labDetailedCourseResourcesPersistence) {
		this.labDetailedCourseResourcesPersistence = labDetailedCourseResourcesPersistence;
	}

	/**
	 * Returns the lab detailed course topics local service.
	 *
	 * @return the lab detailed course topics local service
	 */
	public com.collaborated.entity.service.labDetailedCourseTopicsLocalService getlabDetailedCourseTopicsLocalService() {
		return labDetailedCourseTopicsLocalService;
	}

	/**
	 * Sets the lab detailed course topics local service.
	 *
	 * @param labDetailedCourseTopicsLocalService the lab detailed course topics local service
	 */
	public void setlabDetailedCourseTopicsLocalService(
		com.collaborated.entity.service.labDetailedCourseTopicsLocalService labDetailedCourseTopicsLocalService) {
		this.labDetailedCourseTopicsLocalService = labDetailedCourseTopicsLocalService;
	}

	/**
	 * Returns the lab detailed course topics remote service.
	 *
	 * @return the lab detailed course topics remote service
	 */
	public com.collaborated.entity.service.labDetailedCourseTopicsService getlabDetailedCourseTopicsService() {
		return labDetailedCourseTopicsService;
	}

	/**
	 * Sets the lab detailed course topics remote service.
	 *
	 * @param labDetailedCourseTopicsService the lab detailed course topics remote service
	 */
	public void setlabDetailedCourseTopicsService(
		com.collaborated.entity.service.labDetailedCourseTopicsService labDetailedCourseTopicsService) {
		this.labDetailedCourseTopicsService = labDetailedCourseTopicsService;
	}

	/**
	 * Returns the lab detailed course topics persistence.
	 *
	 * @return the lab detailed course topics persistence
	 */
	public labDetailedCourseTopicsPersistence getlabDetailedCourseTopicsPersistence() {
		return labDetailedCourseTopicsPersistence;
	}

	/**
	 * Sets the lab detailed course topics persistence.
	 *
	 * @param labDetailedCourseTopicsPersistence the lab detailed course topics persistence
	 */
	public void setlabDetailedCourseTopicsPersistence(
		labDetailedCourseTopicsPersistence labDetailedCourseTopicsPersistence) {
		this.labDetailedCourseTopicsPersistence = labDetailedCourseTopicsPersistence;
	}

	/**
	 * Returns the lab detailed instructor qualification local service.
	 *
	 * @return the lab detailed instructor qualification local service
	 */
	public com.collaborated.entity.service.labDetailedInstructorQualificationLocalService getlabDetailedInstructorQualificationLocalService() {
		return labDetailedInstructorQualificationLocalService;
	}

	/**
	 * Sets the lab detailed instructor qualification local service.
	 *
	 * @param labDetailedInstructorQualificationLocalService the lab detailed instructor qualification local service
	 */
	public void setlabDetailedInstructorQualificationLocalService(
		com.collaborated.entity.service.labDetailedInstructorQualificationLocalService labDetailedInstructorQualificationLocalService) {
		this.labDetailedInstructorQualificationLocalService = labDetailedInstructorQualificationLocalService;
	}

	/**
	 * Returns the lab detailed instructor qualification remote service.
	 *
	 * @return the lab detailed instructor qualification remote service
	 */
	public com.collaborated.entity.service.labDetailedInstructorQualificationService getlabDetailedInstructorQualificationService() {
		return labDetailedInstructorQualificationService;
	}

	/**
	 * Sets the lab detailed instructor qualification remote service.
	 *
	 * @param labDetailedInstructorQualificationService the lab detailed instructor qualification remote service
	 */
	public void setlabDetailedInstructorQualificationService(
		com.collaborated.entity.service.labDetailedInstructorQualificationService labDetailedInstructorQualificationService) {
		this.labDetailedInstructorQualificationService = labDetailedInstructorQualificationService;
	}

	/**
	 * Returns the lab detailed instructor qualification persistence.
	 *
	 * @return the lab detailed instructor qualification persistence
	 */
	public labDetailedInstructorQualificationPersistence getlabDetailedInstructorQualificationPersistence() {
		return labDetailedInstructorQualificationPersistence;
	}

	/**
	 * Sets the lab detailed instructor qualification persistence.
	 *
	 * @param labDetailedInstructorQualificationPersistence the lab detailed instructor qualification persistence
	 */
	public void setlabDetailedInstructorQualificationPersistence(
		labDetailedInstructorQualificationPersistence labDetailedInstructorQualificationPersistence) {
		this.labDetailedInstructorQualificationPersistence = labDetailedInstructorQualificationPersistence;
	}

	/**
	 * Returns the lab detailed learning environments local service.
	 *
	 * @return the lab detailed learning environments local service
	 */
	public com.collaborated.entity.service.labDetailedLearningEnvironmentsLocalService getlabDetailedLearningEnvironmentsLocalService() {
		return labDetailedLearningEnvironmentsLocalService;
	}

	/**
	 * Sets the lab detailed learning environments local service.
	 *
	 * @param labDetailedLearningEnvironmentsLocalService the lab detailed learning environments local service
	 */
	public void setlabDetailedLearningEnvironmentsLocalService(
		com.collaborated.entity.service.labDetailedLearningEnvironmentsLocalService labDetailedLearningEnvironmentsLocalService) {
		this.labDetailedLearningEnvironmentsLocalService = labDetailedLearningEnvironmentsLocalService;
	}

	/**
	 * Returns the lab detailed learning environments remote service.
	 *
	 * @return the lab detailed learning environments remote service
	 */
	public com.collaborated.entity.service.labDetailedLearningEnvironmentsService getlabDetailedLearningEnvironmentsService() {
		return labDetailedLearningEnvironmentsService;
	}

	/**
	 * Sets the lab detailed learning environments remote service.
	 *
	 * @param labDetailedLearningEnvironmentsService the lab detailed learning environments remote service
	 */
	public void setlabDetailedLearningEnvironmentsService(
		com.collaborated.entity.service.labDetailedLearningEnvironmentsService labDetailedLearningEnvironmentsService) {
		this.labDetailedLearningEnvironmentsService = labDetailedLearningEnvironmentsService;
	}

	/**
	 * Returns the lab detailed learning environments persistence.
	 *
	 * @return the lab detailed learning environments persistence
	 */
	public labDetailedLearningEnvironmentsPersistence getlabDetailedLearningEnvironmentsPersistence() {
		return labDetailedLearningEnvironmentsPersistence;
	}

	/**
	 * Sets the lab detailed learning environments persistence.
	 *
	 * @param labDetailedLearningEnvironmentsPersistence the lab detailed learning environments persistence
	 */
	public void setlabDetailedLearningEnvironmentsPersistence(
		labDetailedLearningEnvironmentsPersistence labDetailedLearningEnvironmentsPersistence) {
		this.labDetailedLearningEnvironmentsPersistence = labDetailedLearningEnvironmentsPersistence;
	}

	/**
	 * Returns the lab screen project overview local service.
	 *
	 * @return the lab screen project overview local service
	 */
	public com.collaborated.entity.service.labScreenProjectOverviewLocalService getlabScreenProjectOverviewLocalService() {
		return labScreenProjectOverviewLocalService;
	}

	/**
	 * Sets the lab screen project overview local service.
	 *
	 * @param labScreenProjectOverviewLocalService the lab screen project overview local service
	 */
	public void setlabScreenProjectOverviewLocalService(
		com.collaborated.entity.service.labScreenProjectOverviewLocalService labScreenProjectOverviewLocalService) {
		this.labScreenProjectOverviewLocalService = labScreenProjectOverviewLocalService;
	}

	/**
	 * Returns the lab screen project overview remote service.
	 *
	 * @return the lab screen project overview remote service
	 */
	public com.collaborated.entity.service.labScreenProjectOverviewService getlabScreenProjectOverviewService() {
		return labScreenProjectOverviewService;
	}

	/**
	 * Sets the lab screen project overview remote service.
	 *
	 * @param labScreenProjectOverviewService the lab screen project overview remote service
	 */
	public void setlabScreenProjectOverviewService(
		com.collaborated.entity.service.labScreenProjectOverviewService labScreenProjectOverviewService) {
		this.labScreenProjectOverviewService = labScreenProjectOverviewService;
	}

	/**
	 * Returns the lab screen project overview persistence.
	 *
	 * @return the lab screen project overview persistence
	 */
	public labScreenProjectOverviewPersistence getlabScreenProjectOverviewPersistence() {
		return labScreenProjectOverviewPersistence;
	}

	/**
	 * Sets the lab screen project overview persistence.
	 *
	 * @param labScreenProjectOverviewPersistence the lab screen project overview persistence
	 */
	public void setlabScreenProjectOverviewPersistence(
		labScreenProjectOverviewPersistence labScreenProjectOverviewPersistence) {
		this.labScreenProjectOverviewPersistence = labScreenProjectOverviewPersistence;
	}

	/**
	 * Returns the lab screen project partners local service.
	 *
	 * @return the lab screen project partners local service
	 */
	public com.collaborated.entity.service.labScreenProjectPartnersLocalService getlabScreenProjectPartnersLocalService() {
		return labScreenProjectPartnersLocalService;
	}

	/**
	 * Sets the lab screen project partners local service.
	 *
	 * @param labScreenProjectPartnersLocalService the lab screen project partners local service
	 */
	public void setlabScreenProjectPartnersLocalService(
		com.collaborated.entity.service.labScreenProjectPartnersLocalService labScreenProjectPartnersLocalService) {
		this.labScreenProjectPartnersLocalService = labScreenProjectPartnersLocalService;
	}

	/**
	 * Returns the lab screen project partners remote service.
	 *
	 * @return the lab screen project partners remote service
	 */
	public com.collaborated.entity.service.labScreenProjectPartnersService getlabScreenProjectPartnersService() {
		return labScreenProjectPartnersService;
	}

	/**
	 * Sets the lab screen project partners remote service.
	 *
	 * @param labScreenProjectPartnersService the lab screen project partners remote service
	 */
	public void setlabScreenProjectPartnersService(
		com.collaborated.entity.service.labScreenProjectPartnersService labScreenProjectPartnersService) {
		this.labScreenProjectPartnersService = labScreenProjectPartnersService;
	}

	/**
	 * Returns the lab screen project partners persistence.
	 *
	 * @return the lab screen project partners persistence
	 */
	public labScreenProjectPartnersPersistence getlabScreenProjectPartnersPersistence() {
		return labScreenProjectPartnersPersistence;
	}

	/**
	 * Sets the lab screen project partners persistence.
	 *
	 * @param labScreenProjectPartnersPersistence the lab screen project partners persistence
	 */
	public void setlabScreenProjectPartnersPersistence(
		labScreenProjectPartnersPersistence labScreenProjectPartnersPersistence) {
		this.labScreenProjectPartnersPersistence = labScreenProjectPartnersPersistence;
	}

	/**
	 * Returns the lab screen task local service.
	 *
	 * @return the lab screen task local service
	 */
	public com.collaborated.entity.service.labScreenTaskLocalService getlabScreenTaskLocalService() {
		return labScreenTaskLocalService;
	}

	/**
	 * Sets the lab screen task local service.
	 *
	 * @param labScreenTaskLocalService the lab screen task local service
	 */
	public void setlabScreenTaskLocalService(
		com.collaborated.entity.service.labScreenTaskLocalService labScreenTaskLocalService) {
		this.labScreenTaskLocalService = labScreenTaskLocalService;
	}

	/**
	 * Returns the lab screen task remote service.
	 *
	 * @return the lab screen task remote service
	 */
	public com.collaborated.entity.service.labScreenTaskService getlabScreenTaskService() {
		return labScreenTaskService;
	}

	/**
	 * Sets the lab screen task remote service.
	 *
	 * @param labScreenTaskService the lab screen task remote service
	 */
	public void setlabScreenTaskService(
		com.collaborated.entity.service.labScreenTaskService labScreenTaskService) {
		this.labScreenTaskService = labScreenTaskService;
	}

	/**
	 * Returns the lab screen task persistence.
	 *
	 * @return the lab screen task persistence
	 */
	public labScreenTaskPersistence getlabScreenTaskPersistence() {
		return labScreenTaskPersistence;
	}

	/**
	 * Sets the lab screen task persistence.
	 *
	 * @param labScreenTaskPersistence the lab screen task persistence
	 */
	public void setlabScreenTaskPersistence(
		labScreenTaskPersistence labScreenTaskPersistence) {
		this.labScreenTaskPersistence = labScreenTaskPersistence;
	}

	/**
	 * Returns the language preferences local service.
	 *
	 * @return the language preferences local service
	 */
	public com.collaborated.entity.service.languagePreferencesLocalService getlanguagePreferencesLocalService() {
		return languagePreferencesLocalService;
	}

	/**
	 * Sets the language preferences local service.
	 *
	 * @param languagePreferencesLocalService the language preferences local service
	 */
	public void setlanguagePreferencesLocalService(
		com.collaborated.entity.service.languagePreferencesLocalService languagePreferencesLocalService) {
		this.languagePreferencesLocalService = languagePreferencesLocalService;
	}

	/**
	 * Returns the language preferences remote service.
	 *
	 * @return the language preferences remote service
	 */
	public com.collaborated.entity.service.languagePreferencesService getlanguagePreferencesService() {
		return languagePreferencesService;
	}

	/**
	 * Sets the language preferences remote service.
	 *
	 * @param languagePreferencesService the language preferences remote service
	 */
	public void setlanguagePreferencesService(
		com.collaborated.entity.service.languagePreferencesService languagePreferencesService) {
		this.languagePreferencesService = languagePreferencesService;
	}

	/**
	 * Returns the language preferences persistence.
	 *
	 * @return the language preferences persistence
	 */
	public languagePreferencesPersistence getlanguagePreferencesPersistence() {
		return languagePreferencesPersistence;
	}

	/**
	 * Sets the language preferences persistence.
	 *
	 * @param languagePreferencesPersistence the language preferences persistence
	 */
	public void setlanguagePreferencesPersistence(
		languagePreferencesPersistence languagePreferencesPersistence) {
		this.languagePreferencesPersistence = languagePreferencesPersistence;
	}

	/**
	 * Returns the profile areaofinterest local service.
	 *
	 * @return the profile areaofinterest local service
	 */
	public com.collaborated.entity.service.profileAreaofinterestLocalService getprofileAreaofinterestLocalService() {
		return profileAreaofinterestLocalService;
	}

	/**
	 * Sets the profile areaofinterest local service.
	 *
	 * @param profileAreaofinterestLocalService the profile areaofinterest local service
	 */
	public void setprofileAreaofinterestLocalService(
		com.collaborated.entity.service.profileAreaofinterestLocalService profileAreaofinterestLocalService) {
		this.profileAreaofinterestLocalService = profileAreaofinterestLocalService;
	}

	/**
	 * Returns the profile areaofinterest remote service.
	 *
	 * @return the profile areaofinterest remote service
	 */
	public com.collaborated.entity.service.profileAreaofinterestService getprofileAreaofinterestService() {
		return profileAreaofinterestService;
	}

	/**
	 * Sets the profile areaofinterest remote service.
	 *
	 * @param profileAreaofinterestService the profile areaofinterest remote service
	 */
	public void setprofileAreaofinterestService(
		com.collaborated.entity.service.profileAreaofinterestService profileAreaofinterestService) {
		this.profileAreaofinterestService = profileAreaofinterestService;
	}

	/**
	 * Returns the profile areaofinterest persistence.
	 *
	 * @return the profile areaofinterest persistence
	 */
	public profileAreaofinterestPersistence getprofileAreaofinterestPersistence() {
		return profileAreaofinterestPersistence;
	}

	/**
	 * Sets the profile areaofinterest persistence.
	 *
	 * @param profileAreaofinterestPersistence the profile areaofinterest persistence
	 */
	public void setprofileAreaofinterestPersistence(
		profileAreaofinterestPersistence profileAreaofinterestPersistence) {
		this.profileAreaofinterestPersistence = profileAreaofinterestPersistence;
	}

	/**
	 * Returns the project discussion local service.
	 *
	 * @return the project discussion local service
	 */
	public com.collaborated.entity.service.projectDiscussionLocalService getprojectDiscussionLocalService() {
		return projectDiscussionLocalService;
	}

	/**
	 * Sets the project discussion local service.
	 *
	 * @param projectDiscussionLocalService the project discussion local service
	 */
	public void setprojectDiscussionLocalService(
		com.collaborated.entity.service.projectDiscussionLocalService projectDiscussionLocalService) {
		this.projectDiscussionLocalService = projectDiscussionLocalService;
	}

	/**
	 * Returns the project discussion remote service.
	 *
	 * @return the project discussion remote service
	 */
	public com.collaborated.entity.service.projectDiscussionService getprojectDiscussionService() {
		return projectDiscussionService;
	}

	/**
	 * Sets the project discussion remote service.
	 *
	 * @param projectDiscussionService the project discussion remote service
	 */
	public void setprojectDiscussionService(
		com.collaborated.entity.service.projectDiscussionService projectDiscussionService) {
		this.projectDiscussionService = projectDiscussionService;
	}

	/**
	 * Returns the project discussion persistence.
	 *
	 * @return the project discussion persistence
	 */
	public projectDiscussionPersistence getprojectDiscussionPersistence() {
		return projectDiscussionPersistence;
	}

	/**
	 * Sets the project discussion persistence.
	 *
	 * @param projectDiscussionPersistence the project discussion persistence
	 */
	public void setprojectDiscussionPersistence(
		projectDiscussionPersistence projectDiscussionPersistence) {
		this.projectDiscussionPersistence = projectDiscussionPersistence;
	}

	/**
	 * Returns the project files upload local service.
	 *
	 * @return the project files upload local service
	 */
	public com.collaborated.entity.service.projectFilesUploadLocalService getprojectFilesUploadLocalService() {
		return projectFilesUploadLocalService;
	}

	/**
	 * Sets the project files upload local service.
	 *
	 * @param projectFilesUploadLocalService the project files upload local service
	 */
	public void setprojectFilesUploadLocalService(
		com.collaborated.entity.service.projectFilesUploadLocalService projectFilesUploadLocalService) {
		this.projectFilesUploadLocalService = projectFilesUploadLocalService;
	}

	/**
	 * Returns the project files upload remote service.
	 *
	 * @return the project files upload remote service
	 */
	public projectFilesUploadService getprojectFilesUploadService() {
		return projectFilesUploadService;
	}

	/**
	 * Sets the project files upload remote service.
	 *
	 * @param projectFilesUploadService the project files upload remote service
	 */
	public void setprojectFilesUploadService(
		projectFilesUploadService projectFilesUploadService) {
		this.projectFilesUploadService = projectFilesUploadService;
	}

	/**
	 * Returns the project files upload persistence.
	 *
	 * @return the project files upload persistence
	 */
	public projectFilesUploadPersistence getprojectFilesUploadPersistence() {
		return projectFilesUploadPersistence;
	}

	/**
	 * Sets the project files upload persistence.
	 *
	 * @param projectFilesUploadPersistence the project files upload persistence
	 */
	public void setprojectFilesUploadPersistence(
		projectFilesUploadPersistence projectFilesUploadPersistence) {
		this.projectFilesUploadPersistence = projectFilesUploadPersistence;
	}

	/**
	 * Returns the project folder upload local service.
	 *
	 * @return the project folder upload local service
	 */
	public com.collaborated.entity.service.projectFolderUploadLocalService getprojectFolderUploadLocalService() {
		return projectFolderUploadLocalService;
	}

	/**
	 * Sets the project folder upload local service.
	 *
	 * @param projectFolderUploadLocalService the project folder upload local service
	 */
	public void setprojectFolderUploadLocalService(
		com.collaborated.entity.service.projectFolderUploadLocalService projectFolderUploadLocalService) {
		this.projectFolderUploadLocalService = projectFolderUploadLocalService;
	}

	/**
	 * Returns the project folder upload remote service.
	 *
	 * @return the project folder upload remote service
	 */
	public com.collaborated.entity.service.projectFolderUploadService getprojectFolderUploadService() {
		return projectFolderUploadService;
	}

	/**
	 * Sets the project folder upload remote service.
	 *
	 * @param projectFolderUploadService the project folder upload remote service
	 */
	public void setprojectFolderUploadService(
		com.collaborated.entity.service.projectFolderUploadService projectFolderUploadService) {
		this.projectFolderUploadService = projectFolderUploadService;
	}

	/**
	 * Returns the project folder upload persistence.
	 *
	 * @return the project folder upload persistence
	 */
	public projectFolderUploadPersistence getprojectFolderUploadPersistence() {
		return projectFolderUploadPersistence;
	}

	/**
	 * Sets the project folder upload persistence.
	 *
	 * @param projectFolderUploadPersistence the project folder upload persistence
	 */
	public void setprojectFolderUploadPersistence(
		projectFolderUploadPersistence projectFolderUploadPersistence) {
		this.projectFolderUploadPersistence = projectFolderUploadPersistence;
	}

	/**
	 * Returns the project invite tracking local service.
	 *
	 * @return the project invite tracking local service
	 */
	public com.collaborated.entity.service.projectInviteTrackingLocalService getprojectInviteTrackingLocalService() {
		return projectInviteTrackingLocalService;
	}

	/**
	 * Sets the project invite tracking local service.
	 *
	 * @param projectInviteTrackingLocalService the project invite tracking local service
	 */
	public void setprojectInviteTrackingLocalService(
		com.collaborated.entity.service.projectInviteTrackingLocalService projectInviteTrackingLocalService) {
		this.projectInviteTrackingLocalService = projectInviteTrackingLocalService;
	}

	/**
	 * Returns the project invite tracking remote service.
	 *
	 * @return the project invite tracking remote service
	 */
	public com.collaborated.entity.service.projectInviteTrackingService getprojectInviteTrackingService() {
		return projectInviteTrackingService;
	}

	/**
	 * Sets the project invite tracking remote service.
	 *
	 * @param projectInviteTrackingService the project invite tracking remote service
	 */
	public void setprojectInviteTrackingService(
		com.collaborated.entity.service.projectInviteTrackingService projectInviteTrackingService) {
		this.projectInviteTrackingService = projectInviteTrackingService;
	}

	/**
	 * Returns the project invite tracking persistence.
	 *
	 * @return the project invite tracking persistence
	 */
	public projectInviteTrackingPersistence getprojectInviteTrackingPersistence() {
		return projectInviteTrackingPersistence;
	}

	/**
	 * Sets the project invite tracking persistence.
	 *
	 * @param projectInviteTrackingPersistence the project invite tracking persistence
	 */
	public void setprojectInviteTrackingPersistence(
		projectInviteTrackingPersistence projectInviteTrackingPersistence) {
		this.projectInviteTrackingPersistence = projectInviteTrackingPersistence;
	}

	/**
	 * Returns the user credential local service.
	 *
	 * @return the user credential local service
	 */
	public com.collaborated.entity.service.userCredentialLocalService getuserCredentialLocalService() {
		return userCredentialLocalService;
	}

	/**
	 * Sets the user credential local service.
	 *
	 * @param userCredentialLocalService the user credential local service
	 */
	public void setuserCredentialLocalService(
		com.collaborated.entity.service.userCredentialLocalService userCredentialLocalService) {
		this.userCredentialLocalService = userCredentialLocalService;
	}

	/**
	 * Returns the user credential remote service.
	 *
	 * @return the user credential remote service
	 */
	public com.collaborated.entity.service.userCredentialService getuserCredentialService() {
		return userCredentialService;
	}

	/**
	 * Sets the user credential remote service.
	 *
	 * @param userCredentialService the user credential remote service
	 */
	public void setuserCredentialService(
		com.collaborated.entity.service.userCredentialService userCredentialService) {
		this.userCredentialService = userCredentialService;
	}

	/**
	 * Returns the user credential persistence.
	 *
	 * @return the user credential persistence
	 */
	public userCredentialPersistence getuserCredentialPersistence() {
		return userCredentialPersistence;
	}

	/**
	 * Sets the user credential persistence.
	 *
	 * @param userCredentialPersistence the user credential persistence
	 */
	public void setuserCredentialPersistence(
		userCredentialPersistence userCredentialPersistence) {
		this.userCredentialPersistence = userCredentialPersistence;
	}

	/**
	 * Returns the user institution profile details local service.
	 *
	 * @return the user institution profile details local service
	 */
	public com.collaborated.entity.service.userInstitutionProfileDetailsLocalService getuserInstitutionProfileDetailsLocalService() {
		return userInstitutionProfileDetailsLocalService;
	}

	/**
	 * Sets the user institution profile details local service.
	 *
	 * @param userInstitutionProfileDetailsLocalService the user institution profile details local service
	 */
	public void setuserInstitutionProfileDetailsLocalService(
		com.collaborated.entity.service.userInstitutionProfileDetailsLocalService userInstitutionProfileDetailsLocalService) {
		this.userInstitutionProfileDetailsLocalService = userInstitutionProfileDetailsLocalService;
	}

	/**
	 * Returns the user institution profile details remote service.
	 *
	 * @return the user institution profile details remote service
	 */
	public com.collaborated.entity.service.userInstitutionProfileDetailsService getuserInstitutionProfileDetailsService() {
		return userInstitutionProfileDetailsService;
	}

	/**
	 * Sets the user institution profile details remote service.
	 *
	 * @param userInstitutionProfileDetailsService the user institution profile details remote service
	 */
	public void setuserInstitutionProfileDetailsService(
		com.collaborated.entity.service.userInstitutionProfileDetailsService userInstitutionProfileDetailsService) {
		this.userInstitutionProfileDetailsService = userInstitutionProfileDetailsService;
	}

	/**
	 * Returns the user institution profile details persistence.
	 *
	 * @return the user institution profile details persistence
	 */
	public userInstitutionProfileDetailsPersistence getuserInstitutionProfileDetailsPersistence() {
		return userInstitutionProfileDetailsPersistence;
	}

	/**
	 * Sets the user institution profile details persistence.
	 *
	 * @param userInstitutionProfileDetailsPersistence the user institution profile details persistence
	 */
	public void setuserInstitutionProfileDetailsPersistence(
		userInstitutionProfileDetailsPersistence userInstitutionProfileDetailsPersistence) {
		this.userInstitutionProfileDetailsPersistence = userInstitutionProfileDetailsPersistence;
	}

	/**
	 * Returns the user institution profile sub details local service.
	 *
	 * @return the user institution profile sub details local service
	 */
	public com.collaborated.entity.service.userInstitutionProfileSubDetailsLocalService getuserInstitutionProfileSubDetailsLocalService() {
		return userInstitutionProfileSubDetailsLocalService;
	}

	/**
	 * Sets the user institution profile sub details local service.
	 *
	 * @param userInstitutionProfileSubDetailsLocalService the user institution profile sub details local service
	 */
	public void setuserInstitutionProfileSubDetailsLocalService(
		com.collaborated.entity.service.userInstitutionProfileSubDetailsLocalService userInstitutionProfileSubDetailsLocalService) {
		this.userInstitutionProfileSubDetailsLocalService = userInstitutionProfileSubDetailsLocalService;
	}

	/**
	 * Returns the user institution profile sub details remote service.
	 *
	 * @return the user institution profile sub details remote service
	 */
	public com.collaborated.entity.service.userInstitutionProfileSubDetailsService getuserInstitutionProfileSubDetailsService() {
		return userInstitutionProfileSubDetailsService;
	}

	/**
	 * Sets the user institution profile sub details remote service.
	 *
	 * @param userInstitutionProfileSubDetailsService the user institution profile sub details remote service
	 */
	public void setuserInstitutionProfileSubDetailsService(
		com.collaborated.entity.service.userInstitutionProfileSubDetailsService userInstitutionProfileSubDetailsService) {
		this.userInstitutionProfileSubDetailsService = userInstitutionProfileSubDetailsService;
	}

	/**
	 * Returns the user institution profile sub details persistence.
	 *
	 * @return the user institution profile sub details persistence
	 */
	public userInstitutionProfileSubDetailsPersistence getuserInstitutionProfileSubDetailsPersistence() {
		return userInstitutionProfileSubDetailsPersistence;
	}

	/**
	 * Sets the user institution profile sub details persistence.
	 *
	 * @param userInstitutionProfileSubDetailsPersistence the user institution profile sub details persistence
	 */
	public void setuserInstitutionProfileSubDetailsPersistence(
		userInstitutionProfileSubDetailsPersistence userInstitutionProfileSubDetailsPersistence) {
		this.userInstitutionProfileSubDetailsPersistence = userInstitutionProfileSubDetailsPersistence;
	}

	/**
	 * Returns the user professional bio local service.
	 *
	 * @return the user professional bio local service
	 */
	public com.collaborated.entity.service.userProfessionalBioLocalService getuserProfessionalBioLocalService() {
		return userProfessionalBioLocalService;
	}

	/**
	 * Sets the user professional bio local service.
	 *
	 * @param userProfessionalBioLocalService the user professional bio local service
	 */
	public void setuserProfessionalBioLocalService(
		com.collaborated.entity.service.userProfessionalBioLocalService userProfessionalBioLocalService) {
		this.userProfessionalBioLocalService = userProfessionalBioLocalService;
	}

	/**
	 * Returns the user professional bio remote service.
	 *
	 * @return the user professional bio remote service
	 */
	public com.collaborated.entity.service.userProfessionalBioService getuserProfessionalBioService() {
		return userProfessionalBioService;
	}

	/**
	 * Sets the user professional bio remote service.
	 *
	 * @param userProfessionalBioService the user professional bio remote service
	 */
	public void setuserProfessionalBioService(
		com.collaborated.entity.service.userProfessionalBioService userProfessionalBioService) {
		this.userProfessionalBioService = userProfessionalBioService;
	}

	/**
	 * Returns the user professional bio persistence.
	 *
	 * @return the user professional bio persistence
	 */
	public userProfessionalBioPersistence getuserProfessionalBioPersistence() {
		return userProfessionalBioPersistence;
	}

	/**
	 * Sets the user professional bio persistence.
	 *
	 * @param userProfessionalBioPersistence the user professional bio persistence
	 */
	public void setuserProfessionalBioPersistence(
		userProfessionalBioPersistence userProfessionalBioPersistence) {
		this.userProfessionalBioPersistence = userProfessionalBioPersistence;
	}

	/**
	 * Returns the user profile image local service.
	 *
	 * @return the user profile image local service
	 */
	public com.collaborated.entity.service.userProfileImageLocalService getuserProfileImageLocalService() {
		return userProfileImageLocalService;
	}

	/**
	 * Sets the user profile image local service.
	 *
	 * @param userProfileImageLocalService the user profile image local service
	 */
	public void setuserProfileImageLocalService(
		com.collaborated.entity.service.userProfileImageLocalService userProfileImageLocalService) {
		this.userProfileImageLocalService = userProfileImageLocalService;
	}

	/**
	 * Returns the user profile image remote service.
	 *
	 * @return the user profile image remote service
	 */
	public com.collaborated.entity.service.userProfileImageService getuserProfileImageService() {
		return userProfileImageService;
	}

	/**
	 * Sets the user profile image remote service.
	 *
	 * @param userProfileImageService the user profile image remote service
	 */
	public void setuserProfileImageService(
		com.collaborated.entity.service.userProfileImageService userProfileImageService) {
		this.userProfileImageService = userProfileImageService;
	}

	/**
	 * Returns the user profile image persistence.
	 *
	 * @return the user profile image persistence
	 */
	public userProfileImagePersistence getuserProfileImagePersistence() {
		return userProfileImagePersistence;
	}

	/**
	 * Sets the user profile image persistence.
	 *
	 * @param userProfileImagePersistence the user profile image persistence
	 */
	public void setuserProfileImagePersistence(
		userProfileImagePersistence userProfileImagePersistence) {
		this.userProfileImagePersistence = userProfileImagePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return projectFilesUploadService.class.getName();
	}

	protected Class<?> getModelClass() {
		return projectFilesUpload.class;
	}

	protected String getModelClassName() {
		return projectFilesUpload.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = projectFilesUploadPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.collaborated.entity.service.commonWebsserviceAPILocalService.class)
	protected com.collaborated.entity.service.commonWebsserviceAPILocalService commonWebsserviceAPILocalService;
	@BeanReference(type = com.collaborated.entity.service.commonWebsserviceAPIService.class)
	protected com.collaborated.entity.service.commonWebsserviceAPIService commonWebsserviceAPIService;
	@BeanReference(type = commonWebsserviceAPIPersistence.class)
	protected commonWebsserviceAPIPersistence commonWebsserviceAPIPersistence;
	@BeanReference(type = com.collaborated.entity.service.communicationPreferencesLocalService.class)
	protected com.collaborated.entity.service.communicationPreferencesLocalService communicationPreferencesLocalService;
	@BeanReference(type = com.collaborated.entity.service.communicationPreferencesService.class)
	protected com.collaborated.entity.service.communicationPreferencesService communicationPreferencesService;
	@BeanReference(type = communicationPreferencesPersistence.class)
	protected communicationPreferencesPersistence communicationPreferencesPersistence;
	@BeanReference(type = com.collaborated.entity.service.Custom_CalendarLocalService.class)
	protected com.collaborated.entity.service.Custom_CalendarLocalService custom_CalendarLocalService;
	@BeanReference(type = com.collaborated.entity.service.Custom_CalendarService.class)
	protected com.collaborated.entity.service.Custom_CalendarService custom_CalendarService;
	@BeanReference(type = Custom_CalendarPersistence.class)
	protected Custom_CalendarPersistence custom_CalendarPersistence;
	@BeanReference(type = com.collaborated.entity.service.Custom_WorkflowLocalService.class)
	protected com.collaborated.entity.service.Custom_WorkflowLocalService custom_WorkflowLocalService;
	@BeanReference(type = com.collaborated.entity.service.Custom_WorkflowService.class)
	protected com.collaborated.entity.service.Custom_WorkflowService custom_WorkflowService;
	@BeanReference(type = Custom_WorkflowPersistence.class)
	protected Custom_WorkflowPersistence custom_WorkflowPersistence;
	@BeanReference(type = com.collaborated.entity.service.Custom_Workflow_CompletedLocalService.class)
	protected com.collaborated.entity.service.Custom_Workflow_CompletedLocalService custom_Workflow_CompletedLocalService;
	@BeanReference(type = com.collaborated.entity.service.Custom_Workflow_CompletedService.class)
	protected com.collaborated.entity.service.Custom_Workflow_CompletedService custom_Workflow_CompletedService;
	@BeanReference(type = Custom_Workflow_CompletedPersistence.class)
	protected Custom_Workflow_CompletedPersistence custom_Workflow_CompletedPersistence;
	@BeanReference(type = com.collaborated.entity.service.Custom_Workflow_TaskLocalService.class)
	protected com.collaborated.entity.service.Custom_Workflow_TaskLocalService custom_Workflow_TaskLocalService;
	@BeanReference(type = com.collaborated.entity.service.Custom_Workflow_TaskService.class)
	protected com.collaborated.entity.service.Custom_Workflow_TaskService custom_Workflow_TaskService;
	@BeanReference(type = Custom_Workflow_TaskPersistence.class)
	protected Custom_Workflow_TaskPersistence custom_Workflow_TaskPersistence;
	@BeanReference(type = com.collaborated.entity.service.Custom_Workflow_TransitionLocalService.class)
	protected com.collaborated.entity.service.Custom_Workflow_TransitionLocalService custom_Workflow_TransitionLocalService;
	@BeanReference(type = com.collaborated.entity.service.Custom_Workflow_TransitionService.class)
	protected com.collaborated.entity.service.Custom_Workflow_TransitionService custom_Workflow_TransitionService;
	@BeanReference(type = Custom_Workflow_TransitionPersistence.class)
	protected Custom_Workflow_TransitionPersistence custom_Workflow_TransitionPersistence;
	@BeanReference(type = com.collaborated.entity.service.Custom_WorkflowLogLocalService.class)
	protected com.collaborated.entity.service.Custom_WorkflowLogLocalService custom_WorkflowLogLocalService;
	@BeanReference(type = com.collaborated.entity.service.Custom_WorkflowLogService.class)
	protected com.collaborated.entity.service.Custom_WorkflowLogService custom_WorkflowLogService;
	@BeanReference(type = Custom_WorkflowLogPersistence.class)
	protected Custom_WorkflowLogPersistence custom_WorkflowLogPersistence;
	@BeanReference(type = com.collaborated.entity.service.labDetailedActivityTableLocalService.class)
	protected com.collaborated.entity.service.labDetailedActivityTableLocalService labDetailedActivityTableLocalService;
	@BeanReference(type = com.collaborated.entity.service.labDetailedActivityTableService.class)
	protected com.collaborated.entity.service.labDetailedActivityTableService labDetailedActivityTableService;
	@BeanReference(type = labDetailedActivityTablePersistence.class)
	protected labDetailedActivityTablePersistence labDetailedActivityTablePersistence;
	@BeanReference(type = com.collaborated.entity.service.labDetailedCourseHoursLocalService.class)
	protected com.collaborated.entity.service.labDetailedCourseHoursLocalService labDetailedCourseHoursLocalService;
	@BeanReference(type = com.collaborated.entity.service.labDetailedCourseHoursService.class)
	protected com.collaborated.entity.service.labDetailedCourseHoursService labDetailedCourseHoursService;
	@BeanReference(type = labDetailedCourseHoursPersistence.class)
	protected labDetailedCourseHoursPersistence labDetailedCourseHoursPersistence;
	@BeanReference(type = com.collaborated.entity.service.labDetailedCourseIdentificationLocalService.class)
	protected com.collaborated.entity.service.labDetailedCourseIdentificationLocalService labDetailedCourseIdentificationLocalService;
	@BeanReference(type = com.collaborated.entity.service.labDetailedCourseIdentificationService.class)
	protected com.collaborated.entity.service.labDetailedCourseIdentificationService labDetailedCourseIdentificationService;
	@BeanReference(type = labDetailedCourseIdentificationPersistence.class)
	protected labDetailedCourseIdentificationPersistence labDetailedCourseIdentificationPersistence;
	@BeanReference(type = com.collaborated.entity.service.labDetailedCourseObjectivesLocalService.class)
	protected com.collaborated.entity.service.labDetailedCourseObjectivesLocalService labDetailedCourseObjectivesLocalService;
	@BeanReference(type = com.collaborated.entity.service.labDetailedCourseObjectivesService.class)
	protected com.collaborated.entity.service.labDetailedCourseObjectivesService labDetailedCourseObjectivesService;
	@BeanReference(type = labDetailedCourseObjectivesPersistence.class)
	protected labDetailedCourseObjectivesPersistence labDetailedCourseObjectivesPersistence;
	@BeanReference(type = com.collaborated.entity.service.labDetailedCourseResourcesLocalService.class)
	protected com.collaborated.entity.service.labDetailedCourseResourcesLocalService labDetailedCourseResourcesLocalService;
	@BeanReference(type = com.collaborated.entity.service.labDetailedCourseResourcesService.class)
	protected com.collaborated.entity.service.labDetailedCourseResourcesService labDetailedCourseResourcesService;
	@BeanReference(type = labDetailedCourseResourcesPersistence.class)
	protected labDetailedCourseResourcesPersistence labDetailedCourseResourcesPersistence;
	@BeanReference(type = com.collaborated.entity.service.labDetailedCourseTopicsLocalService.class)
	protected com.collaborated.entity.service.labDetailedCourseTopicsLocalService labDetailedCourseTopicsLocalService;
	@BeanReference(type = com.collaborated.entity.service.labDetailedCourseTopicsService.class)
	protected com.collaborated.entity.service.labDetailedCourseTopicsService labDetailedCourseTopicsService;
	@BeanReference(type = labDetailedCourseTopicsPersistence.class)
	protected labDetailedCourseTopicsPersistence labDetailedCourseTopicsPersistence;
	@BeanReference(type = com.collaborated.entity.service.labDetailedInstructorQualificationLocalService.class)
	protected com.collaborated.entity.service.labDetailedInstructorQualificationLocalService labDetailedInstructorQualificationLocalService;
	@BeanReference(type = com.collaborated.entity.service.labDetailedInstructorQualificationService.class)
	protected com.collaborated.entity.service.labDetailedInstructorQualificationService labDetailedInstructorQualificationService;
	@BeanReference(type = labDetailedInstructorQualificationPersistence.class)
	protected labDetailedInstructorQualificationPersistence labDetailedInstructorQualificationPersistence;
	@BeanReference(type = com.collaborated.entity.service.labDetailedLearningEnvironmentsLocalService.class)
	protected com.collaborated.entity.service.labDetailedLearningEnvironmentsLocalService labDetailedLearningEnvironmentsLocalService;
	@BeanReference(type = com.collaborated.entity.service.labDetailedLearningEnvironmentsService.class)
	protected com.collaborated.entity.service.labDetailedLearningEnvironmentsService labDetailedLearningEnvironmentsService;
	@BeanReference(type = labDetailedLearningEnvironmentsPersistence.class)
	protected labDetailedLearningEnvironmentsPersistence labDetailedLearningEnvironmentsPersistence;
	@BeanReference(type = com.collaborated.entity.service.labScreenProjectOverviewLocalService.class)
	protected com.collaborated.entity.service.labScreenProjectOverviewLocalService labScreenProjectOverviewLocalService;
	@BeanReference(type = com.collaborated.entity.service.labScreenProjectOverviewService.class)
	protected com.collaborated.entity.service.labScreenProjectOverviewService labScreenProjectOverviewService;
	@BeanReference(type = labScreenProjectOverviewPersistence.class)
	protected labScreenProjectOverviewPersistence labScreenProjectOverviewPersistence;
	@BeanReference(type = com.collaborated.entity.service.labScreenProjectPartnersLocalService.class)
	protected com.collaborated.entity.service.labScreenProjectPartnersLocalService labScreenProjectPartnersLocalService;
	@BeanReference(type = com.collaborated.entity.service.labScreenProjectPartnersService.class)
	protected com.collaborated.entity.service.labScreenProjectPartnersService labScreenProjectPartnersService;
	@BeanReference(type = labScreenProjectPartnersPersistence.class)
	protected labScreenProjectPartnersPersistence labScreenProjectPartnersPersistence;
	@BeanReference(type = com.collaborated.entity.service.labScreenTaskLocalService.class)
	protected com.collaborated.entity.service.labScreenTaskLocalService labScreenTaskLocalService;
	@BeanReference(type = com.collaborated.entity.service.labScreenTaskService.class)
	protected com.collaborated.entity.service.labScreenTaskService labScreenTaskService;
	@BeanReference(type = labScreenTaskPersistence.class)
	protected labScreenTaskPersistence labScreenTaskPersistence;
	@BeanReference(type = com.collaborated.entity.service.languagePreferencesLocalService.class)
	protected com.collaborated.entity.service.languagePreferencesLocalService languagePreferencesLocalService;
	@BeanReference(type = com.collaborated.entity.service.languagePreferencesService.class)
	protected com.collaborated.entity.service.languagePreferencesService languagePreferencesService;
	@BeanReference(type = languagePreferencesPersistence.class)
	protected languagePreferencesPersistence languagePreferencesPersistence;
	@BeanReference(type = com.collaborated.entity.service.profileAreaofinterestLocalService.class)
	protected com.collaborated.entity.service.profileAreaofinterestLocalService profileAreaofinterestLocalService;
	@BeanReference(type = com.collaborated.entity.service.profileAreaofinterestService.class)
	protected com.collaborated.entity.service.profileAreaofinterestService profileAreaofinterestService;
	@BeanReference(type = profileAreaofinterestPersistence.class)
	protected profileAreaofinterestPersistence profileAreaofinterestPersistence;
	@BeanReference(type = com.collaborated.entity.service.projectDiscussionLocalService.class)
	protected com.collaborated.entity.service.projectDiscussionLocalService projectDiscussionLocalService;
	@BeanReference(type = com.collaborated.entity.service.projectDiscussionService.class)
	protected com.collaborated.entity.service.projectDiscussionService projectDiscussionService;
	@BeanReference(type = projectDiscussionPersistence.class)
	protected projectDiscussionPersistence projectDiscussionPersistence;
	@BeanReference(type = com.collaborated.entity.service.projectFilesUploadLocalService.class)
	protected com.collaborated.entity.service.projectFilesUploadLocalService projectFilesUploadLocalService;
	@BeanReference(type = projectFilesUploadService.class)
	protected projectFilesUploadService projectFilesUploadService;
	@BeanReference(type = projectFilesUploadPersistence.class)
	protected projectFilesUploadPersistence projectFilesUploadPersistence;
	@BeanReference(type = com.collaborated.entity.service.projectFolderUploadLocalService.class)
	protected com.collaborated.entity.service.projectFolderUploadLocalService projectFolderUploadLocalService;
	@BeanReference(type = com.collaborated.entity.service.projectFolderUploadService.class)
	protected com.collaborated.entity.service.projectFolderUploadService projectFolderUploadService;
	@BeanReference(type = projectFolderUploadPersistence.class)
	protected projectFolderUploadPersistence projectFolderUploadPersistence;
	@BeanReference(type = com.collaborated.entity.service.projectInviteTrackingLocalService.class)
	protected com.collaborated.entity.service.projectInviteTrackingLocalService projectInviteTrackingLocalService;
	@BeanReference(type = com.collaborated.entity.service.projectInviteTrackingService.class)
	protected com.collaborated.entity.service.projectInviteTrackingService projectInviteTrackingService;
	@BeanReference(type = projectInviteTrackingPersistence.class)
	protected projectInviteTrackingPersistence projectInviteTrackingPersistence;
	@BeanReference(type = com.collaborated.entity.service.userCredentialLocalService.class)
	protected com.collaborated.entity.service.userCredentialLocalService userCredentialLocalService;
	@BeanReference(type = com.collaborated.entity.service.userCredentialService.class)
	protected com.collaborated.entity.service.userCredentialService userCredentialService;
	@BeanReference(type = userCredentialPersistence.class)
	protected userCredentialPersistence userCredentialPersistence;
	@BeanReference(type = com.collaborated.entity.service.userInstitutionProfileDetailsLocalService.class)
	protected com.collaborated.entity.service.userInstitutionProfileDetailsLocalService userInstitutionProfileDetailsLocalService;
	@BeanReference(type = com.collaborated.entity.service.userInstitutionProfileDetailsService.class)
	protected com.collaborated.entity.service.userInstitutionProfileDetailsService userInstitutionProfileDetailsService;
	@BeanReference(type = userInstitutionProfileDetailsPersistence.class)
	protected userInstitutionProfileDetailsPersistence userInstitutionProfileDetailsPersistence;
	@BeanReference(type = com.collaborated.entity.service.userInstitutionProfileSubDetailsLocalService.class)
	protected com.collaborated.entity.service.userInstitutionProfileSubDetailsLocalService userInstitutionProfileSubDetailsLocalService;
	@BeanReference(type = com.collaborated.entity.service.userInstitutionProfileSubDetailsService.class)
	protected com.collaborated.entity.service.userInstitutionProfileSubDetailsService userInstitutionProfileSubDetailsService;
	@BeanReference(type = userInstitutionProfileSubDetailsPersistence.class)
	protected userInstitutionProfileSubDetailsPersistence userInstitutionProfileSubDetailsPersistence;
	@BeanReference(type = com.collaborated.entity.service.userProfessionalBioLocalService.class)
	protected com.collaborated.entity.service.userProfessionalBioLocalService userProfessionalBioLocalService;
	@BeanReference(type = com.collaborated.entity.service.userProfessionalBioService.class)
	protected com.collaborated.entity.service.userProfessionalBioService userProfessionalBioService;
	@BeanReference(type = userProfessionalBioPersistence.class)
	protected userProfessionalBioPersistence userProfessionalBioPersistence;
	@BeanReference(type = com.collaborated.entity.service.userProfileImageLocalService.class)
	protected com.collaborated.entity.service.userProfileImageLocalService userProfileImageLocalService;
	@BeanReference(type = com.collaborated.entity.service.userProfileImageService.class)
	protected com.collaborated.entity.service.userProfileImageService userProfileImageService;
	@BeanReference(type = userProfileImagePersistence.class)
	protected userProfileImagePersistence userProfileImagePersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}