/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.collaborated.entity.model.Custom_WorkflowLog;
import com.collaborated.entity.model.Custom_WorkflowLogModel;
import com.collaborated.entity.model.Custom_WorkflowLogSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Custom_WorkflowLog service. Represents a row in the &quot;collaborated_Custom_WorkflowLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link Custom_WorkflowLogModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Custom_WorkflowLogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Custom_WorkflowLogImpl
 * @see Custom_WorkflowLog
 * @see Custom_WorkflowLogModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class Custom_WorkflowLogModelImpl extends BaseModelImpl<Custom_WorkflowLog>
	implements Custom_WorkflowLogModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a custom_ workflow log model instance should use the {@link Custom_WorkflowLog} interface instead.
	 */
	public static final String TABLE_NAME = "collaborated_Custom_WorkflowLog";
	public static final Object[][] TABLE_COLUMNS = {
			{ "logId", Types.BIGINT },
			{ "trackingId", Types.BIGINT },
			{ "workflowId", Types.BIGINT },
			{ "workflowTaskId", Types.VARCHAR },
			{ "trasitionId", Types.BIGINT },
			{ "logDescription", Types.VARCHAR },
			{ "comments", Types.VARCHAR },
			{ "assigneeClassPK", Types.BIGINT },
			{ "className", Types.VARCHAR },
			{ "assignedDate", Types.TIMESTAMP },
			{ "completedDate", Types.TIMESTAMP },
			{ "createdBy", Types.BIGINT },
			{ "createdDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("logId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("trackingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("workflowId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("workflowTaskId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("trasitionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("logDescription", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("comments", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("assigneeClassPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("className", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("assignedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("completedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table collaborated_Custom_WorkflowLog (logId LONG not null primary key,trackingId LONG,workflowId LONG,workflowTaskId VARCHAR(75) null,trasitionId LONG,logDescription VARCHAR(75) null,comments VARCHAR(75) null,assigneeClassPK LONG,className VARCHAR(75) null,assignedDate DATE null,completedDate DATE null,createdBy LONG,createdDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table collaborated_Custom_WorkflowLog";
	public static final String ORDER_BY_JPQL = " ORDER BY custom_WorkflowLog.logId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY collaborated_Custom_WorkflowLog.logId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.collaborated.entity.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.collaborated.entity.model.Custom_WorkflowLog"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.collaborated.entity.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.collaborated.entity.model.Custom_WorkflowLog"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Custom_WorkflowLog toModel(Custom_WorkflowLogSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Custom_WorkflowLog model = new Custom_WorkflowLogImpl();

		model.setLogId(soapModel.getLogId());
		model.setTrackingId(soapModel.getTrackingId());
		model.setWorkflowId(soapModel.getWorkflowId());
		model.setWorkflowTaskId(soapModel.getWorkflowTaskId());
		model.setTrasitionId(soapModel.getTrasitionId());
		model.setLogDescription(soapModel.getLogDescription());
		model.setComments(soapModel.getComments());
		model.setAssigneeClassPK(soapModel.getAssigneeClassPK());
		model.setClassName(soapModel.getClassName());
		model.setAssignedDate(soapModel.getAssignedDate());
		model.setCompletedDate(soapModel.getCompletedDate());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setCreatedDate(soapModel.getCreatedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Custom_WorkflowLog> toModels(
		Custom_WorkflowLogSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Custom_WorkflowLog> models = new ArrayList<Custom_WorkflowLog>(soapModels.length);

		for (Custom_WorkflowLogSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.collaborated.entity.service.util.ServiceProps.get(
				"lock.expiration.time.com.collaborated.entity.model.Custom_WorkflowLog"));

	public Custom_WorkflowLogModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _logId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLogId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _logId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Custom_WorkflowLog.class;
	}

	@Override
	public String getModelClassName() {
		return Custom_WorkflowLog.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("logId", getLogId());
		attributes.put("trackingId", getTrackingId());
		attributes.put("workflowId", getWorkflowId());
		attributes.put("workflowTaskId", getWorkflowTaskId());
		attributes.put("trasitionId", getTrasitionId());
		attributes.put("logDescription", getLogDescription());
		attributes.put("comments", getComments());
		attributes.put("assigneeClassPK", getAssigneeClassPK());
		attributes.put("className", getClassName());
		attributes.put("assignedDate", getAssignedDate());
		attributes.put("completedDate", getCompletedDate());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("createdDate", getCreatedDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long logId = (Long)attributes.get("logId");

		if (logId != null) {
			setLogId(logId);
		}

		Long trackingId = (Long)attributes.get("trackingId");

		if (trackingId != null) {
			setTrackingId(trackingId);
		}

		Long workflowId = (Long)attributes.get("workflowId");

		if (workflowId != null) {
			setWorkflowId(workflowId);
		}

		String workflowTaskId = (String)attributes.get("workflowTaskId");

		if (workflowTaskId != null) {
			setWorkflowTaskId(workflowTaskId);
		}

		Long trasitionId = (Long)attributes.get("trasitionId");

		if (trasitionId != null) {
			setTrasitionId(trasitionId);
		}

		String logDescription = (String)attributes.get("logDescription");

		if (logDescription != null) {
			setLogDescription(logDescription);
		}

		String comments = (String)attributes.get("comments");

		if (comments != null) {
			setComments(comments);
		}

		Long assigneeClassPK = (Long)attributes.get("assigneeClassPK");

		if (assigneeClassPK != null) {
			setAssigneeClassPK(assigneeClassPK);
		}

		String className = (String)attributes.get("className");

		if (className != null) {
			setClassName(className);
		}

		Date assignedDate = (Date)attributes.get("assignedDate");

		if (assignedDate != null) {
			setAssignedDate(assignedDate);
		}

		Date completedDate = (Date)attributes.get("completedDate");

		if (completedDate != null) {
			setCompletedDate(completedDate);
		}

		Long createdBy = (Long)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}
	}

	@JSON
	@Override
	public long getLogId() {
		return _logId;
	}

	@Override
	public void setLogId(long logId) {
		_logId = logId;
	}

	@JSON
	@Override
	public long getTrackingId() {
		return _trackingId;
	}

	@Override
	public void setTrackingId(long trackingId) {
		_trackingId = trackingId;
	}

	@JSON
	@Override
	public long getWorkflowId() {
		return _workflowId;
	}

	@Override
	public void setWorkflowId(long workflowId) {
		_workflowId = workflowId;
	}

	@JSON
	@Override
	public String getWorkflowTaskId() {
		if (_workflowTaskId == null) {
			return StringPool.BLANK;
		}
		else {
			return _workflowTaskId;
		}
	}

	@Override
	public void setWorkflowTaskId(String workflowTaskId) {
		_workflowTaskId = workflowTaskId;
	}

	@JSON
	@Override
	public long getTrasitionId() {
		return _trasitionId;
	}

	@Override
	public void setTrasitionId(long trasitionId) {
		_trasitionId = trasitionId;
	}

	@JSON
	@Override
	public String getLogDescription() {
		if (_logDescription == null) {
			return StringPool.BLANK;
		}
		else {
			return _logDescription;
		}
	}

	@Override
	public void setLogDescription(String logDescription) {
		_logDescription = logDescription;
	}

	@JSON
	@Override
	public String getComments() {
		if (_comments == null) {
			return StringPool.BLANK;
		}
		else {
			return _comments;
		}
	}

	@Override
	public void setComments(String comments) {
		_comments = comments;
	}

	@JSON
	@Override
	public long getAssigneeClassPK() {
		return _assigneeClassPK;
	}

	@Override
	public void setAssigneeClassPK(long assigneeClassPK) {
		_assigneeClassPK = assigneeClassPK;
	}

	@JSON
	@Override
	public String getClassName() {
		if (_className == null) {
			return StringPool.BLANK;
		}
		else {
			return _className;
		}
	}

	@Override
	public void setClassName(String className) {
		_className = className;
	}

	@JSON
	@Override
	public Date getAssignedDate() {
		return _assignedDate;
	}

	@Override
	public void setAssignedDate(Date assignedDate) {
		_assignedDate = assignedDate;
	}

	@JSON
	@Override
	public Date getCompletedDate() {
		return _completedDate;
	}

	@Override
	public void setCompletedDate(Date completedDate) {
		_completedDate = completedDate;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Custom_WorkflowLog.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Custom_WorkflowLog toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Custom_WorkflowLog)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Custom_WorkflowLogImpl custom_WorkflowLogImpl = new Custom_WorkflowLogImpl();

		custom_WorkflowLogImpl.setLogId(getLogId());
		custom_WorkflowLogImpl.setTrackingId(getTrackingId());
		custom_WorkflowLogImpl.setWorkflowId(getWorkflowId());
		custom_WorkflowLogImpl.setWorkflowTaskId(getWorkflowTaskId());
		custom_WorkflowLogImpl.setTrasitionId(getTrasitionId());
		custom_WorkflowLogImpl.setLogDescription(getLogDescription());
		custom_WorkflowLogImpl.setComments(getComments());
		custom_WorkflowLogImpl.setAssigneeClassPK(getAssigneeClassPK());
		custom_WorkflowLogImpl.setClassName(getClassName());
		custom_WorkflowLogImpl.setAssignedDate(getAssignedDate());
		custom_WorkflowLogImpl.setCompletedDate(getCompletedDate());
		custom_WorkflowLogImpl.setCreatedBy(getCreatedBy());
		custom_WorkflowLogImpl.setCreatedDate(getCreatedDate());

		custom_WorkflowLogImpl.resetOriginalValues();

		return custom_WorkflowLogImpl;
	}

	@Override
	public int compareTo(Custom_WorkflowLog custom_WorkflowLog) {
		long primaryKey = custom_WorkflowLog.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Custom_WorkflowLog)) {
			return false;
		}

		Custom_WorkflowLog custom_WorkflowLog = (Custom_WorkflowLog)obj;

		long primaryKey = custom_WorkflowLog.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Custom_WorkflowLog> toCacheModel() {
		Custom_WorkflowLogCacheModel custom_WorkflowLogCacheModel = new Custom_WorkflowLogCacheModel();

		custom_WorkflowLogCacheModel.logId = getLogId();

		custom_WorkflowLogCacheModel.trackingId = getTrackingId();

		custom_WorkflowLogCacheModel.workflowId = getWorkflowId();

		custom_WorkflowLogCacheModel.workflowTaskId = getWorkflowTaskId();

		String workflowTaskId = custom_WorkflowLogCacheModel.workflowTaskId;

		if ((workflowTaskId != null) && (workflowTaskId.length() == 0)) {
			custom_WorkflowLogCacheModel.workflowTaskId = null;
		}

		custom_WorkflowLogCacheModel.trasitionId = getTrasitionId();

		custom_WorkflowLogCacheModel.logDescription = getLogDescription();

		String logDescription = custom_WorkflowLogCacheModel.logDescription;

		if ((logDescription != null) && (logDescription.length() == 0)) {
			custom_WorkflowLogCacheModel.logDescription = null;
		}

		custom_WorkflowLogCacheModel.comments = getComments();

		String comments = custom_WorkflowLogCacheModel.comments;

		if ((comments != null) && (comments.length() == 0)) {
			custom_WorkflowLogCacheModel.comments = null;
		}

		custom_WorkflowLogCacheModel.assigneeClassPK = getAssigneeClassPK();

		custom_WorkflowLogCacheModel.className = getClassName();

		String className = custom_WorkflowLogCacheModel.className;

		if ((className != null) && (className.length() == 0)) {
			custom_WorkflowLogCacheModel.className = null;
		}

		Date assignedDate = getAssignedDate();

		if (assignedDate != null) {
			custom_WorkflowLogCacheModel.assignedDate = assignedDate.getTime();
		}
		else {
			custom_WorkflowLogCacheModel.assignedDate = Long.MIN_VALUE;
		}

		Date completedDate = getCompletedDate();

		if (completedDate != null) {
			custom_WorkflowLogCacheModel.completedDate = completedDate.getTime();
		}
		else {
			custom_WorkflowLogCacheModel.completedDate = Long.MIN_VALUE;
		}

		custom_WorkflowLogCacheModel.createdBy = getCreatedBy();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			custom_WorkflowLogCacheModel.createdDate = createdDate.getTime();
		}
		else {
			custom_WorkflowLogCacheModel.createdDate = Long.MIN_VALUE;
		}

		return custom_WorkflowLogCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{logId=");
		sb.append(getLogId());
		sb.append(", trackingId=");
		sb.append(getTrackingId());
		sb.append(", workflowId=");
		sb.append(getWorkflowId());
		sb.append(", workflowTaskId=");
		sb.append(getWorkflowTaskId());
		sb.append(", trasitionId=");
		sb.append(getTrasitionId());
		sb.append(", logDescription=");
		sb.append(getLogDescription());
		sb.append(", comments=");
		sb.append(getComments());
		sb.append(", assigneeClassPK=");
		sb.append(getAssigneeClassPK());
		sb.append(", className=");
		sb.append(getClassName());
		sb.append(", assignedDate=");
		sb.append(getAssignedDate());
		sb.append(", completedDate=");
		sb.append(getCompletedDate());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.collaborated.entity.model.Custom_WorkflowLog");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>logId</column-name><column-value><![CDATA[");
		sb.append(getLogId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trackingId</column-name><column-value><![CDATA[");
		sb.append(getTrackingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>workflowId</column-name><column-value><![CDATA[");
		sb.append(getWorkflowId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>workflowTaskId</column-name><column-value><![CDATA[");
		sb.append(getWorkflowTaskId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trasitionId</column-name><column-value><![CDATA[");
		sb.append(getTrasitionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>logDescription</column-name><column-value><![CDATA[");
		sb.append(getLogDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>comments</column-name><column-value><![CDATA[");
		sb.append(getComments());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assigneeClassPK</column-name><column-value><![CDATA[");
		sb.append(getAssigneeClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>className</column-name><column-value><![CDATA[");
		sb.append(getClassName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assignedDate</column-name><column-value><![CDATA[");
		sb.append(getAssignedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>completedDate</column-name><column-value><![CDATA[");
		sb.append(getCompletedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Custom_WorkflowLog.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Custom_WorkflowLog.class
		};
	private long _logId;
	private long _trackingId;
	private long _workflowId;
	private String _workflowTaskId;
	private long _trasitionId;
	private String _logDescription;
	private String _comments;
	private long _assigneeClassPK;
	private String _className;
	private Date _assignedDate;
	private Date _completedDate;
	private long _createdBy;
	private Date _createdDate;
	private Custom_WorkflowLog _escapedModel;
}