/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.collaborated.entity.model.Custom_CalendarInvitees;
import com.collaborated.entity.model.Custom_CalendarInviteesModel;
import com.collaborated.entity.model.Custom_CalendarInviteesSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Custom_CalendarInvitees service. Represents a row in the &quot;collaborated_Custom_CalendarInvitees&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link Custom_CalendarInviteesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Custom_CalendarInviteesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Custom_CalendarInviteesImpl
 * @see Custom_CalendarInvitees
 * @see Custom_CalendarInviteesModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class Custom_CalendarInviteesModelImpl extends BaseModelImpl<Custom_CalendarInvitees>
	implements Custom_CalendarInviteesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a custom_ calendar invitees model instance should use the {@link Custom_CalendarInvitees} interface instead.
	 */
	public static final String TABLE_NAME = "collaborated_Custom_CalendarInvitees";
	public static final Object[][] TABLE_COLUMNS = {
			{ "PK_calendarEventSubId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "PK_calendarEventId", Types.BIGINT },
			{ "inviteeEmailAddress", Types.VARCHAR },
			{ "invitee", Types.BIGINT },
			{ "status", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("PK_calendarEventSubId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("PK_calendarEventId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("inviteeEmailAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("invitee", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table collaborated_Custom_CalendarInvitees (PK_calendarEventSubId LONG not null primary key,groupId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,PK_calendarEventId LONG,inviteeEmailAddress VARCHAR(75) null,invitee LONG,status INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table collaborated_Custom_CalendarInvitees";
	public static final String ORDER_BY_JPQL = " ORDER BY custom_CalendarInvitees.PK_calendarEventSubId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY collaborated_Custom_CalendarInvitees.PK_calendarEventSubId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.collaborated.entity.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.collaborated.entity.model.Custom_CalendarInvitees"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.collaborated.entity.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.collaborated.entity.model.Custom_CalendarInvitees"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Custom_CalendarInvitees toModel(
		Custom_CalendarInviteesSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Custom_CalendarInvitees model = new Custom_CalendarInviteesImpl();

		model.setPK_calendarEventSubId(soapModel.getPK_calendarEventSubId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setPK_calendarEventId(soapModel.getPK_calendarEventId());
		model.setInviteeEmailAddress(soapModel.getInviteeEmailAddress());
		model.setInvitee(soapModel.getInvitee());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Custom_CalendarInvitees> toModels(
		Custom_CalendarInviteesSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Custom_CalendarInvitees> models = new ArrayList<Custom_CalendarInvitees>(soapModels.length);

		for (Custom_CalendarInviteesSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.collaborated.entity.service.util.ServiceProps.get(
				"lock.expiration.time.com.collaborated.entity.model.Custom_CalendarInvitees"));

	public Custom_CalendarInviteesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _PK_calendarEventSubId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPK_calendarEventSubId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PK_calendarEventSubId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Custom_CalendarInvitees.class;
	}

	@Override
	public String getModelClassName() {
		return Custom_CalendarInvitees.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("PK_calendarEventSubId", getPK_calendarEventSubId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("PK_calendarEventId", getPK_calendarEventId());
		attributes.put("inviteeEmailAddress", getInviteeEmailAddress());
		attributes.put("invitee", getInvitee());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long PK_calendarEventSubId = (Long)attributes.get(
				"PK_calendarEventSubId");

		if (PK_calendarEventSubId != null) {
			setPK_calendarEventSubId(PK_calendarEventSubId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long PK_calendarEventId = (Long)attributes.get("PK_calendarEventId");

		if (PK_calendarEventId != null) {
			setPK_calendarEventId(PK_calendarEventId);
		}

		String inviteeEmailAddress = (String)attributes.get(
				"inviteeEmailAddress");

		if (inviteeEmailAddress != null) {
			setInviteeEmailAddress(inviteeEmailAddress);
		}

		Long invitee = (Long)attributes.get("invitee");

		if (invitee != null) {
			setInvitee(invitee);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	@Override
	public long getPK_calendarEventSubId() {
		return _PK_calendarEventSubId;
	}

	@Override
	public void setPK_calendarEventSubId(long PK_calendarEventSubId) {
		_PK_calendarEventSubId = PK_calendarEventSubId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getPK_calendarEventId() {
		return _PK_calendarEventId;
	}

	@Override
	public void setPK_calendarEventId(long PK_calendarEventId) {
		_PK_calendarEventId = PK_calendarEventId;
	}

	@JSON
	@Override
	public String getInviteeEmailAddress() {
		if (_inviteeEmailAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _inviteeEmailAddress;
		}
	}

	@Override
	public void setInviteeEmailAddress(String inviteeEmailAddress) {
		_inviteeEmailAddress = inviteeEmailAddress;
	}

	@JSON
	@Override
	public long getInvitee() {
		return _invitee;
	}

	@Override
	public void setInvitee(long invitee) {
		_invitee = invitee;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Custom_CalendarInvitees.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Custom_CalendarInvitees toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Custom_CalendarInvitees)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Custom_CalendarInviteesImpl custom_CalendarInviteesImpl = new Custom_CalendarInviteesImpl();

		custom_CalendarInviteesImpl.setPK_calendarEventSubId(getPK_calendarEventSubId());
		custom_CalendarInviteesImpl.setGroupId(getGroupId());
		custom_CalendarInviteesImpl.setUserId(getUserId());
		custom_CalendarInviteesImpl.setCreateDate(getCreateDate());
		custom_CalendarInviteesImpl.setModifiedDate(getModifiedDate());
		custom_CalendarInviteesImpl.setPK_calendarEventId(getPK_calendarEventId());
		custom_CalendarInviteesImpl.setInviteeEmailAddress(getInviteeEmailAddress());
		custom_CalendarInviteesImpl.setInvitee(getInvitee());
		custom_CalendarInviteesImpl.setStatus(getStatus());

		custom_CalendarInviteesImpl.resetOriginalValues();

		return custom_CalendarInviteesImpl;
	}

	@Override
	public int compareTo(Custom_CalendarInvitees custom_CalendarInvitees) {
		long primaryKey = custom_CalendarInvitees.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Custom_CalendarInvitees)) {
			return false;
		}

		Custom_CalendarInvitees custom_CalendarInvitees = (Custom_CalendarInvitees)obj;

		long primaryKey = custom_CalendarInvitees.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		Custom_CalendarInviteesModelImpl custom_CalendarInviteesModelImpl = this;

		custom_CalendarInviteesModelImpl._setModifiedDate = false;
	}

	@Override
	public CacheModel<Custom_CalendarInvitees> toCacheModel() {
		Custom_CalendarInviteesCacheModel custom_CalendarInviteesCacheModel = new Custom_CalendarInviteesCacheModel();

		custom_CalendarInviteesCacheModel.PK_calendarEventSubId = getPK_calendarEventSubId();

		custom_CalendarInviteesCacheModel.groupId = getGroupId();

		custom_CalendarInviteesCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			custom_CalendarInviteesCacheModel.createDate = createDate.getTime();
		}
		else {
			custom_CalendarInviteesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			custom_CalendarInviteesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			custom_CalendarInviteesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		custom_CalendarInviteesCacheModel.PK_calendarEventId = getPK_calendarEventId();

		custom_CalendarInviteesCacheModel.inviteeEmailAddress = getInviteeEmailAddress();

		String inviteeEmailAddress = custom_CalendarInviteesCacheModel.inviteeEmailAddress;

		if ((inviteeEmailAddress != null) &&
				(inviteeEmailAddress.length() == 0)) {
			custom_CalendarInviteesCacheModel.inviteeEmailAddress = null;
		}

		custom_CalendarInviteesCacheModel.invitee = getInvitee();

		custom_CalendarInviteesCacheModel.status = getStatus();

		return custom_CalendarInviteesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{PK_calendarEventSubId=");
		sb.append(getPK_calendarEventSubId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", PK_calendarEventId=");
		sb.append(getPK_calendarEventId());
		sb.append(", inviteeEmailAddress=");
		sb.append(getInviteeEmailAddress());
		sb.append(", invitee=");
		sb.append(getInvitee());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.collaborated.entity.model.Custom_CalendarInvitees");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>PK_calendarEventSubId</column-name><column-value><![CDATA[");
		sb.append(getPK_calendarEventSubId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PK_calendarEventId</column-name><column-value><![CDATA[");
		sb.append(getPK_calendarEventId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inviteeEmailAddress</column-name><column-value><![CDATA[");
		sb.append(getInviteeEmailAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>invitee</column-name><column-value><![CDATA[");
		sb.append(getInvitee());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Custom_CalendarInvitees.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Custom_CalendarInvitees.class
		};
	private long _PK_calendarEventSubId;
	private long _groupId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _PK_calendarEventId;
	private String _inviteeEmailAddress;
	private long _invitee;
	private int _status;
	private Custom_CalendarInvitees _escapedModel;
}