/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.collaborated.entity.model.labDetailedCourseResources;
import com.collaborated.entity.model.labDetailedCourseResourcesModel;
import com.collaborated.entity.model.labDetailedCourseResourcesSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the labDetailedCourseResources service. Represents a row in the &quot;collaborated_labDetailedCourseResources&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link labDetailedCourseResourcesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link labDetailedCourseResourcesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see labDetailedCourseResourcesImpl
 * @see labDetailedCourseResources
 * @see labDetailedCourseResourcesModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class labDetailedCourseResourcesModelImpl extends BaseModelImpl<labDetailedCourseResources>
	implements labDetailedCourseResourcesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lab detailed course resources model instance should use the {@link labDetailedCourseResources} interface instead.
	 */
	public static final String TABLE_NAME = "collaborated_labDetailedCourseResources";
	public static final Object[][] TABLE_COLUMNS = {
			{ "PK_courseResourceId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "PK_projectId", Types.BIGINT },
			{ "PK_courseId", Types.BIGINT },
			{ "textbokTitle", Types.VARCHAR },
			{ "publisherName", Types.VARCHAR },
			{ "author", Types.VARCHAR },
			{ "isbn", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("PK_courseResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("PK_projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("PK_courseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("textbokTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("publisherName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("author", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isbn", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table collaborated_labDetailedCourseResources (PK_courseResourceId LONG not null primary key,groupId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,PK_projectId LONG,PK_courseId LONG,textbokTitle VARCHAR(75) null,publisherName VARCHAR(75) null,author VARCHAR(75) null,isbn VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table collaborated_labDetailedCourseResources";
	public static final String ORDER_BY_JPQL = " ORDER BY labDetailedCourseResources.PK_courseResourceId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY collaborated_labDetailedCourseResources.PK_courseResourceId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.collaborated.entity.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.collaborated.entity.model.labDetailedCourseResources"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.collaborated.entity.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.collaborated.entity.model.labDetailedCourseResources"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.collaborated.entity.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.collaborated.entity.model.labDetailedCourseResources"),
			true);
	public static final long PK_COURSEID_COLUMN_BITMASK = 1L;
	public static final long PK_COURSERESOURCEID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static labDetailedCourseResources toModel(
		labDetailedCourseResourcesSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		labDetailedCourseResources model = new labDetailedCourseResourcesImpl();

		model.setPK_courseResourceId(soapModel.getPK_courseResourceId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setPK_projectId(soapModel.getPK_projectId());
		model.setPK_courseId(soapModel.getPK_courseId());
		model.setTextbokTitle(soapModel.getTextbokTitle());
		model.setPublisherName(soapModel.getPublisherName());
		model.setAuthor(soapModel.getAuthor());
		model.setIsbn(soapModel.getIsbn());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<labDetailedCourseResources> toModels(
		labDetailedCourseResourcesSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<labDetailedCourseResources> models = new ArrayList<labDetailedCourseResources>(soapModels.length);

		for (labDetailedCourseResourcesSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.collaborated.entity.service.util.ServiceProps.get(
				"lock.expiration.time.com.collaborated.entity.model.labDetailedCourseResources"));

	public labDetailedCourseResourcesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _PK_courseResourceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPK_courseResourceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PK_courseResourceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return labDetailedCourseResources.class;
	}

	@Override
	public String getModelClassName() {
		return labDetailedCourseResources.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("PK_courseResourceId", getPK_courseResourceId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("PK_projectId", getPK_projectId());
		attributes.put("PK_courseId", getPK_courseId());
		attributes.put("textbokTitle", getTextbokTitle());
		attributes.put("publisherName", getPublisherName());
		attributes.put("author", getAuthor());
		attributes.put("isbn", getIsbn());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long PK_courseResourceId = (Long)attributes.get("PK_courseResourceId");

		if (PK_courseResourceId != null) {
			setPK_courseResourceId(PK_courseResourceId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long PK_projectId = (Long)attributes.get("PK_projectId");

		if (PK_projectId != null) {
			setPK_projectId(PK_projectId);
		}

		Long PK_courseId = (Long)attributes.get("PK_courseId");

		if (PK_courseId != null) {
			setPK_courseId(PK_courseId);
		}

		String textbokTitle = (String)attributes.get("textbokTitle");

		if (textbokTitle != null) {
			setTextbokTitle(textbokTitle);
		}

		String publisherName = (String)attributes.get("publisherName");

		if (publisherName != null) {
			setPublisherName(publisherName);
		}

		String author = (String)attributes.get("author");

		if (author != null) {
			setAuthor(author);
		}

		String isbn = (String)attributes.get("isbn");

		if (isbn != null) {
			setIsbn(isbn);
		}
	}

	@JSON
	@Override
	public long getPK_courseResourceId() {
		return _PK_courseResourceId;
	}

	@Override
	public void setPK_courseResourceId(long PK_courseResourceId) {
		_PK_courseResourceId = PK_courseResourceId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getPK_projectId() {
		return _PK_projectId;
	}

	@Override
	public void setPK_projectId(long PK_projectId) {
		_PK_projectId = PK_projectId;
	}

	@JSON
	@Override
	public long getPK_courseId() {
		return _PK_courseId;
	}

	@Override
	public void setPK_courseId(long PK_courseId) {
		_columnBitmask |= PK_COURSEID_COLUMN_BITMASK;

		if (!_setOriginalPK_courseId) {
			_setOriginalPK_courseId = true;

			_originalPK_courseId = _PK_courseId;
		}

		_PK_courseId = PK_courseId;
	}

	public long getOriginalPK_courseId() {
		return _originalPK_courseId;
	}

	@JSON
	@Override
	public String getTextbokTitle() {
		if (_textbokTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _textbokTitle;
		}
	}

	@Override
	public void setTextbokTitle(String textbokTitle) {
		_textbokTitle = textbokTitle;
	}

	@JSON
	@Override
	public String getPublisherName() {
		if (_publisherName == null) {
			return StringPool.BLANK;
		}
		else {
			return _publisherName;
		}
	}

	@Override
	public void setPublisherName(String publisherName) {
		_publisherName = publisherName;
	}

	@JSON
	@Override
	public String getAuthor() {
		if (_author == null) {
			return StringPool.BLANK;
		}
		else {
			return _author;
		}
	}

	@Override
	public void setAuthor(String author) {
		_author = author;
	}

	@JSON
	@Override
	public String getIsbn() {
		if (_isbn == null) {
			return StringPool.BLANK;
		}
		else {
			return _isbn;
		}
	}

	@Override
	public void setIsbn(String isbn) {
		_isbn = isbn;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			labDetailedCourseResources.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public labDetailedCourseResources toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (labDetailedCourseResources)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		labDetailedCourseResourcesImpl labDetailedCourseResourcesImpl = new labDetailedCourseResourcesImpl();

		labDetailedCourseResourcesImpl.setPK_courseResourceId(getPK_courseResourceId());
		labDetailedCourseResourcesImpl.setGroupId(getGroupId());
		labDetailedCourseResourcesImpl.setUserId(getUserId());
		labDetailedCourseResourcesImpl.setCreateDate(getCreateDate());
		labDetailedCourseResourcesImpl.setModifiedDate(getModifiedDate());
		labDetailedCourseResourcesImpl.setPK_projectId(getPK_projectId());
		labDetailedCourseResourcesImpl.setPK_courseId(getPK_courseId());
		labDetailedCourseResourcesImpl.setTextbokTitle(getTextbokTitle());
		labDetailedCourseResourcesImpl.setPublisherName(getPublisherName());
		labDetailedCourseResourcesImpl.setAuthor(getAuthor());
		labDetailedCourseResourcesImpl.setIsbn(getIsbn());

		labDetailedCourseResourcesImpl.resetOriginalValues();

		return labDetailedCourseResourcesImpl;
	}

	@Override
	public int compareTo(labDetailedCourseResources labDetailedCourseResources) {
		long primaryKey = labDetailedCourseResources.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof labDetailedCourseResources)) {
			return false;
		}

		labDetailedCourseResources labDetailedCourseResources = (labDetailedCourseResources)obj;

		long primaryKey = labDetailedCourseResources.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		labDetailedCourseResourcesModelImpl labDetailedCourseResourcesModelImpl = this;

		labDetailedCourseResourcesModelImpl._setModifiedDate = false;

		labDetailedCourseResourcesModelImpl._originalPK_courseId = labDetailedCourseResourcesModelImpl._PK_courseId;

		labDetailedCourseResourcesModelImpl._setOriginalPK_courseId = false;

		labDetailedCourseResourcesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<labDetailedCourseResources> toCacheModel() {
		labDetailedCourseResourcesCacheModel labDetailedCourseResourcesCacheModel =
			new labDetailedCourseResourcesCacheModel();

		labDetailedCourseResourcesCacheModel.PK_courseResourceId = getPK_courseResourceId();

		labDetailedCourseResourcesCacheModel.groupId = getGroupId();

		labDetailedCourseResourcesCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			labDetailedCourseResourcesCacheModel.createDate = createDate.getTime();
		}
		else {
			labDetailedCourseResourcesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			labDetailedCourseResourcesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			labDetailedCourseResourcesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		labDetailedCourseResourcesCacheModel.PK_projectId = getPK_projectId();

		labDetailedCourseResourcesCacheModel.PK_courseId = getPK_courseId();

		labDetailedCourseResourcesCacheModel.textbokTitle = getTextbokTitle();

		String textbokTitle = labDetailedCourseResourcesCacheModel.textbokTitle;

		if ((textbokTitle != null) && (textbokTitle.length() == 0)) {
			labDetailedCourseResourcesCacheModel.textbokTitle = null;
		}

		labDetailedCourseResourcesCacheModel.publisherName = getPublisherName();

		String publisherName = labDetailedCourseResourcesCacheModel.publisherName;

		if ((publisherName != null) && (publisherName.length() == 0)) {
			labDetailedCourseResourcesCacheModel.publisherName = null;
		}

		labDetailedCourseResourcesCacheModel.author = getAuthor();

		String author = labDetailedCourseResourcesCacheModel.author;

		if ((author != null) && (author.length() == 0)) {
			labDetailedCourseResourcesCacheModel.author = null;
		}

		labDetailedCourseResourcesCacheModel.isbn = getIsbn();

		String isbn = labDetailedCourseResourcesCacheModel.isbn;

		if ((isbn != null) && (isbn.length() == 0)) {
			labDetailedCourseResourcesCacheModel.isbn = null;
		}

		return labDetailedCourseResourcesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{PK_courseResourceId=");
		sb.append(getPK_courseResourceId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", PK_projectId=");
		sb.append(getPK_projectId());
		sb.append(", PK_courseId=");
		sb.append(getPK_courseId());
		sb.append(", textbokTitle=");
		sb.append(getTextbokTitle());
		sb.append(", publisherName=");
		sb.append(getPublisherName());
		sb.append(", author=");
		sb.append(getAuthor());
		sb.append(", isbn=");
		sb.append(getIsbn());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.collaborated.entity.model.labDetailedCourseResources");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>PK_courseResourceId</column-name><column-value><![CDATA[");
		sb.append(getPK_courseResourceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PK_projectId</column-name><column-value><![CDATA[");
		sb.append(getPK_projectId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PK_courseId</column-name><column-value><![CDATA[");
		sb.append(getPK_courseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>textbokTitle</column-name><column-value><![CDATA[");
		sb.append(getTextbokTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>publisherName</column-name><column-value><![CDATA[");
		sb.append(getPublisherName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>author</column-name><column-value><![CDATA[");
		sb.append(getAuthor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isbn</column-name><column-value><![CDATA[");
		sb.append(getIsbn());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = labDetailedCourseResources.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			labDetailedCourseResources.class
		};
	private long _PK_courseResourceId;
	private long _groupId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _PK_projectId;
	private long _PK_courseId;
	private long _originalPK_courseId;
	private boolean _setOriginalPK_courseId;
	private String _textbokTitle;
	private String _publisherName;
	private String _author;
	private String _isbn;
	private long _columnBitmask;
	private labDetailedCourseResources _escapedModel;
}