/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.collaborated.entity.model.labDetailedActivityTable;
import com.collaborated.entity.model.labDetailedActivityTableModel;
import com.collaborated.entity.model.labDetailedActivityTableSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the labDetailedActivityTable service. Represents a row in the &quot;collaborated_labDetailedActivityTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link labDetailedActivityTableModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link labDetailedActivityTableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see labDetailedActivityTableImpl
 * @see labDetailedActivityTable
 * @see labDetailedActivityTableModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class labDetailedActivityTableModelImpl extends BaseModelImpl<labDetailedActivityTable>
	implements labDetailedActivityTableModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lab detailed activity table model instance should use the {@link labDetailedActivityTable} interface instead.
	 */
	public static final String TABLE_NAME = "collaborated_labDetailedActivityTable";
	public static final Object[][] TABLE_COLUMNS = {
			{ "PK_activityTableId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "PK_projectId", Types.BIGINT },
			{ "PK_courseId", Types.BIGINT },
			{ "week", Types.BIGINT },
			{ "courseObjective", Types.VARCHAR },
			{ "learningEnvironmentDesign", Types.VARCHAR },
			{ "activity", Types.VARCHAR },
			{ "content", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("PK_activityTableId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("PK_projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("PK_courseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("week", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("courseObjective", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("learningEnvironmentDesign", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("activity", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("content", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table collaborated_labDetailedActivityTable (PK_activityTableId LONG not null primary key,groupId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,PK_projectId LONG,PK_courseId LONG,week LONG,courseObjective VARCHAR(75) null,learningEnvironmentDesign VARCHAR(75) null,activity VARCHAR(75) null,content VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table collaborated_labDetailedActivityTable";
	public static final String ORDER_BY_JPQL = " ORDER BY labDetailedActivityTable.PK_activityTableId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY collaborated_labDetailedActivityTable.PK_activityTableId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.collaborated.entity.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.collaborated.entity.model.labDetailedActivityTable"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.collaborated.entity.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.collaborated.entity.model.labDetailedActivityTable"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static labDetailedActivityTable toModel(
		labDetailedActivityTableSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		labDetailedActivityTable model = new labDetailedActivityTableImpl();

		model.setPK_activityTableId(soapModel.getPK_activityTableId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setPK_projectId(soapModel.getPK_projectId());
		model.setPK_courseId(soapModel.getPK_courseId());
		model.setWeek(soapModel.getWeek());
		model.setCourseObjective(soapModel.getCourseObjective());
		model.setLearningEnvironmentDesign(soapModel.getLearningEnvironmentDesign());
		model.setActivity(soapModel.getActivity());
		model.setContent(soapModel.getContent());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<labDetailedActivityTable> toModels(
		labDetailedActivityTableSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<labDetailedActivityTable> models = new ArrayList<labDetailedActivityTable>(soapModels.length);

		for (labDetailedActivityTableSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.collaborated.entity.service.util.ServiceProps.get(
				"lock.expiration.time.com.collaborated.entity.model.labDetailedActivityTable"));

	public labDetailedActivityTableModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _PK_activityTableId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPK_activityTableId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PK_activityTableId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return labDetailedActivityTable.class;
	}

	@Override
	public String getModelClassName() {
		return labDetailedActivityTable.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("PK_activityTableId", getPK_activityTableId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("PK_projectId", getPK_projectId());
		attributes.put("PK_courseId", getPK_courseId());
		attributes.put("week", getWeek());
		attributes.put("courseObjective", getCourseObjective());
		attributes.put("learningEnvironmentDesign",
			getLearningEnvironmentDesign());
		attributes.put("activity", getActivity());
		attributes.put("content", getContent());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long PK_activityTableId = (Long)attributes.get("PK_activityTableId");

		if (PK_activityTableId != null) {
			setPK_activityTableId(PK_activityTableId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long PK_projectId = (Long)attributes.get("PK_projectId");

		if (PK_projectId != null) {
			setPK_projectId(PK_projectId);
		}

		Long PK_courseId = (Long)attributes.get("PK_courseId");

		if (PK_courseId != null) {
			setPK_courseId(PK_courseId);
		}

		Long week = (Long)attributes.get("week");

		if (week != null) {
			setWeek(week);
		}

		String courseObjective = (String)attributes.get("courseObjective");

		if (courseObjective != null) {
			setCourseObjective(courseObjective);
		}

		String learningEnvironmentDesign = (String)attributes.get(
				"learningEnvironmentDesign");

		if (learningEnvironmentDesign != null) {
			setLearningEnvironmentDesign(learningEnvironmentDesign);
		}

		String activity = (String)attributes.get("activity");

		if (activity != null) {
			setActivity(activity);
		}

		String content = (String)attributes.get("content");

		if (content != null) {
			setContent(content);
		}
	}

	@JSON
	@Override
	public long getPK_activityTableId() {
		return _PK_activityTableId;
	}

	@Override
	public void setPK_activityTableId(long PK_activityTableId) {
		_PK_activityTableId = PK_activityTableId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getPK_projectId() {
		return _PK_projectId;
	}

	@Override
	public void setPK_projectId(long PK_projectId) {
		_PK_projectId = PK_projectId;
	}

	@JSON
	@Override
	public long getPK_courseId() {
		return _PK_courseId;
	}

	@Override
	public void setPK_courseId(long PK_courseId) {
		_PK_courseId = PK_courseId;
	}

	@JSON
	@Override
	public long getWeek() {
		return _week;
	}

	@Override
	public void setWeek(long week) {
		_week = week;
	}

	@JSON
	@Override
	public String getCourseObjective() {
		if (_courseObjective == null) {
			return StringPool.BLANK;
		}
		else {
			return _courseObjective;
		}
	}

	@Override
	public void setCourseObjective(String courseObjective) {
		_courseObjective = courseObjective;
	}

	@JSON
	@Override
	public String getLearningEnvironmentDesign() {
		if (_learningEnvironmentDesign == null) {
			return StringPool.BLANK;
		}
		else {
			return _learningEnvironmentDesign;
		}
	}

	@Override
	public void setLearningEnvironmentDesign(String learningEnvironmentDesign) {
		_learningEnvironmentDesign = learningEnvironmentDesign;
	}

	@JSON
	@Override
	public String getActivity() {
		if (_activity == null) {
			return StringPool.BLANK;
		}
		else {
			return _activity;
		}
	}

	@Override
	public void setActivity(String activity) {
		_activity = activity;
	}

	@JSON
	@Override
	public String getContent() {
		if (_content == null) {
			return StringPool.BLANK;
		}
		else {
			return _content;
		}
	}

	@Override
	public void setContent(String content) {
		_content = content;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			labDetailedActivityTable.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public labDetailedActivityTable toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (labDetailedActivityTable)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		labDetailedActivityTableImpl labDetailedActivityTableImpl = new labDetailedActivityTableImpl();

		labDetailedActivityTableImpl.setPK_activityTableId(getPK_activityTableId());
		labDetailedActivityTableImpl.setGroupId(getGroupId());
		labDetailedActivityTableImpl.setUserId(getUserId());
		labDetailedActivityTableImpl.setCreateDate(getCreateDate());
		labDetailedActivityTableImpl.setModifiedDate(getModifiedDate());
		labDetailedActivityTableImpl.setPK_projectId(getPK_projectId());
		labDetailedActivityTableImpl.setPK_courseId(getPK_courseId());
		labDetailedActivityTableImpl.setWeek(getWeek());
		labDetailedActivityTableImpl.setCourseObjective(getCourseObjective());
		labDetailedActivityTableImpl.setLearningEnvironmentDesign(getLearningEnvironmentDesign());
		labDetailedActivityTableImpl.setActivity(getActivity());
		labDetailedActivityTableImpl.setContent(getContent());

		labDetailedActivityTableImpl.resetOriginalValues();

		return labDetailedActivityTableImpl;
	}

	@Override
	public int compareTo(labDetailedActivityTable labDetailedActivityTable) {
		long primaryKey = labDetailedActivityTable.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof labDetailedActivityTable)) {
			return false;
		}

		labDetailedActivityTable labDetailedActivityTable = (labDetailedActivityTable)obj;

		long primaryKey = labDetailedActivityTable.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		labDetailedActivityTableModelImpl labDetailedActivityTableModelImpl = this;

		labDetailedActivityTableModelImpl._setModifiedDate = false;
	}

	@Override
	public CacheModel<labDetailedActivityTable> toCacheModel() {
		labDetailedActivityTableCacheModel labDetailedActivityTableCacheModel = new labDetailedActivityTableCacheModel();

		labDetailedActivityTableCacheModel.PK_activityTableId = getPK_activityTableId();

		labDetailedActivityTableCacheModel.groupId = getGroupId();

		labDetailedActivityTableCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			labDetailedActivityTableCacheModel.createDate = createDate.getTime();
		}
		else {
			labDetailedActivityTableCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			labDetailedActivityTableCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			labDetailedActivityTableCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		labDetailedActivityTableCacheModel.PK_projectId = getPK_projectId();

		labDetailedActivityTableCacheModel.PK_courseId = getPK_courseId();

		labDetailedActivityTableCacheModel.week = getWeek();

		labDetailedActivityTableCacheModel.courseObjective = getCourseObjective();

		String courseObjective = labDetailedActivityTableCacheModel.courseObjective;

		if ((courseObjective != null) && (courseObjective.length() == 0)) {
			labDetailedActivityTableCacheModel.courseObjective = null;
		}

		labDetailedActivityTableCacheModel.learningEnvironmentDesign = getLearningEnvironmentDesign();

		String learningEnvironmentDesign = labDetailedActivityTableCacheModel.learningEnvironmentDesign;

		if ((learningEnvironmentDesign != null) &&
				(learningEnvironmentDesign.length() == 0)) {
			labDetailedActivityTableCacheModel.learningEnvironmentDesign = null;
		}

		labDetailedActivityTableCacheModel.activity = getActivity();

		String activity = labDetailedActivityTableCacheModel.activity;

		if ((activity != null) && (activity.length() == 0)) {
			labDetailedActivityTableCacheModel.activity = null;
		}

		labDetailedActivityTableCacheModel.content = getContent();

		String content = labDetailedActivityTableCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			labDetailedActivityTableCacheModel.content = null;
		}

		return labDetailedActivityTableCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{PK_activityTableId=");
		sb.append(getPK_activityTableId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", PK_projectId=");
		sb.append(getPK_projectId());
		sb.append(", PK_courseId=");
		sb.append(getPK_courseId());
		sb.append(", week=");
		sb.append(getWeek());
		sb.append(", courseObjective=");
		sb.append(getCourseObjective());
		sb.append(", learningEnvironmentDesign=");
		sb.append(getLearningEnvironmentDesign());
		sb.append(", activity=");
		sb.append(getActivity());
		sb.append(", content=");
		sb.append(getContent());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.collaborated.entity.model.labDetailedActivityTable");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>PK_activityTableId</column-name><column-value><![CDATA[");
		sb.append(getPK_activityTableId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PK_projectId</column-name><column-value><![CDATA[");
		sb.append(getPK_projectId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PK_courseId</column-name><column-value><![CDATA[");
		sb.append(getPK_courseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>week</column-name><column-value><![CDATA[");
		sb.append(getWeek());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>courseObjective</column-name><column-value><![CDATA[");
		sb.append(getCourseObjective());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>learningEnvironmentDesign</column-name><column-value><![CDATA[");
		sb.append(getLearningEnvironmentDesign());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activity</column-name><column-value><![CDATA[");
		sb.append(getActivity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content</column-name><column-value><![CDATA[");
		sb.append(getContent());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = labDetailedActivityTable.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			labDetailedActivityTable.class
		};
	private long _PK_activityTableId;
	private long _groupId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _PK_projectId;
	private long _PK_courseId;
	private long _week;
	private String _courseObjective;
	private String _learningEnvironmentDesign;
	private String _activity;
	private String _content;
	private labDetailedActivityTable _escapedModel;
}