/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.collaborated.entity.model.labScreenProjectPartners;
import com.collaborated.entity.model.labScreenProjectPartnersModel;
import com.collaborated.entity.model.labScreenProjectPartnersSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the labScreenProjectPartners service. Represents a row in the &quot;collaborated_labScreenProjectPartners&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link labScreenProjectPartnersModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link labScreenProjectPartnersImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see labScreenProjectPartnersImpl
 * @see labScreenProjectPartners
 * @see labScreenProjectPartnersModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class labScreenProjectPartnersModelImpl extends BaseModelImpl<labScreenProjectPartners>
	implements labScreenProjectPartnersModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lab screen project partners model instance should use the {@link labScreenProjectPartners} interface instead.
	 */
	public static final String TABLE_NAME = "collaborated_labScreenProjectPartners";
	public static final Object[][] TABLE_COLUMNS = {
			{ "PK_projectPartnerId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "PK_projectId", Types.BIGINT },
			{ "projectPartnerId", Types.BIGINT },
			{ "isActive", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("PK_projectPartnerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("PK_projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectPartnerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("isActive", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table collaborated_labScreenProjectPartners (PK_projectPartnerId LONG not null primary key,groupId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,PK_projectId LONG,projectPartnerId LONG,isActive LONG)";
	public static final String TABLE_SQL_DROP = "drop table collaborated_labScreenProjectPartners";
	public static final String ORDER_BY_JPQL = " ORDER BY labScreenProjectPartners.PK_projectPartnerId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY collaborated_labScreenProjectPartners.PK_projectPartnerId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.collaborated.entity.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.collaborated.entity.model.labScreenProjectPartners"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.collaborated.entity.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.collaborated.entity.model.labScreenProjectPartners"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static labScreenProjectPartners toModel(
		labScreenProjectPartnersSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		labScreenProjectPartners model = new labScreenProjectPartnersImpl();

		model.setPK_projectPartnerId(soapModel.getPK_projectPartnerId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setPK_projectId(soapModel.getPK_projectId());
		model.setProjectPartnerId(soapModel.getProjectPartnerId());
		model.setIsActive(soapModel.getIsActive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<labScreenProjectPartners> toModels(
		labScreenProjectPartnersSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<labScreenProjectPartners> models = new ArrayList<labScreenProjectPartners>(soapModels.length);

		for (labScreenProjectPartnersSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.collaborated.entity.service.util.ServiceProps.get(
				"lock.expiration.time.com.collaborated.entity.model.labScreenProjectPartners"));

	public labScreenProjectPartnersModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _PK_projectPartnerId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPK_projectPartnerId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PK_projectPartnerId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return labScreenProjectPartners.class;
	}

	@Override
	public String getModelClassName() {
		return labScreenProjectPartners.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("PK_projectPartnerId", getPK_projectPartnerId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("PK_projectId", getPK_projectId());
		attributes.put("projectPartnerId", getProjectPartnerId());
		attributes.put("isActive", getIsActive());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long PK_projectPartnerId = (Long)attributes.get("PK_projectPartnerId");

		if (PK_projectPartnerId != null) {
			setPK_projectPartnerId(PK_projectPartnerId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long PK_projectId = (Long)attributes.get("PK_projectId");

		if (PK_projectId != null) {
			setPK_projectId(PK_projectId);
		}

		Long projectPartnerId = (Long)attributes.get("projectPartnerId");

		if (projectPartnerId != null) {
			setProjectPartnerId(projectPartnerId);
		}

		Long isActive = (Long)attributes.get("isActive");

		if (isActive != null) {
			setIsActive(isActive);
		}
	}

	@JSON
	@Override
	public long getPK_projectPartnerId() {
		return _PK_projectPartnerId;
	}

	@Override
	public void setPK_projectPartnerId(long PK_projectPartnerId) {
		_PK_projectPartnerId = PK_projectPartnerId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getPK_projectId() {
		return _PK_projectId;
	}

	@Override
	public void setPK_projectId(long PK_projectId) {
		_PK_projectId = PK_projectId;
	}

	@JSON
	@Override
	public long getProjectPartnerId() {
		return _projectPartnerId;
	}

	@Override
	public void setProjectPartnerId(long projectPartnerId) {
		_projectPartnerId = projectPartnerId;
	}

	@JSON
	@Override
	public long getIsActive() {
		return _isActive;
	}

	@Override
	public void setIsActive(long isActive) {
		_isActive = isActive;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			labScreenProjectPartners.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public labScreenProjectPartners toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (labScreenProjectPartners)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		labScreenProjectPartnersImpl labScreenProjectPartnersImpl = new labScreenProjectPartnersImpl();

		labScreenProjectPartnersImpl.setPK_projectPartnerId(getPK_projectPartnerId());
		labScreenProjectPartnersImpl.setGroupId(getGroupId());
		labScreenProjectPartnersImpl.setUserId(getUserId());
		labScreenProjectPartnersImpl.setCreateDate(getCreateDate());
		labScreenProjectPartnersImpl.setModifiedDate(getModifiedDate());
		labScreenProjectPartnersImpl.setPK_projectId(getPK_projectId());
		labScreenProjectPartnersImpl.setProjectPartnerId(getProjectPartnerId());
		labScreenProjectPartnersImpl.setIsActive(getIsActive());

		labScreenProjectPartnersImpl.resetOriginalValues();

		return labScreenProjectPartnersImpl;
	}

	@Override
	public int compareTo(labScreenProjectPartners labScreenProjectPartners) {
		long primaryKey = labScreenProjectPartners.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof labScreenProjectPartners)) {
			return false;
		}

		labScreenProjectPartners labScreenProjectPartners = (labScreenProjectPartners)obj;

		long primaryKey = labScreenProjectPartners.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		labScreenProjectPartnersModelImpl labScreenProjectPartnersModelImpl = this;

		labScreenProjectPartnersModelImpl._setModifiedDate = false;
	}

	@Override
	public CacheModel<labScreenProjectPartners> toCacheModel() {
		labScreenProjectPartnersCacheModel labScreenProjectPartnersCacheModel = new labScreenProjectPartnersCacheModel();

		labScreenProjectPartnersCacheModel.PK_projectPartnerId = getPK_projectPartnerId();

		labScreenProjectPartnersCacheModel.groupId = getGroupId();

		labScreenProjectPartnersCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			labScreenProjectPartnersCacheModel.createDate = createDate.getTime();
		}
		else {
			labScreenProjectPartnersCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			labScreenProjectPartnersCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			labScreenProjectPartnersCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		labScreenProjectPartnersCacheModel.PK_projectId = getPK_projectId();

		labScreenProjectPartnersCacheModel.projectPartnerId = getProjectPartnerId();

		labScreenProjectPartnersCacheModel.isActive = getIsActive();

		return labScreenProjectPartnersCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{PK_projectPartnerId=");
		sb.append(getPK_projectPartnerId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", PK_projectId=");
		sb.append(getPK_projectId());
		sb.append(", projectPartnerId=");
		sb.append(getProjectPartnerId());
		sb.append(", isActive=");
		sb.append(getIsActive());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.collaborated.entity.model.labScreenProjectPartners");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>PK_projectPartnerId</column-name><column-value><![CDATA[");
		sb.append(getPK_projectPartnerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PK_projectId</column-name><column-value><![CDATA[");
		sb.append(getPK_projectId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>projectPartnerId</column-name><column-value><![CDATA[");
		sb.append(getProjectPartnerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isActive</column-name><column-value><![CDATA[");
		sb.append(getIsActive());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = labScreenProjectPartners.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			labScreenProjectPartners.class
		};
	private long _PK_projectPartnerId;
	private long _groupId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _PK_projectId;
	private long _projectPartnerId;
	private long _isActive;
	private labScreenProjectPartners _escapedModel;
}