/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.collaborated.entity.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.collaborated.entity.model.projectInviteTracking;
import com.collaborated.entity.model.projectInviteTrackingModel;
import com.collaborated.entity.model.projectInviteTrackingSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the projectInviteTracking service. Represents a row in the &quot;collaborated_projectInviteTracking&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link projectInviteTrackingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link projectInviteTrackingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see projectInviteTrackingImpl
 * @see projectInviteTracking
 * @see projectInviteTrackingModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class projectInviteTrackingModelImpl extends BaseModelImpl<projectInviteTracking>
	implements projectInviteTrackingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a project invite tracking model instance should use the {@link projectInviteTracking} interface instead.
	 */
	public static final String TABLE_NAME = "collaborated_projectInviteTracking";
	public static final Object[][] TABLE_COLUMNS = {
			{ "PK_projectInvitationId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "projectId", Types.BIGINT },
			{ "inviteFrom", Types.BIGINT },
			{ "inviteTo", Types.BIGINT },
			{ "invitationStatus", Types.VARCHAR },
			{ "isRead", Types.BIGINT },
			{ "isRemoved", Types.BIGINT },
			{ "messageTitle", Types.VARCHAR },
			{ "messageContent", Types.VARCHAR },
			{ "emailContent", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("PK_projectInvitationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("inviteFrom", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("inviteTo", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("invitationStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isRead", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("isRemoved", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("messageTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("messageContent", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("emailContent", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table collaborated_projectInviteTracking (PK_projectInvitationId LONG not null primary key,groupId LONG,createDate DATE null,modifiedDate DATE null,projectId LONG,inviteFrom LONG,inviteTo LONG,invitationStatus VARCHAR(75) null,isRead LONG,isRemoved LONG,messageTitle VARCHAR(75) null,messageContent VARCHAR(75) null,emailContent VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table collaborated_projectInviteTracking";
	public static final String ORDER_BY_JPQL = " ORDER BY projectInviteTracking.PK_projectInvitationId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY collaborated_projectInviteTracking.PK_projectInvitationId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.collaborated.entity.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.collaborated.entity.model.projectInviteTracking"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.collaborated.entity.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.collaborated.entity.model.projectInviteTracking"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static projectInviteTracking toModel(
		projectInviteTrackingSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		projectInviteTracking model = new projectInviteTrackingImpl();

		model.setPK_projectInvitationId(soapModel.getPK_projectInvitationId());
		model.setGroupId(soapModel.getGroupId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setProjectId(soapModel.getProjectId());
		model.setInviteFrom(soapModel.getInviteFrom());
		model.setInviteTo(soapModel.getInviteTo());
		model.setInvitationStatus(soapModel.getInvitationStatus());
		model.setIsRead(soapModel.getIsRead());
		model.setIsRemoved(soapModel.getIsRemoved());
		model.setMessageTitle(soapModel.getMessageTitle());
		model.setMessageContent(soapModel.getMessageContent());
		model.setEmailContent(soapModel.getEmailContent());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<projectInviteTracking> toModels(
		projectInviteTrackingSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<projectInviteTracking> models = new ArrayList<projectInviteTracking>(soapModels.length);

		for (projectInviteTrackingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.collaborated.entity.service.util.ServiceProps.get(
				"lock.expiration.time.com.collaborated.entity.model.projectInviteTracking"));

	public projectInviteTrackingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _PK_projectInvitationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPK_projectInvitationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PK_projectInvitationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return projectInviteTracking.class;
	}

	@Override
	public String getModelClassName() {
		return projectInviteTracking.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("PK_projectInvitationId", getPK_projectInvitationId());
		attributes.put("groupId", getGroupId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("projectId", getProjectId());
		attributes.put("inviteFrom", getInviteFrom());
		attributes.put("inviteTo", getInviteTo());
		attributes.put("invitationStatus", getInvitationStatus());
		attributes.put("isRead", getIsRead());
		attributes.put("isRemoved", getIsRemoved());
		attributes.put("messageTitle", getMessageTitle());
		attributes.put("messageContent", getMessageContent());
		attributes.put("emailContent", getEmailContent());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long PK_projectInvitationId = (Long)attributes.get(
				"PK_projectInvitationId");

		if (PK_projectInvitationId != null) {
			setPK_projectInvitationId(PK_projectInvitationId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long projectId = (Long)attributes.get("projectId");

		if (projectId != null) {
			setProjectId(projectId);
		}

		Long inviteFrom = (Long)attributes.get("inviteFrom");

		if (inviteFrom != null) {
			setInviteFrom(inviteFrom);
		}

		Long inviteTo = (Long)attributes.get("inviteTo");

		if (inviteTo != null) {
			setInviteTo(inviteTo);
		}

		String invitationStatus = (String)attributes.get("invitationStatus");

		if (invitationStatus != null) {
			setInvitationStatus(invitationStatus);
		}

		Long isRead = (Long)attributes.get("isRead");

		if (isRead != null) {
			setIsRead(isRead);
		}

		Long isRemoved = (Long)attributes.get("isRemoved");

		if (isRemoved != null) {
			setIsRemoved(isRemoved);
		}

		String messageTitle = (String)attributes.get("messageTitle");

		if (messageTitle != null) {
			setMessageTitle(messageTitle);
		}

		String messageContent = (String)attributes.get("messageContent");

		if (messageContent != null) {
			setMessageContent(messageContent);
		}

		String emailContent = (String)attributes.get("emailContent");

		if (emailContent != null) {
			setEmailContent(emailContent);
		}
	}

	@JSON
	@Override
	public long getPK_projectInvitationId() {
		return _PK_projectInvitationId;
	}

	@Override
	public void setPK_projectInvitationId(long PK_projectInvitationId) {
		_PK_projectInvitationId = PK_projectInvitationId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_projectId = projectId;
	}

	@JSON
	@Override
	public long getInviteFrom() {
		return _inviteFrom;
	}

	@Override
	public void setInviteFrom(long inviteFrom) {
		_inviteFrom = inviteFrom;
	}

	@JSON
	@Override
	public long getInviteTo() {
		return _inviteTo;
	}

	@Override
	public void setInviteTo(long inviteTo) {
		_inviteTo = inviteTo;
	}

	@JSON
	@Override
	public String getInvitationStatus() {
		if (_invitationStatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _invitationStatus;
		}
	}

	@Override
	public void setInvitationStatus(String invitationStatus) {
		_invitationStatus = invitationStatus;
	}

	@JSON
	@Override
	public long getIsRead() {
		return _isRead;
	}

	@Override
	public void setIsRead(long isRead) {
		_isRead = isRead;
	}

	@JSON
	@Override
	public long getIsRemoved() {
		return _isRemoved;
	}

	@Override
	public void setIsRemoved(long isRemoved) {
		_isRemoved = isRemoved;
	}

	@JSON
	@Override
	public String getMessageTitle() {
		if (_messageTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _messageTitle;
		}
	}

	@Override
	public void setMessageTitle(String messageTitle) {
		_messageTitle = messageTitle;
	}

	@JSON
	@Override
	public String getMessageContent() {
		if (_messageContent == null) {
			return StringPool.BLANK;
		}
		else {
			return _messageContent;
		}
	}

	@Override
	public void setMessageContent(String messageContent) {
		_messageContent = messageContent;
	}

	@JSON
	@Override
	public String getEmailContent() {
		if (_emailContent == null) {
			return StringPool.BLANK;
		}
		else {
			return _emailContent;
		}
	}

	@Override
	public void setEmailContent(String emailContent) {
		_emailContent = emailContent;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			projectInviteTracking.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public projectInviteTracking toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (projectInviteTracking)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		projectInviteTrackingImpl projectInviteTrackingImpl = new projectInviteTrackingImpl();

		projectInviteTrackingImpl.setPK_projectInvitationId(getPK_projectInvitationId());
		projectInviteTrackingImpl.setGroupId(getGroupId());
		projectInviteTrackingImpl.setCreateDate(getCreateDate());
		projectInviteTrackingImpl.setModifiedDate(getModifiedDate());
		projectInviteTrackingImpl.setProjectId(getProjectId());
		projectInviteTrackingImpl.setInviteFrom(getInviteFrom());
		projectInviteTrackingImpl.setInviteTo(getInviteTo());
		projectInviteTrackingImpl.setInvitationStatus(getInvitationStatus());
		projectInviteTrackingImpl.setIsRead(getIsRead());
		projectInviteTrackingImpl.setIsRemoved(getIsRemoved());
		projectInviteTrackingImpl.setMessageTitle(getMessageTitle());
		projectInviteTrackingImpl.setMessageContent(getMessageContent());
		projectInviteTrackingImpl.setEmailContent(getEmailContent());

		projectInviteTrackingImpl.resetOriginalValues();

		return projectInviteTrackingImpl;
	}

	@Override
	public int compareTo(projectInviteTracking projectInviteTracking) {
		long primaryKey = projectInviteTracking.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof projectInviteTracking)) {
			return false;
		}

		projectInviteTracking projectInviteTracking = (projectInviteTracking)obj;

		long primaryKey = projectInviteTracking.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		projectInviteTrackingModelImpl projectInviteTrackingModelImpl = this;

		projectInviteTrackingModelImpl._setModifiedDate = false;
	}

	@Override
	public CacheModel<projectInviteTracking> toCacheModel() {
		projectInviteTrackingCacheModel projectInviteTrackingCacheModel = new projectInviteTrackingCacheModel();

		projectInviteTrackingCacheModel.PK_projectInvitationId = getPK_projectInvitationId();

		projectInviteTrackingCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			projectInviteTrackingCacheModel.createDate = createDate.getTime();
		}
		else {
			projectInviteTrackingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			projectInviteTrackingCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			projectInviteTrackingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		projectInviteTrackingCacheModel.projectId = getProjectId();

		projectInviteTrackingCacheModel.inviteFrom = getInviteFrom();

		projectInviteTrackingCacheModel.inviteTo = getInviteTo();

		projectInviteTrackingCacheModel.invitationStatus = getInvitationStatus();

		String invitationStatus = projectInviteTrackingCacheModel.invitationStatus;

		if ((invitationStatus != null) && (invitationStatus.length() == 0)) {
			projectInviteTrackingCacheModel.invitationStatus = null;
		}

		projectInviteTrackingCacheModel.isRead = getIsRead();

		projectInviteTrackingCacheModel.isRemoved = getIsRemoved();

		projectInviteTrackingCacheModel.messageTitle = getMessageTitle();

		String messageTitle = projectInviteTrackingCacheModel.messageTitle;

		if ((messageTitle != null) && (messageTitle.length() == 0)) {
			projectInviteTrackingCacheModel.messageTitle = null;
		}

		projectInviteTrackingCacheModel.messageContent = getMessageContent();

		String messageContent = projectInviteTrackingCacheModel.messageContent;

		if ((messageContent != null) && (messageContent.length() == 0)) {
			projectInviteTrackingCacheModel.messageContent = null;
		}

		projectInviteTrackingCacheModel.emailContent = getEmailContent();

		String emailContent = projectInviteTrackingCacheModel.emailContent;

		if ((emailContent != null) && (emailContent.length() == 0)) {
			projectInviteTrackingCacheModel.emailContent = null;
		}

		return projectInviteTrackingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{PK_projectInvitationId=");
		sb.append(getPK_projectInvitationId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", projectId=");
		sb.append(getProjectId());
		sb.append(", inviteFrom=");
		sb.append(getInviteFrom());
		sb.append(", inviteTo=");
		sb.append(getInviteTo());
		sb.append(", invitationStatus=");
		sb.append(getInvitationStatus());
		sb.append(", isRead=");
		sb.append(getIsRead());
		sb.append(", isRemoved=");
		sb.append(getIsRemoved());
		sb.append(", messageTitle=");
		sb.append(getMessageTitle());
		sb.append(", messageContent=");
		sb.append(getMessageContent());
		sb.append(", emailContent=");
		sb.append(getEmailContent());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.collaborated.entity.model.projectInviteTracking");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>PK_projectInvitationId</column-name><column-value><![CDATA[");
		sb.append(getPK_projectInvitationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>projectId</column-name><column-value><![CDATA[");
		sb.append(getProjectId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inviteFrom</column-name><column-value><![CDATA[");
		sb.append(getInviteFrom());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inviteTo</column-name><column-value><![CDATA[");
		sb.append(getInviteTo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>invitationStatus</column-name><column-value><![CDATA[");
		sb.append(getInvitationStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isRead</column-name><column-value><![CDATA[");
		sb.append(getIsRead());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isRemoved</column-name><column-value><![CDATA[");
		sb.append(getIsRemoved());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>messageTitle</column-name><column-value><![CDATA[");
		sb.append(getMessageTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>messageContent</column-name><column-value><![CDATA[");
		sb.append(getMessageContent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emailContent</column-name><column-value><![CDATA[");
		sb.append(getEmailContent());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = projectInviteTracking.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			projectInviteTracking.class
		};
	private long _PK_projectInvitationId;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _projectId;
	private long _inviteFrom;
	private long _inviteTo;
	private String _invitationStatus;
	private long _isRead;
	private long _isRemoved;
	private String _messageTitle;
	private String _messageContent;
	private String _emailContent;
	private projectInviteTracking _escapedModel;
}